In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os

for root, dirs, files in os.walk("/content/drive/MyDrive"):
    for file in files:
        if file == "6ab10eb3b23ba_student_resource.zip":
            print("ZIP found!")
            print(os.path.join(root, file))

ZIP found!
/content/drive/MyDrive/Business_model_amazon/6ab10eb3b23ba_student_resource.zip

In [ ]:
import os
import zipfile

zip_path = "/content/drive/MyDrive/Business_model_amazon/6ab10eb3b23ba_student_resource.zip"
extract_path = "/content/drive/MyDrive/Business_model_amazon/extracted_data"

os.makedirs(extract_path, exist_ok=True)

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_path)

print("Extraction completed successfully!")

Extraction completed successfully!

In [ ]:
import os

extract_path = "/content/drive/MyDrive/Business_model_amazon/extracted_data"

for root, dirs, files in os.walk(extract_path):
    level = root.replace(extract_path, "").count(os.sep)
    indent = "    " * level
    print(f"{indent}{os.path.basename(root)}/")

    for file in files:
        print(f"{indent}    {file}")

extracted_data/
    student_resource/
        Documentation_template.md
        .DS_Store
        README.md
        dataset/
            .DS_Store
            test/
                test_source2.tsv
                test_source3.tsv
                test_source1.tsv
            train/
                train_ground_truth.tsv
                train_source2.tsv
                train_source3.tsv
                train_source1.tsv
        utils/
            validate_submission.py
    __MACOSX/
        ._student_resource
        student_resource/
            ._Documentation_template.md
            ._.DS_Store
            ._dataset
            ._utils
            ._README.md
            dataset/
                ._.DS_Store
                ._test
                ._train
                test/
                    ._test_source2.tsv
                    ._test_source3.tsv
                    ._test_source1.tsv
                train/
                    ._train_ground_truth.tsv
                    ._train_source2.tsv
                    ._train_source3.tsv
                    ._train_source1.tsv
            utils/
                ._validate_submission.py

In [ ]:
import pandas as pd

base_path = "/content/drive/MyDrive/Business_model_amazon/extracted_data/student_resource/dataset"

train_source1 = pd.read_csv(
    base_path + "/train/train_source1.tsv",
    sep="\t"
)

print("Shape:", train_source1.shape)
print("\nColumns:")
print(train_source1.columns.tolist())

print("\nFirst 5 rows:")
display(train_source1.head())

Shape: (2206821, 4)

Columns:
['entity_id', 'business_name', 'business_address', 'country']

First 5 rows:

,entity_id,business_name,business_address,country
0,S1-925783039,Orelee's Barbershop,"1795 Westchester Drive, High Point, NC",US
1,S1-773889195,Prime Money,"17560 Ellis Road, Tahlequah, OK",US
2,S1-377745466,B+ Retail Inc,"1712 Montebello Avenue, Phoenix, AZ",US
3,S1-133037285,Christ Chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",US
4,S1-755362802,Prabhav Business Center,"797, Lake Town Block A, Kolkata, Howrah, West ...",India

In [ ]:
print("Missing values:")
print(train_source1.isnull().sum())

print("\nMissing percentage:")
print((train_source1.isnull().mean() * 100).round(2))

Missing values:
entity_id           0
business_name       0
business_address    0
country             0
dtype: int64

Missing percentage:
entity_id           0.0
business_name       0.0
business_address    0.0
country             0.0
dtype: float64

In [ ]:
print("Duplicate entity_ids:", train_source1["entity_id"].duplicated().sum())

print("Completely duplicate rows:", train_source1.duplicated().sum())

print("Duplicate business names:", train_source1["business_name"].duplicated().sum())

print("Duplicate addresses:", train_source1["business_address"].duplicated().sum())

Duplicate entity_ids: 0
Completely duplicate rows: 0
Duplicate business names: 667592
Duplicate addresses: 76215

In [ ]:
country_counts = train_source1["country"].value_counts()

print("Number of unique countries:", train_source1["country"].nunique())

print("\nTop 20 countries:")
print(country_counts.head(20))

Number of unique countries: 2

Top 20 countries:
country
US       1323633
India     883188
Name: count, dtype: int64

In [ ]:
print(train_source1["country"].unique())

['US' 'India']

In [ ]:
for country in train_source1["country"].unique():
    print(repr(country), "->", len(country))

'US' -> 2
'India' -> 5

In [ ]:
print(train_source1["business_name"].head(20).to_string(index=False))

                     Orelee's Barbershop
                             Prime Money
                           B+ Retail Inc
                           Christ Chapel
                 Prabhav Business Center
              Custom Wealth Services LLC
Consulting Nyasa Nursing Private Limited
                       Nexus Anchor Rain
                       Moore Bitwise Inc
              Dermatology Green Medicine
                      Crystal Lending PC
              Dream Construction Limited
                     Kelly Advisory, Inc
                                  Helios
                  Unified Choice Dynamix
              Health Fellowship Partners
        Smart Healthcare Private Limited
                  Callicoat & Dailey Inc
                           Iris Advisors
       Secunderabad Park Private Limited

In [ ]:
name_series = train_source1["business_name"]

print("Names already containing lowercase letters:",
      name_series.str.contains(r"[a-z]", regex=True).sum())

print("Names containing uppercase letters:",
      name_series.str.contains(r"[A-Z]", regex=True).sum())

print("Names that are completely uppercase:",
      (name_series == name_series.str.upper()).sum())

print("Names that are completely lowercase:",
      (name_series == name_series.str.lower()).sum())

Names already containing lowercase letters: 2206821
Names containing uppercase letters: 2206821
Names that are completely uppercase: 0
Names that are completely lowercase: 0

In [ ]:
import re

special_chars = train_source1["business_name"].str.contains(
    r"[^A-Za-z0-9\s]",
    regex=True
)

print("Names containing special characters:", special_chars.sum())
print("Percentage:", round(special_chars.mean() * 100, 2), "%")

Names containing special characters: 461669
Percentage: 20.92 %

In [ ]:
from collections import Counter

chars = Counter()

for name in train_source1["business_name"]:
    for char in name:
        if not char.isalnum() and not char.isspace():
            chars[char] += 1

print("Special characters found:")
for char, count in chars.most_common(30):
    print(repr(char), "->", count)

Special characters found:
'.' -> 302837
',' -> 206162
'&' -> 111912
"'" -> 46610
')' -> 45931
'(' -> 45912
'-' -> 13681
'!' -> 6945
'/' -> 5190
'+' -> 3471
'#' -> 1402
'@' -> 506
'<' -> 116
'_' -> 116
'>' -> 116
':' -> 31
'[' -> 3
']' -> 3
';' -> 1
'\x1a' -> 1

In [ ]:
bad_char = "\x1a"

matches = train_source1[
    train_source1["business_name"].str.contains(
        bad_char,
        regex=False,
        na=False
    )
]

print(matches.to_string(index=False))

   entity_id                                   business_name                                                                                                                        business_address country
S1-930893679 MedchalMalkajgiri Housekeeping Private Limited Plot No 70 (Part), 3Rd And 4Th Floor, Tsiic-Iala, Phase- 1, Cherlapally Village, Kapra Mandal, MedchalMalkajgiri, Hyderabad, Telangana   India

In [ ]:
import re

def has_control_char(text):
    return bool(re.search(r"[\x00-\x1F\x7F]", str(text)))

name_control = train_source1["business_name"].apply(has_control_char)
address_control = train_source1["business_address"].apply(has_control_char)

print("Business names with control characters:", name_control.sum())
print("Addresses with control characters:", address_control.sum())

Business names with control characters: 1
Addresses with control characters: 70

In [ ]:
from collections import Counter

control_chars = Counter()

for address in train_source1["business_address"]:
    for char in str(address):
        if ord(char) < 32 or ord(char) == 127:
            control_chars[repr(char)] += 1

print("Control characters found:")
for char, count in control_chars.items():
    print(char, "->", count)

Control characters found:
'\x1a' -> 82
'\x7f' -> 1
'\x1f' -> 1

In [ ]:
import re

def clean_control_chars(text):
    text = str(text)
    text = re.sub(r"[\x00-\x1F\x7F]", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

train_source1["business_name_clean"] = train_source1["business_name"].apply(clean_control_chars)
train_source1["business_address_clean"] = train_source1["business_address"].apply(clean_control_chars)

print("Cleaning completed.")

Cleaning completed.

In [ ]:
name_control_after = train_source1["business_name_clean"].apply(has_control_char)
address_control_after = train_source1["business_address_clean"].apply(has_control_char)

print("Control characters in cleaned names:", name_control_after.sum())
print("Control characters in cleaned addresses:", address_control_after.sum())

Control characters in cleaned names: 0
Control characters in cleaned addresses: 0

In [ ]:
def has_whitespace_issue(text):
    text = str(text)

    # Leading or trailing whitespace
    if text != text.strip():
        return True

    # Multiple consecutive whitespace characters
    if re.search(r"\s{2,}", text):
        return True

    return False


name_whitespace = train_source1["business_name"].apply(has_whitespace_issue)
address_whitespace = train_source1["business_address"].apply(has_whitespace_issue)

print("Business names with whitespace issues:", name_whitespace.sum())
print("Business addresses with whitespace issues:", address_whitespace.sum())

print("Name percentage:", round(name_whitespace.mean() * 100, 2), "%")
print("Address percentage:", round(address_whitespace.mean() * 100, 2), "%")

Business names with whitespace issues: 0
Business addresses with whitespace issues: 968
Name percentage: 0.0 %
Address percentage: 0.04 %

In [ ]:
address_whitespace_after = train_source1["business_address_clean"].apply(has_whitespace_issue)

print("Whitespace issues in cleaned addresses:", address_whitespace_after.sum())

Whitespace issues in cleaned addresses: 0

In [ ]:
def has_non_ascii(text):
    return any(ord(char) > 127 for char in str(text))

name_non_ascii = train_source1["business_name"].apply(has_non_ascii)
address_non_ascii = train_source1["business_address"].apply(has_non_ascii)

print("Business names with non-ASCII characters:", name_non_ascii.sum())
print("Business addresses with non-ASCII characters:", address_non_ascii.sum())

print("Name percentage:", round(name_non_ascii.mean() * 100, 2), "%")
print("Address percentage:", round(address_non_ascii.mean() * 100, 2), "%")

Business names with non-ASCII characters: 0
Business addresses with non-ASCII characters: 554
Name percentage: 0.0 %
Address percentage: 0.03 %

In [ ]:
from collections import Counter

non_ascii_chars = Counter()

for address in train_source1["business_address"]:
    for char in str(address):
        if ord(char) > 127:
            non_ascii_chars[char] += 1

print("Non-ASCII characters found:")

for char, count in non_ascii_chars.most_common():
    print(repr(char), "->", count)

Non-ASCII characters found:
'\x80' -> 657
'Â' -> 495
'\x93' -> 468
'â' -> 165
'\x99' -> 124
'\x98' -> 50
'¿' -> 20
'½' -> 20
'\x90' -> 15
'ï' -> 14
'Ï' -> 6
'\x82' -> 1
'¬' -> 1

In [ ]:
non_ascii_addresses = train_source1.loc[
    address_non_ascii,
    ["entity_id", "business_address", "country"]
]

print(non_ascii_addresses.head(20).to_string(index=False))

   entity_id                                                                                                                                business_address country
S1-104226194                                                 A-212, Malhotra Complex, Gali No. Â 01, Vikas Marg, Shakarpur, Laxmi Nagar, East Delhi, Delhi   India
S1-388056557                                                                          C 12/27 ÂA & C 12/28, Lahangpura Aurangabad, Varanasi, Uttar Pradesh   India
S1-403268983   Hyderabad, VspâS Bhavana Surovar, Madhavapuri, Hill Flat No.101, First Floor, Pjr Enclave, Ch, Andanagar, Hyderabad, Plot No.277, Telangana   India
S1-489323344                         14/2, Burdwan Road, Sidhartha Apartment, 6Th Floor, Block Â B, Flat No. 6C (4), Kolkata, Kolkata, Howrah, West Bengal   India
S1-973804694                                                        8-2-293/82/J/B/87/A, Plot Â B, Journalists Colony, Jubilee Hills, Hyderabad, Telangana   India
S1-471705468                                              Survey No. 343P, Sanand-Bavla State Highway, At Modasar, Ta Â Sanand, Sanand, Ahmedabad, Gujarat   India
S1-875657988                         ÂShubh-Aishwaryâ, Sector 75/1, Chintamani Chowk, Chintamani Colony B4, Walhekarwadi, Chin, Chwad, Pune, Maharashtra   India
S1-372154634                                        Room No Â 107, 1St Floor, Pratap Bhawan, 5 Bahadur Shah Zafar Marg, New Delhi, South West Delhi, Delhi   India
S1-280839281                                                      5Th Floor Dlf Tower ÂB, Jasola District Centre, Jasola, Delhi, South Delhi, Unit No. 514   India
S1-978614056                         Ahmedabad, Gujarat, 411 4Th/F, Ahmedabad, Block ÂC, Tps-14, Sumel Business Park-6, Nr. Dudheshwar Circule, Dudheshwar   India
S1-374293190        307, Agarwal B-2-B Centre Bldg, Dhruv Park, DâMonte Lane, Near Malad Industrial Estate, Mala, D West, Mumbai, Mumbai City, Maharashtra   India
S1-567740277                                                       South City, #Arekeremico Layout, Layout, Bangalore Â, Ka, Bangalore, A1-1201, Karnataka   India
S1-860468109                    Royal Diam, Fl No.2, Rs-433/1, Sub Plâ3 Tpsâ3 Fpâ300 Nandu Doshi Ni Wadi, Vasta Devdi Road, K, Atargam, Surat, Gujarat   India
S1-330969930                                                                         # 64, Pocket-1, Block ÂA, Sector-17, Rohini, Delhi, North West, Delhi   India
S1-693574917                                        1St Floor, D-Wing, Hdil Kaledonia, Sahar Road Andheri Â East, Mumbai, Mumbai, Mumbai City, Maharashtra   India
S1-922662044                                                          Jetpur, Rajkot, Gujarat, Plot No 16-17, Survey No 81 Nr LionâS School, Junagadh Road   India
 S1-96542326 Ghaziabad, 1St Floor, Ghaziabad, Plot No.A Â 339 Khasra No.1068, Vikashngr Opp. Uttam Toyota Car Show Room Delhi-Me, Erut Road, Uttar Pradesh   India
S1-774926156                                          # 31-3-2235, TngoâS Colony, Waddepalli Near Shyama Ac Garden, Hanumakonda, Warangal Urban, Telangana   India
S1-832472725                                                                       Shop No. 16, Bptp Park Street Sector Â 37 D, Gurugram, Gurgaon, Haryana   India
S1-492758374                                                                              P. No. 1264 B Ambawadi Nr. ManglamaâS Mandir, Bhavnagar, Gujarat   India

In [ ]:
from collections import Counter

corrupted_sequences = Counter()

for address in train_source1.loc[address_non_ascii, "business_address"]:
    for i in range(len(address) - 2):
        seq = address[i:i+3]
        if any(ord(c) > 127 for c in seq):
            corrupted_sequences[seq] += 1

print("Common 3-character sequences containing non-ASCII characters:")

for seq, count in corrupted_sequences.most_common(30):
    print(repr(seq), "->", count)

Common 3-character sequences containing non-ASCII characters:
' Â\x80' -> 475
'Â\x80\x93' -> 434
'\x80\x93 ' -> 366
'â\x80\x99' -> 116
'\x93 1' -> 66
'r Â' -> 60
'\x80\x99S' -> 58
'\x99S ' -> 51
'Â\x80\x98' -> 49
'o Â' -> 47
'. Â' -> 44
'\x80\x99 ' -> 39
'e Â' -> 38
't Â' -> 35
'k Â' -> 34
'â\x80\x93' -> 34
', Â' -> 28
'\x93 2' -> 27
'\x93 4' -> 23
'\x93 A' -> 23
'\x93 3' -> 22
'a Â' -> 21
'\x93 6' -> 16
'\x93 I' -> 16
'l Â' -> 16
'\x80\x93B' -> 15
'\x80\x93,' -> 15
'\x93, ' -> 15
'\x93 5' -> 15
'\x80\x99,' -> 14

In [ ]:
def repair_encoding(text):
    try:
        return text.encode("latin1").decode("utf-8")
    except (UnicodeEncodeError, UnicodeDecodeError):
        return text

test_addresses = train_source1.loc[
    address_non_ascii,
    "business_address"
].head(20)

for address in test_addresses:
    repaired = repair_encoding(address)
    print("BEFORE:", address)
    print("AFTER :", repaired)
    print("-" * 100)

BEFORE: A-212, Malhotra Complex, Gali No. Â 01, Vikas Marg, Shakarpur, Laxmi Nagar, East Delhi, Delhi
AFTER : A-212, Malhotra Complex, Gali No. Â 01, Vikas Marg, Shakarpur, Laxmi Nagar, East Delhi, Delhi
----------------------------------------------------------------------------------------------------
BEFORE: C 12/27 ÂA & C 12/28, Lahangpura Aurangabad, Varanasi, Uttar Pradesh
AFTER : C 12/27 ÂA & C 12/28, Lahangpura Aurangabad, Varanasi, Uttar Pradesh
----------------------------------------------------------------------------------------------------
BEFORE: Hyderabad, VspâS Bhavana Surovar, Madhavapuri, Hill Flat No.101, First Floor, Pjr Enclave, Ch, Andanagar, Hyderabad, Plot No.277, Telangana
AFTER : Hyderabad, Vsp’S Bhavana Surovar, Madhavapuri, Hill Flat No.101, First Floor, Pjr Enclave, Ch, Andanagar, Hyderabad, Plot No.277, Telangana
----------------------------------------------------------------------------------------------------
BEFORE: 14/2, Burdwan Road, Sidhartha Apartment, 6Th Floor, Block Â B, Flat No. 6C (4), Kolkata, Kolkata, Howrah, West Bengal
AFTER : 14/2, Burdwan Road, Sidhartha Apartment, 6Th Floor, Block Â B, Flat No. 6C (4), Kolkata, Kolkata, Howrah, West Bengal
----------------------------------------------------------------------------------------------------
BEFORE: 8-2-293/82/J/B/87/A, Plot Â B, Journalists Colony, Jubilee Hills, Hyderabad, Telangana
AFTER : 8-2-293/82/J/B/87/A, Plot Â B, Journalists Colony, Jubilee Hills, Hyderabad, Telangana
----------------------------------------------------------------------------------------------------
BEFORE: Survey No. 343P, Sanand-Bavla State Highway, At Modasar, Ta Â Sanand, Sanand, Ahmedabad, Gujarat
AFTER : Survey No. 343P, Sanand-Bavla State Highway, At Modasar, Ta Â Sanand, Sanand, Ahmedabad, Gujarat
----------------------------------------------------------------------------------------------------
BEFORE: ÂShubh-Aishwaryâ, Sector 75/1, Chintamani Chowk, Chintamani Colony B4, Walhekarwadi, Chin, Chwad, Pune, Maharashtra
AFTER : ÂShubh-Aishwaryâ, Sector 75/1, Chintamani Chowk, Chintamani Colony B4, Walhekarwadi, Chin, Chwad, Pune, Maharashtra
----------------------------------------------------------------------------------------------------
BEFORE: Room No Â 107, 1St Floor, Pratap Bhawan, 5 Bahadur Shah Zafar Marg, New Delhi, South West Delhi, Delhi
AFTER : Room No Â 107, 1St Floor, Pratap Bhawan, 5 Bahadur Shah Zafar Marg, New Delhi, South West Delhi, Delhi
----------------------------------------------------------------------------------------------------
BEFORE: 5Th Floor Dlf Tower ÂB, Jasola District Centre, Jasola, Delhi, South Delhi, Unit No. 514
AFTER : 5Th Floor Dlf Tower ÂB, Jasola District Centre, Jasola, Delhi, South Delhi, Unit No. 514
----------------------------------------------------------------------------------------------------
BEFORE: Ahmedabad, Gujarat, 411 4Th/F, Ahmedabad, Block ÂC, Tps-14, Sumel Business Park-6, Nr. Dudheshwar Circule, Dudheshwar
AFTER : Ahmedabad, Gujarat, 411 4Th/F, Ahmedabad, Block ÂC, Tps-14, Sumel Business Park-6, Nr. Dudheshwar Circule, Dudheshwar
----------------------------------------------------------------------------------------------------
BEFORE: 307, Agarwal B-2-B Centre Bldg, Dhruv Park, DâMonte Lane, Near Malad Industrial Estate, Mala, D West, Mumbai, Mumbai City, Maharashtra
AFTER : 307, Agarwal B-2-B Centre Bldg, Dhruv Park, D’Monte Lane, Near Malad Industrial Estate, Mala, D West, Mumbai, Mumbai City, Maharashtra
----------------------------------------------------------------------------------------------------
BEFORE: South City, #Arekeremico Layout, Layout, Bangalore Â, Ka, Bangalore, A1-1201, Karnataka
AFTER : South City, #Arekeremico Layout, Layout, Bangalore Â, Ka, Bangalore, A1-1201, Karnataka
----------------------------------------------------------------------------------------------------
BEFORE: Royal Diam, Fl No.2, Rs-433/1, Sub Plâ3 Tpsâ3 Fpâ300 Nandu Doshi Ni Wadi, Vasta Devdi Road, K, Atargam, Surat, Gujarat
AFTER : Royal Diam, Fl No.2, Rs-433/1, Sub Pl–3 Tps–3 Fp–300 Nandu Doshi Ni Wadi, Vasta Devdi Road, K, Atargam, Surat, Gujarat
----------------------------------------------------------------------------------------------------
BEFORE: # 64, Pocket-1, Block ÂA, Sector-17, Rohini, Delhi, North West, Delhi
AFTER : # 64, Pocket-1, Block ÂA, Sector-17, Rohini, Delhi, North West, Delhi
----------------------------------------------------------------------------------------------------
BEFORE: 1St Floor, D-Wing, Hdil Kaledonia, Sahar Road Andheri Â East, Mumbai, Mumbai, Mumbai City, Maharashtra
AFTER : 1St Floor, D-Wing, Hdil Kaledonia, Sahar Road Andheri Â East, Mumbai, Mumbai, Mumbai City, Maharashtra
----------------------------------------------------------------------------------------------------
BEFORE: Jetpur, Rajkot, Gujarat, Plot No 16-17, Survey No 81 Nr LionâS School, Junagadh Road
AFTER : Jetpur, Rajkot, Gujarat, Plot No 16-17, Survey No 81 Nr Lion’S School, Junagadh Road
----------------------------------------------------------------------------------------------------
BEFORE: Ghaziabad, 1St Floor, Ghaziabad, Plot No.A Â 339 Khasra No.1068, Vikashngr Opp. Uttam Toyota Car Show Room Delhi-Me, Erut Road, Uttar Pradesh
AFTER : Ghaziabad, 1St Floor, Ghaziabad, Plot No.A Â 339 Khasra No.1068, Vikashngr Opp. Uttam Toyota Car Show Room Delhi-Me, Erut Road, Uttar Pradesh
----------------------------------------------------------------------------------------------------
BEFORE: # 31-3-2235, TngoâS Colony, Waddepalli Near Shyama Ac Garden, Hanumakonda, Warangal Urban, Telangana
AFTER : # 31-3-2235, Tngo’S Colony, Waddepalli Near Shyama Ac Garden, Hanumakonda, Warangal Urban, Telangana
----------------------------------------------------------------------------------------------------
BEFORE: Shop No. 16, Bptp Park Street Sector Â 37 D, Gurugram, Gurgaon, Haryana
AFTER : Shop No. 16, Bptp Park Street Sector Â 37 D, Gurugram, Gurgaon, Haryana
----------------------------------------------------------------------------------------------------
BEFORE: P. No. 1264 B Ambawadi Nr. ManglamaâS Mandir, Bhavnagar, Gujarat
AFTER : P. No. 1264 B Ambawadi Nr. Manglama’S Mandir, Bhavnagar, Gujarat
----------------------------------------------------------------------------------------------------

In [ ]:
# Show all unique non-ASCII characters with their Unicode code points

for char, count in non_ascii_chars.most_common():
    print(
        repr(char),
        "->",
        count,
        "Unicode:",
        f"U+{ord(char):04X}"
    )

'\x80' -> 657 Unicode: U+0080
'Â' -> 495 Unicode: U+00C2
'\x93' -> 468 Unicode: U+0093
'â' -> 165 Unicode: U+00E2
'\x99' -> 124 Unicode: U+0099
'\x98' -> 50 Unicode: U+0098
'¿' -> 20 Unicode: U+00BF
'½' -> 20 Unicode: U+00BD
'\x90' -> 15 Unicode: U+0090
'ï' -> 14 Unicode: U+00EF
'Ï' -> 6 Unicode: U+00CF
'\x82' -> 1 Unicode: U+0082
'¬' -> 1 Unicode: U+00AC

In [ ]:
def repair_mojibake(text):
    text = str(text)

    try:
        repaired = text.encode("latin1").decode("utf-8")
        return repaired
    except (UnicodeEncodeError, UnicodeDecodeError):
        return text

In [ ]:
test_repaired = train_source1.loc[
    address_non_ascii, "business_address"
].apply(repair_mojibake)

changes = (
    train_source1.loc[address_non_ascii, "business_address"].values
    != test_repaired.values
)

print("Addresses changed by repair:", changes.sum())
print("Addresses unchanged:", (~changes).sum())

Addresses changed by repair: 106
Addresses unchanged: 448

In [ ]:
original = train_source1.loc[
    address_non_ascii, "business_address"
].reset_index(drop=True)

repaired = test_repaired.reset_index(drop=True)

changed = original != repaired

comparison = pd.DataFrame({
    "original": original[changed],
    "repaired": repaired[changed]
})

print(comparison.head(30).to_string(index=False))

                                                                                                                                     original                                                                                                                                    repaired
Hyderabad, VspâS Bhavana Surovar, Madhavapuri, Hill Flat No.101, First Floor, Pjr Enclave, Ch, Andanagar, Hyderabad, Plot No.277, Telangana Hyderabad, Vsp’S Bhavana Surovar, Madhavapuri, Hill Flat No.101, First Floor, Pjr Enclave, Ch, Andanagar, Hyderabad, Plot No.277, Telangana
     307, Agarwal B-2-B Centre Bldg, Dhruv Park, DâMonte Lane, Near Malad Industrial Estate, Mala, D West, Mumbai, Mumbai City, Maharashtra      307, Agarwal B-2-B Centre Bldg, Dhruv Park, D’Monte Lane, Near Malad Industrial Estate, Mala, D West, Mumbai, Mumbai City, Maharashtra
                 Royal Diam, Fl No.2, Rs-433/1, Sub Plâ3 Tpsâ3 Fpâ300 Nandu Doshi Ni Wadi, Vasta Devdi Road, K, Atargam, Surat, Gujarat                      Royal Diam, Fl No.2, Rs-433/1, Sub Pl–3 Tps–3 Fp–300 Nandu Doshi Ni Wadi, Vasta Devdi Road, K, Atargam, Surat, Gujarat
                                                       Jetpur, Rajkot, Gujarat, Plot No 16-17, Survey No 81 Nr LionâS School, Junagadh Road                                                        Jetpur, Rajkot, Gujarat, Plot No 16-17, Survey No 81 Nr Lion’S School, Junagadh Road
                                       # 31-3-2235, TngoâS Colony, Waddepalli Near Shyama Ac Garden, Hanumakonda, Warangal Urban, Telangana                                        # 31-3-2235, Tngo’S Colony, Waddepalli Near Shyama Ac Garden, Hanumakonda, Warangal Urban, Telangana
                                                                           P. No. 1264 B Ambawadi Nr. ManglamaâS Mandir, Bhavnagar, Gujarat                                                                            P. No. 1264 B Ambawadi Nr. Manglama’S Mandir, Bhavnagar, Gujarat
                                                       Hyderabad, Telangana, Plot No. 706, 1-113/Tb/Sa/706, SupranavaâS Solitaire, Kondapur                                                        Hyderabad, Telangana, Plot No. 706, 1-113/Tb/Sa/706, Supranava’S Solitaire, Kondapur
                                         Chennai, Plot No. 33, Tamil Nadu, Sidco Thirumullaivoyal, WomenâS Industrial Park, Kattur, Chennai                                          Chennai, Plot No. 33, Tamil Nadu, Sidco Thirumullaivoyal, Women’S Industrial Park, Kattur, Chennai
                                                            Flat No 14284, Prestige Lakesideï¿½Habitat, Bangalore North, Bangalore, Karnataka                                                             Flat No 14284, Prestige Lakeside�Habitat, Bangalore North, Bangalore, Karnataka
                                                 Plot No. 140A IiâNd Floor, Sindhi Colony, Jalna Road, Cts No14987, Maharashtra, Aurangabad                                                  Plot No. 140A Ii’Nd Floor, Sindhi Colony, Jalna Road, Cts No14987, Maharashtra, Aurangabad
                                                                                       'Samanvayâ, 600 Tapovan Ambawadi, Ahmedabad, Gujarat                                                                                        'Samanvay’, 600 Tapovan Ambawadi, Ahmedabad, Gujarat
    Office No.1, 6Th Floor, TowerâB, Plot No A-44, A-45 Embassy Galaxy Business Park, Sector -62, Noida, Gautam Buddha Nagar, Uttar Pradesh     Office No.1, 6Th Floor, Tower–B, Plot No A-44, A-45 Embassy Galaxy Business Park, Sector -62, Noida, Gautam Buddha Nagar, Uttar Pradesh
                                       ZonahâS Crescent, Fifth Floor M. No. 8-2-682/2/E, Road No. 12, Banja, Ra Hills, Hyderabad, Telangana                                        Zonah’S Crescent, Fifth Floor M. No. 8-2-682/2/E, Road No. 12, Banja, Ra Hills, Hyderabad, Telangana
                                                              1St Floor, 7- Jain Colony, Nagar ShethâS Vando, Gheekanta, Ahmedabad, Gujarat                                                               1St Floor, 7- Jain Colony, Nagar Sheth’S Vando, Gheekanta, Ahmedabad, Gujarat
    Coronation Anand Tower, First Floor 116-117, Vibhuti Khand, Gomtinagar, Lucknow, Oppï¿½Sushmaï¿½Hospital, Lucknow, Uttar Pradesh, Lucknow       Coronation Anand Tower, First Floor 116-117, Vibhuti Khand, Gomtinagar, Lucknow, Opp�Sushma�Hospital, Lucknow, Uttar Pradesh, Lucknow
                                                                                    129/Bâ2, Ankleshwar 3, Ankleshwar (G), Bharuch, Gujarat                                                                                     129/B‐2, Ankleshwar 3, Ankleshwar (G), Bharuch, Gujarat
                                                                            401, Plot No. 7, The YoungâS Cghs Sector 64, Faridabad, Haryana                                                                             401, Plot No. 7, The Young’S Cghs Sector 64, Faridabad, Haryana
                                                                                Plâ294/11, Gidc Pandesara, Surat (M Corpog), Surat, Gujarat                                                                                 Pl‐294/11, Gidc Pandesara, Surat (M Corpog), Surat, Gujarat
                                           Mâ22-D, First Floor, Abul Fazal Enclave Part-1 Jamia Nagar, Okhla, New Delhi, South Delhi, Delhi                                            M–22-D, First Floor, Abul Fazal Enclave Part-1 Jamia Nagar, Okhla, New Delhi, South Delhi, Delhi
                 Office 808, Palm Spring Center Premises Chs Ltd Croma Link Road, Next To DâMart, Malad W, Mumbai, Mumbai City, Maharashtra                  Office 808, Palm Spring Center Premises Chs Ltd Croma Link Road, Next To D’Mart, Malad W, Mumbai, Mumbai City, Maharashtra
    Flat 201, 3-28/7, SankepallyâS Empire, Pot No 07 Mathrushree Colony, Puppalaguda, Maikonda, Main Road, Hyderabad, Rangareddy, Telangana     Flat 201, 3-28/7, Sankepally’S Empire, Pot No 07 Mathrushree Colony, Puppalaguda, Maikonda, Main Road, Hyderabad, Rangareddy, Telangana
                                                                                 No 124, 2Nd Floor, St. JohnâS Church, Bangalore, Karnataka                                                                                  No 124, 2Nd Floor, St. John’S Church, Bangalore, Karnataka
                              Above Bank Of India, Near Queen Mary GirlâS School B.K. Kaul Nagar, Ram Nagar, Pushkar Road, Ajmer, Rajasthan                               Above Bank Of India, Near Queen Mary Girl’S School B.K. Kaul Nagar, Ram Nagar, Pushkar Road, Ajmer, Rajasthan
                                           Near Bidya GhoshâS House. Samar Nagar Champasari, Siliguri, West Bengal, Jalpaiguri, West Bengal                                            Near Bidya Ghosh’S House. Samar Nagar Champasari, Siliguri, West Bengal, Jalpaiguri, West Bengal
                                                New No.85/1, Old No.45, Court Road, Maravaneri, Opp. To St.PaulâS School, Salem, Tamil Nadu                                                 New No.85/1, Old No.45, Court Road, Maravaneri, Opp. To St.Paul’S School, Salem, Tamil Nadu
                                        South West Delhi, Westendï¿½Margï¿½Laneï¿½2, Saidulajab, Property No 55 Third Floor, New Delhi, Delhi                                             South West Delhi, Westend�Marg�Lane�2, Saidulajab, Property No 55 Third Floor, New Delhi, Delhi
                                            P.No.18, Sy NoâS. 31 To 36, Trendz Trinity Building, Madhapur, Hyderabad, Rangareddy, Telangana                                             P.No.18, Sy No’S. 31 To 36, Trendz Trinity Building, Madhapur, Hyderabad, Rangareddy, Telangana
                                                                 Pune, Maharashtra, FlatâB/506 The Island Om Developers Sno.169 Wakad, Pune                                                                  Pune, Maharashtra, Flat–B/506 The Island Om Developers Sno.169 Wakad, Pune
                                                 C/O. Divaben M Prajapati, 948/B/1-2, JatiâS Pole, Sankdi Sheri, Raipur, Ahmedabad, Gujarat                                                  C/O. Divaben M Prajapati, 948/B/1-2, Jati’S Pole, Sankdi Sheri, Raipur, Ahmedabad, Gujarat
      B-1, Bldg Noâ1, Wing-A, New India Chambers, Vlg Mulgaon, Midc Road, Bhd Onida House, And, Heri East, Mumbai, Mumbai City, Maharashtra       B-1, Bldg No–1, Wing-A, New India Chambers, Vlg Mulgaon, Midc Road, Bhd Onida House, And, Heri East, Mumbai, Mumbai City, Maharashtra

In [ ]:
train_source1["business_address_clean"] = (
    train_source1["business_address_clean"]
    .apply(repair_mojibake)
)

print("Encoding repair applied.")

Encoding repair applied.

In [ ]:
non_ascii_after_repair = train_source1["business_address_clean"].apply(has_non_ascii)

print(
    "Addresses with non-ASCII characters after repair:",
    non_ascii_after_repair.sum()
)

Addresses with non-ASCII characters after repair: 554

In [ ]:
train_source1["business_address_clean"] = (
    train_source1["business_address"]
    .apply(repair_mojibake)
    .apply(clean_control_chars)
)

print("Cleaned address column rebuilt.")

Cleaned address column rebuilt.

In [ ]:
non_ascii_after_repair = train_source1["business_address_clean"].apply(has_non_ascii)

print(
    "Addresses with non-ASCII characters after repair:",
    non_ascii_after_repair.sum()
)

Addresses with non-ASCII characters after repair: 554

In [ ]:
test_addresses = train_source1.loc[
    address_non_ascii,
    ["business_address", "business_address_clean"]
].head(20)

print(test_addresses.to_string(index=False))

                                                                                                                               business_address                                                                                                                          business_address_clean
                                                A-212, Malhotra Complex, Gali No. Â 01, Vikas Marg, Shakarpur, Laxmi Nagar, East Delhi, Delhi                                                 A-212, Malhotra Complex, Gali No. Â 01, Vikas Marg, Shakarpur, Laxmi Nagar, East Delhi, Delhi
                                                                         C 12/27 ÂA & C 12/28, Lahangpura Aurangabad, Varanasi, Uttar Pradesh                                                                          C 12/27 ÂA & C 12/28, Lahangpura Aurangabad, Varanasi, Uttar Pradesh
  Hyderabad, VspâS Bhavana Surovar, Madhavapuri, Hill Flat No.101, First Floor, Pjr Enclave, Ch, Andanagar, Hyderabad, Plot No.277, Telangana     Hyderabad, Vsp’S Bhavana Surovar, Madhavapuri, Hill Flat No.101, First Floor, Pjr Enclave, Ch, Andanagar, Hyderabad, Plot No.277, Telangana
                        14/2, Burdwan Road, Sidhartha Apartment, 6Th Floor, Block Â B, Flat No. 6C (4), Kolkata, Kolkata, Howrah, West Bengal                         14/2, Burdwan Road, Sidhartha Apartment, 6Th Floor, Block Â B, Flat No. 6C (4), Kolkata, Kolkata, Howrah, West Bengal
                                                       8-2-293/82/J/B/87/A, Plot Â B, Journalists Colony, Jubilee Hills, Hyderabad, Telangana                                                        8-2-293/82/J/B/87/A, Plot Â B, Journalists Colony, Jubilee Hills, Hyderabad, Telangana
                                             Survey No. 343P, Sanand-Bavla State Highway, At Modasar, Ta Â Sanand, Sanand, Ahmedabad, Gujarat                                              Survey No. 343P, Sanand-Bavla State Highway, At Modasar, Ta Â Sanand, Sanand, Ahmedabad, Gujarat
                        ÂShubh-Aishwaryâ, Sector 75/1, Chintamani Chowk, Chintamani Colony B4, Walhekarwadi, Chin, Chwad, Pune, Maharashtra                         ÂShubh-Aishwaryâ, Sector 75/1, Chintamani Chowk, Chintamani Colony B4, Walhekarwadi, Chin, Chwad, Pune, Maharashtra
                                       Room No Â 107, 1St Floor, Pratap Bhawan, 5 Bahadur Shah Zafar Marg, New Delhi, South West Delhi, Delhi                                        Room No Â 107, 1St Floor, Pratap Bhawan, 5 Bahadur Shah Zafar Marg, New Delhi, South West Delhi, Delhi
                                                     5Th Floor Dlf Tower ÂB, Jasola District Centre, Jasola, Delhi, South Delhi, Unit No. 514                                                      5Th Floor Dlf Tower ÂB, Jasola District Centre, Jasola, Delhi, South Delhi, Unit No. 514
                        Ahmedabad, Gujarat, 411 4Th/F, Ahmedabad, Block ÂC, Tps-14, Sumel Business Park-6, Nr. Dudheshwar Circule, Dudheshwar                         Ahmedabad, Gujarat, 411 4Th/F, Ahmedabad, Block ÂC, Tps-14, Sumel Business Park-6, Nr. Dudheshwar Circule, Dudheshwar
       307, Agarwal B-2-B Centre Bldg, Dhruv Park, DâMonte Lane, Near Malad Industrial Estate, Mala, D West, Mumbai, Mumbai City, Maharashtra          307, Agarwal B-2-B Centre Bldg, Dhruv Park, D’Monte Lane, Near Malad Industrial Estate, Mala, D West, Mumbai, Mumbai City, Maharashtra
                                                      South City, #Arekeremico Layout, Layout, Bangalore Â, Ka, Bangalore, A1-1201, Karnataka                                                       South City, #Arekeremico Layout, Layout, Bangalore Â, Ka, Bangalore, A1-1201, Karnataka
                   Royal Diam, Fl No.2, Rs-433/1, Sub Plâ3 Tpsâ3 Fpâ300 Nandu Doshi Ni Wadi, Vasta Devdi Road, K, Atargam, Surat, Gujarat                          Royal Diam, Fl No.2, Rs-433/1, Sub Pl–3 Tps–3 Fp–300 Nandu Doshi Ni Wadi, Vasta Devdi Road, K, Atargam, Surat, Gujarat
                                                                        # 64, Pocket-1, Block ÂA, Sector-17, Rohini, Delhi, North West, Delhi                                                                         # 64, Pocket-1, Block ÂA, Sector-17, Rohini, Delhi, North West, Delhi
                                       1St Floor, D-Wing, Hdil Kaledonia, Sahar Road Andheri Â East, Mumbai, Mumbai, Mumbai City, Maharashtra                                        1St Floor, D-Wing, Hdil Kaledonia, Sahar Road Andheri Â East, Mumbai, Mumbai, Mumbai City, Maharashtra
                                                         Jetpur, Rajkot, Gujarat, Plot No 16-17, Survey No 81 Nr LionâS School, Junagadh Road                                                            Jetpur, Rajkot, Gujarat, Plot No 16-17, Survey No 81 Nr Lion’S School, Junagadh Road
Ghaziabad, 1St Floor, Ghaziabad, Plot No.A Â 339 Khasra No.1068, Vikashngr Opp. Uttam Toyota Car Show Room Delhi-Me, Erut Road, Uttar Pradesh Ghaziabad, 1St Floor, Ghaziabad, Plot No.A Â 339 Khasra No.1068, Vikashngr Opp. Uttam Toyota Car Show Room Delhi-Me, Erut Road, Uttar Pradesh
                                         # 31-3-2235, TngoâS Colony, Waddepalli Near Shyama Ac Garden, Hanumakonda, Warangal Urban, Telangana                                            # 31-3-2235, Tngo’S Colony, Waddepalli Near Shyama Ac Garden, Hanumakonda, Warangal Urban, Telangana
                                                                      Shop No. 16, Bptp Park Street Sector Â 37 D, Gurugram, Gurgaon, Haryana                                                                       Shop No. 16, Bptp Park Street Sector Â 37 D, Gurugram, Gurgaon, Haryana
                                                                             P. No. 1264 B Ambawadi Nr. ManglamaâS Mandir, Bhavnagar, Gujarat                                                                                P. No. 1264 B Ambawadi Nr. Manglama’S Mandir, Bhavnagar, Gujarat

In [ ]:
remaining_non_ascii = Counter()

for address in train_source1["business_address_clean"]:
    for char in str(address):
        if ord(char) > 127:
            remaining_non_ascii[char] += 1

print("Remaining non-ASCII characters:")

for char, count in remaining_non_ascii.most_common():
    print(repr(char), "->", count, f"U+{ord(char):04X}")

Remaining non-ASCII characters:
'\x80' -> 553 U+0080
'Â' -> 495 U+00C2
'\x93' -> 439 U+0093
'’' -> 63 U+2019
'â' -> 61 U+00E2
'\x99' -> 61 U+0099
'\x98' -> 49 U+0098
'–' -> 29 U+2013
'�' -> 14 U+FFFD
'‐' -> 11 U+2010
'Ï' -> 6 U+00CF
'¿' -> 6 U+00BF
'½' -> 6 U+00BD
'\x90' -> 4 U+0090
'\x82' -> 1 U+0082
'¬' -> 1 U+00AC
'‘' -> 1 U+2018

In [ ]:
replacement_addresses = train_source1.loc[
    train_source1["business_address_clean"].str.contains("�", regex=False),
    ["entity_id", "business_address", "business_address_clean", "country"]
]

print(replacement_addresses.to_string(index=False))

   entity_id                                                                                                                          business_address                                                                                                                business_address_clean country
S1-245666188                                                         Flat No 14284, Prestige Lakesideï¿½Habitat, Bangalore North, Bangalore, Karnataka                                                       Flat No 14284, Prestige Lakeside�Habitat, Bangalore North, Bangalore, Karnataka   India
S1-135387328 Coronation Anand Tower, First Floor 116-117, Vibhuti Khand, Gomtinagar, Lucknow, Oppï¿½Sushmaï¿½Hospital, Lucknow, Uttar Pradesh, Lucknow Coronation Anand Tower, First Floor 116-117, Vibhuti Khand, Gomtinagar, Lucknow, Opp�Sushma�Hospital, Lucknow, Uttar Pradesh, Lucknow   India
S1-240441310                                     South West Delhi, Westendï¿½Margï¿½Laneï¿½2, Saidulajab, Property No 55 Third Floor, New Delhi, Delhi                                       South West Delhi, Westend�Marg�Lane�2, Saidulajab, Property No 55 Third Floor, New Delhi, Delhi   India
S1-439563063                                                                  H-450 Fourth Floor, Flat No 402 Hï¿½Block, New Delhi, South Delhi, Delhi                                                                H-450 Fourth Floor, Flat No 402 H�Block, New Delhi, South Delhi, Delhi   India
S1-581177005                                                                 8/2 Chhoti Gwal Toli, Indore Poleï¿½Noï¿½Ims/17/6, Indore, Madhya Pradesh                                                                 8/2 Chhoti Gwal Toli, Indore Pole�No�Ims/17/6, Indore, Madhya Pradesh   India
S1-733749343                                             235, Binnamangala, 2Nd Fl, 13Th Cross Road, 2Ndï¿½ .St, Bangalore North, Bangalore, Karnataka                                           235, Binnamangala, 2Nd Fl, 13Th Cross Road, 2Nd� .St, Bangalore North, Bangalore, Karnataka   India
S1-414844948                                                                      Thane, Acres Waghbillï¿½Gb Road, 603-I Wing Ph 2 Bhoomi, Maharashtra                                                                    Thane, Acres Waghbill�Gb Road, 603-I Wing Ph 2 Bhoomi, Maharashtra   India
S1-397492974                                             M 2083 19Th Floor, Avenue Gc 11 Gaur City Greaterï¿½Noida, Gautam Buddha Nagar, Uttar Pradesh                                           M 2083 19Th Floor, Avenue Gc 11 Gaur City Greater�Noida, Gautam Buddha Nagar, Uttar Pradesh   India
S1-131406256                                                4/189 Bhatwaliya Nathï¿½Nag, 1-F-78 Raj Nagar Ii Palam, New Delhi, South West Delhi, Delhi                                              4/189 Bhatwaliya Nath�Nag, 1-F-78 Raj Nagar Ii Palam, New Delhi, South West Delhi, Delhi   India
S1-504400854                                     Office No-102, 1St Floor, Renuka Akruti, Surve No- 187/1/2, Wakadï¿½(Pcmc), Haveli, Pune, Maharashtra                                   Office No-102, 1St Floor, Renuka Akruti, Surve No- 187/1/2, Wakad�(Pcmc), Haveli, Pune, Maharashtra   India

In [ ]:
import re

def normalize_text(text):
    text = str(text).lower()

    # Treat replacement character as a separator
    text = text.replace("�", " ")

    # Replace punctuation/special characters with spaces
    text = re.sub(r"[^a-z0-9]+", " ", text)

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text)

    return text.strip()


train_source1["business_name_normalized"] = (
    train_source1["business_name_clean"]
    .apply(normalize_text)
)

train_source1["business_address_normalized"] = (
    train_source1["business_address_clean"]
    .apply(normalize_text)
)

In [ ]:
train_source1[
    ["business_name", "business_name_normalized",
     "business_address", "business_address_normalized"]
].head(10)

,business_name,business_name_normalized,business_address,business_address_normalized
0,Orelee's Barbershop,orelee s barbershop,"1795 Westchester Drive, High Point, NC",1795 westchester drive high point nc
1,Prime Money,prime money,"17560 Ellis Road, Tahlequah, OK",17560 ellis road tahlequah ok
2,B+ Retail Inc,b retail inc,"1712 Montebello Avenue, Phoenix, AZ",1712 montebello avenue phoenix az
3,Christ Chapel,christ chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",2100 cameron drive unit apartment g dundalk md
4,Prabhav Business Center,prabhav business center,"797, Lake Town Block A, Kolkata, Howrah, West ...",797 lake town block a kolkata howrah west bengal
5,Custom Wealth Services LLC,custom wealth services llc,"OH, Columbus, 5559 Orville Avenue",oh columbus 5559 orville avenue
6,Consulting Nyasa Nursing Private Limited,consulting nyasa nursing private limited,"2505, Tower 1, Oakwood, Runwal Greens, Mulund ...",2505 tower 1 oakwood runwal greens mulund gore...
7,Nexus Anchor Rain,nexus anchor rain,"1111 Church Street, Unit 2007, Nashville, TN",1111 church street unit 2007 nashville tn
8,Moore Bitwise Inc,moore bitwise inc,"337 Oakland Avenue, Michigan City, IN",337 oakland avenue michigan city in
9,Dermatology Green Medicine,dermatology green medicine,"294 Meadowcreek Drive, Unit Unit 2, Village Of...",294 meadowcreek drive unit unit 2 village of p...

In [ ]:
print("Empty normalized names:",
      (train_source1["business_name_normalized"] == "").sum())

print("Empty normalized addresses:",
      (train_source1["business_address_normalized"] == "").sum())

print("Missing normalized names:",
      train_source1["business_name_normalized"].isna().sum())

print("Missing normalized addresses:",
      train_source1["business_address_normalized"].isna().sum())

Empty normalized names: 0
Empty normalized addresses: 0
Missing normalized names: 0
Missing normalized addresses: 0

In [ ]:
train_source2 = pd.read_csv(
    base_path + "/train/train_source2.tsv",
    sep="\t"
)

print("Shape:", train_source2.shape)
print("\nColumns:")
print(train_source2.columns.tolist())

print("\nFirst 5 rows:")
display(train_source2.head())

print("\nMissing values:")
print(train_source2.isnull().sum())

Shape: (5034616, 4)

Columns:
['entity_id', 'business_name', 'business_address', 'country']

First 5 rows:

,entity_id,business_name,business_address,country
0,S2-166376419,राम मार्केटिंग प्राइवेट लिमिटेड,"KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi",India
1,S2-764573417,-- Holloway Peak Inc Seafood,"105 ELM ST, MORGANTON, NC",US
2,S2-639257739,आदित्य प्रॉपर्टीज एलएलपी,"G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh",India
3,S2-163963287,Summit Inc,"GREENSBORO, NC, 19 1/2 STARDUST TRAIL",US
4,S2-49942811,Delta Tetlecommunication Inc,"914 PIERPONT AVE, CLEVELAND, OH",US

Missing values:
entity_id                0
business_name            2
business_address    168967
country                  0
dtype: int64

In [ ]:
missing_names = train_source2[
    train_source2["business_name"].isna()
]

print(missing_names.to_string(index=False))

   entity_id business_name                    business_address country
S2-982925237           NaN 11 OX YOKE CIRCLE, EAST HAMPTON, CT      US
S2-599473918           NaN        BROOKHAVEN, 7 LILAC LANE, NY      US

In [ ]:
missing_addresses = train_source2[
    train_source2["business_address"].isna()
]

print(missing_addresses.head(10).to_string(index=False))

   entity_id                       business_name business_address country
S2-187379771       Guerra And Krueger Table, LLC              NaN      US
S2-751730544                 L E Pierce Cal [PC]              NaN      US
S2-162849450           Preferred Bay Montage Inc              NaN      US
S2-616836723             DELONG STRATEGIC  READY              NaN      US
 S2-39617527     Desert Vanguard ([Maintenance])              NaN      US
S2-582984116                    Wildlife Sóciety              NaN      US
S2-762023797                 Orellana Kensington              NaN      US
S2-682660453                      rathi holdings              NaN   India
S2-752363850                          Berry Saul              NaN      US
 S2-14102665 Thrasher, Wanner 5tenson LLC Center              NaN      US

In [ ]:
print("Duplicate entity_id:",
      train_source2["entity_id"].duplicated().sum())

print("Duplicate complete rows:",
      train_source2.duplicated().sum())

print("Duplicate business names:",
      train_source2["business_name"].duplicated().sum())

print("Duplicate business addresses:",
      train_source2["business_address"].duplicated().sum())

Duplicate entity_id: 0
Duplicate complete rows: 0
Duplicate business names: 632607
Duplicate business addresses: 697354

In [ ]:
print("Number of unique countries:",
      train_source2["country"].nunique())

print("\nCountry distribution:")
print(train_source2["country"].value_counts())

print("\nUnique country values:")
print(train_source2["country"].unique())

Number of unique countries: 2

Country distribution:
country
US       3016817
India    2017799
Name: count, dtype: int64

Unique country values:
['India' 'US']

In [ ]:
def has_whitespace_issue(text):
    if pd.isna(text):
        return False

    text = str(text)

    if text != text.strip():
        return True

    if re.search(r"\s{2,}", text):
        return True

    return False


name_whitespace = train_source2["business_name"].apply(has_whitespace_issue)
address_whitespace = train_source2["business_address"].apply(has_whitespace_issue)

print("Business names with whitespace issues:",
      name_whitespace.sum())

print("Business addresses with whitespace issues:",
      address_whitespace.sum())

Business names with whitespace issues: 554392
Business addresses with whitespace issues: 107574

In [ ]:
def has_control_char(text):
    if pd.isna(text):
        return False

    return bool(re.search(r"[\x00-\x1F\x7F]", str(text)))


name_control = train_source2["business_name"].apply(has_control_char)
address_control = train_source2["business_address"].apply(has_control_char)

print("Business names with control characters:",
      name_control.sum())

print("Business addresses with control characters:",
      address_control.sum())

Business names with control characters: 3
Business addresses with control characters: 119

In [ ]:
from collections import Counter

def get_control_chars(series):
    counter = Counter()

    for value in series.dropna():
        for char in str(value):
            if ord(char) < 32 or ord(char) == 127:
                counter[char] += 1

    return counter


name_control_chars = get_control_chars(train_source2["business_name"])
address_control_chars = get_control_chars(train_source2["business_address"])

print("Control characters in business names:")
for char, count in name_control_chars.items():
    print(repr(char), "->", count)

print("\nControl characters in business addresses:")
for char, count in address_control_chars.items():
    print(repr(char), "->", count)

Control characters in business names:
'\x1a' -> 3

Control characters in business addresses:
'\x1a' -> 147
'\x7f' -> 1

In [ ]:
def has_non_ascii(text):
    if pd.isna(text):
        return False

    return any(ord(char) > 127 for char in str(text))


name_non_ascii = train_source2["business_name"].apply(has_non_ascii)
address_non_ascii = train_source2["business_address"].apply(has_non_ascii)

print("Business names with non-ASCII characters:",
      name_non_ascii.sum())

print("Business addresses with non-ASCII characters:",
      address_non_ascii.sum())

Business names with non-ASCII characters: 764608
Business addresses with non-ASCII characters: 478453

In [ ]:
from collections import Counter

def get_non_ascii_chars(series):
    counter = Counter()

    for value in series.dropna():
        for char in str(value):
            if ord(char) > 127:
                counter[char] += 1

    return counter


name_non_ascii_chars = get_non_ascii_chars(
    train_source2["business_name"]
)

address_non_ascii_chars = get_non_ascii_chars(
    train_source2["business_address"]
)

print("Top non-ASCII characters in business names:")
for char, count in name_non_ascii_chars.most_common(30):
    print(repr(char), "->", count, f"U+{ord(char):04X}")

print("\nTop non-ASCII characters in business addresses:")
for char, count in address_non_ascii_chars.most_common(30):
    print(repr(char), "->", count, f"U+{ord(char):04X}")

Top non-ASCII characters in business names:
'्' -> 717972 U+094D
'ट' -> 608455 U+091F
'ि' -> 584183 U+093F
'े' -> 561088 U+0947
'र' -> 505620 U+0930
'ल' -> 414835 U+0932
'ा' -> 338443 U+093E
'स' -> 312754 U+0938
'प' -> 295013 U+092A
'म' -> 285977 U+092E
'ड' -> 284842 U+0921
'్' -> 256212 U+0C4D
'इ' -> 255030 U+0907
'್' -> 243924 U+0CCD
'व' -> 242718 U+0935
'்' -> 205368 U+0BCD
'ं' -> 172632 U+0902
'क' -> 168901 U+0915
'न' -> 153597 U+0928
'്' -> 142777 U+0D4D
'ட' -> 129032 U+0B9F
'ज' -> 119425 U+091C
'ி' -> 117630 U+0BBF
'ी' -> 114313 U+0940
'य' -> 102407 U+092F
'ట' -> 99677 U+0C1F
'્' -> 98872 U+0ACD
'ಿ' -> 95439 U+0CBF
'ಟ' -> 94171 U+0C9F
'ి' -> 89981 U+0C3F

Top non-ASCII characters in business addresses:
'्' -> 405562 U+094D
'र' -> 358544 U+0930
'ा' -> 301833 U+093E
'ह' -> 139364 U+0939
'ल' -> 133832 U+0932
'द' -> 120297 U+0926
'म' -> 119466 U+092E
'ष' -> 107011 U+0937
'ट' -> 107011 U+091F
'ि' -> 99269 U+093F
'त' -> 81852 U+0924
'ಕ' -> 77120 U+0C95
'ी' -> 66916 U+0940
'্' -> 63540 U+09CD
'प' -> 53381 U+092A
'े' -> 53381 U+0947
'श' -> 53381 U+0936
'उ' -> 40926 U+0909
'ರ' -> 38560 U+0CB0
'್' -> 38560 U+0CCD
'ನ' -> 38560 U+0CA8
'ಾ' -> 38560 U+0CBE
'ಟ' -> 38560 U+0C9F
'த' -> 34777 U+0BA4
'ம' -> 34777 U+0BAE
'ி' -> 34777 U+0BBF
'ழ' -> 34777 U+0BB4
'்' -> 34777 U+0BCD
'ந' -> 34777 U+0BA8
'ா' -> 34777 U+0BBE

In [ ]:
suspicious_patterns = [
    "â",
    "Â",
    "ï¿",
    "â",
    "Â"
]

for pattern in suspicious_patterns:
    name_count = train_source2["business_name"].fillna("").str.contains(
        pattern, regex=False
    ).sum()

    address_count = train_source2["business_address"].fillna("").str.contains(
        pattern, regex=False
    ).sum()

    print(
        repr(pattern),
        "-> names:", name_count,
        "| addresses:", address_count
    )

'â\x80' -> names: 0 | addresses: 0
'Â\x80' -> names: 0 | addresses: 1115
'ï¿' -> names: 0 | addresses: 0
'â' -> names: 0 | addresses: 0
'Â' -> names: 0 | addresses: 1118

In [ ]:
mojibake_addresses = train_source2[
    train_source2["business_address"].fillna("").str.contains(
        "Â", regex=False
    )
][
    ["entity_id", "business_address", "country"]
]

print(mojibake_addresses.head(20).to_string(index=False))

   entity_id                                                                                                                 business_address country
S2-891240803                                                                 A/195., PEOPLEÂS CO-OPERATIVE COLONY, KANKARBAGH, PATNA, Bihar   India
S2-339142042                                                   CSN 326/A, B-1 ÂO4 TAKSHSHILA, NEW SHAHUPURI, KARVEER, KOLHAPUR, Maharashtra   India
S2-289995403                                        NO 041 C/O YAWAR MAZHAR, MOHALLA Â DHARAMPUR NEW COLONY, WARD NO. 03, SAMASTIPUR, Bihar   India
S2-219105751 B-1, BLDG NOÂ1, WING-A, NEW INDIA CHAMBERS, VLG MULGAON, MIDC ROAD, BHD ONIDA HOUSE, AND, HERI EAST, MUMBAI, NULL, Maharashtra   India
S2-735939828           Tamil Nadu, MODULE NO.1205, 12TH FLOOR, TICEL BIOPARK LIMITED PHASE ÂII, NO.5, CSIR CAMPUS ROAD, TAR, AMANI, CHENNAI   India
S2-504129074                                 MAFATLAL CENTRE, 11TH FLOOR, NARIMAN POINT, MUMBAI Â 400 021, MUMBAI CITY, MUMBAI, Maharashtra   India
S2-926069490                                                                           OFFICE NO.D Â 414, NAVI MUMBAI, KARANJA, Maharashtra   India
 S2-90268325                   Gujarat, #56 C/O MARUTI TRADERS, GIDC 2, PLOT NO 60, ARAMBHDA VILL Â ARAMBHADA, TAL Â OKHAMANDAL, ARAMBHDA   India
S2-186253871          H.NO. 7-121-31, R R VENKATAPURAM, SAI NAGAR LAYOUT GOPALAPATNAM, LAND MARK Â LG POLYMERS, VISAKHAPATNAM, ఆంధ్రప్రదేశ్   India
S2-713596486                                 FLAT NO. Â 307, MARVEL HOMES, B.R.T.S MAIN ROAD OPP. KRISHNA PETROL PUMP, PUNA, SURAT, Gujarat   India
S2-275681823     NO. 27/29, CHIKKAKAMMANA HALLI, NEAR ST FRANCIS XAVIERÂS CHURCH, BANNERGHATTA ROAD, GOTT, IGERE POST, BANGALORE, Karnataka   India
S2-836799939                                  FLAT NO. Â 304, MARVEL HOMES, B.R.T.S MAIN ROAD OPP. KRISHNA PETROL PUMP, PUNA, SURAT, ગુજરાત   India
S2-624202156                                  Telangana, NO. 6-3-1090/B/4, ÂTHE GRANDÂ, 3RD FLOOR, RAJ BHAVAN ROAD, SOMAJIGUDA, HYDERABAD   India
S2-512091844                                            NO. 91 UNIT NO. 518, 5TH FLOOR DLF TOWER ÂB, JASOLA DISTRICT CENTRE, JASOLA, दिल्ली   India
S2-505511018                                                   CSN 326/A, B-1 ÂO4 TAKSHSHILA, NEW SHAHUPURI, KARVEER, KOLHAPUR, Maharashtra   India
S2-868063300                                                                          LV TNWER SA Â 94, D.D. PURAM, BAREILLY, Uttar Pradesh   India
S2-930916664                                                                                            ZOAHÂS CRESCENT, HYDERABAD, తెలంగాణ   India
S2-104047454                           Delhi, UNIT NO.30, FLOOR 3, WORLDMARK Â 3, ASSET Â 7, AEROCITY, N.H Â 8, NEW DELHI, , NEW DELHI   India
S2-979698147                  912, CTS NO 628, 629, 630, 631, 632, 633 WINGÂG LINK ROAD ANDHERI WEST VILLAGE OS, HIWARA, MUMBAI, महाराष्ट्र   India
S2-876633786                                                                                                    C Â ##52, JAIPUR, Rajasthan   India

In [ ]:
def repair_mojibake(text):
    if pd.isna(text):
        return text

    text = str(text)

    try:
        repaired = text.encode("latin1").decode("utf-8")
        return repaired
    except (UnicodeEncodeError, UnicodeDecodeError):
        return text

In [ ]:
test_addresses = train_source2["business_address"].head(100000)

repaired_test = test_addresses.apply(repair_mojibake)

changed = (test_addresses != repaired_test).sum()

print("Addresses changed in first 100,000 rows:", changed)

Addresses changed in first 100,000 rows: 3330

In [ ]:
def repair_mojibake(text):
    if pd.isna(text):
        return text

    text = str(text)

    try:
        repaired = text.encode("latin1").decode("utf-8")
        return repaired
    except (UnicodeEncodeError, UnicodeDecodeError):
        return text

In [ ]:
sample = train_source2[
    train_source2["business_address"].fillna("").str.contains("Â", regex=False)
]["business_address"].iloc[0]

print("ORIGINAL:")
print(repr(sample))

print("\nREPAIRED:")
print(repr(repair_mojibake(sample)))

ORIGINAL:
'A/195., PEOPLEÂ\x80\x99S CO-OPERATIVE COLONY, KANKARBAGH, PATNA, Bihar'

REPAIRED:
'A/195., PEOPLEÂ\x80\x99S CO-OPERATIVE COLONY, KANKARBAGH, PATNA, Bihar'

In [ ]:
def repair_mojibake(text):
    if pd.isna(text):
        return text

    text = str(text)

    try:
        repaired = text.encode("latin1").decode("utf-8")
        return repaired
    except (UnicodeEncodeError, UnicodeDecodeError):
        return text

sample = train_source2[
    train_source2["business_address"].fillna("").str.contains("Â", regex=False)
]["business_address"].iloc[0]

print("Original:")
print(repr(sample))

# Show the characters individually
print("\nCharacters:")
for char in sample:
    if ord(char) > 127 or ord(char) < 32:
        print(repr(char), hex(ord(char)))

Original:
'A/195., PEOPLEÂ\x80\x99S CO-OPERATIVE COLONY, KANKARBAGH, PATNA, Bihar'

Characters:
'Â' 0xc2
'\x80' 0x80
'\x99' 0x99

In [ ]:
def repair_mojibake(text):
    if pd.isna(text):
        return text

    text = str(text)

    replacements = {
        "Â\x80\x99": "’",
        "Â\x80\x98": "‘",
        "Â\x80\x93": "–",
        "Â\x80\x94": "—",
        "Â\x80\xa6": "…",
    }

    for bad, good in replacements.items():
        text = text.replace(bad, good)

    return text


sample = train_source2[
    train_source2["business_address"].fillna("").str.contains("Â", regex=False)
]["business_address"].iloc[0]

print("ORIGINAL:")
print(repr(sample))

repaired = repair_mojibake(sample)

print("\nREPAIRED:")
print(repr(repaired))

ORIGINAL:
'A/195., PEOPLEÂ\x80\x99S CO-OPERATIVE COLONY, KANKARBAGH, PATNA, Bihar'

REPAIRED:
'A/195., PEOPLE’S CO-OPERATIVE COLONY, KANKARBAGH, PATNA, Bihar'

In [ ]:
from collections import Counter

patterns = Counter()

for text in train_source2["business_address"].dropna():
    text = str(text)

    for i in range(len(text) - 2):
        chunk = text[i:i+3]

        if chunk.startswith("Â"):
            patterns[chunk] += 1

print("Mojibake patterns found:")
for pattern, count in patterns.most_common():
    print(repr(pattern), "->", count)

Mojibake patterns found:
'Â\x80\x93' -> 951
'Â\x80\x99' -> 266
'Â\x80\x98' -> 110
'Â\x80\x90' -> 32
'Â/8' -> 2
'Â\x82¬' -> 1

In [ ]:
for pattern in ["Â/8", "Â\x82¬"]:
    print("\n" + "="*60)
    print("PATTERN:", repr(pattern))

    rows = train_source2[
        train_source2["business_address"].fillna("").str.contains(
            pattern, regex=False
        )
    ]["business_address"]

    for value in rows.head(10):
        print(repr(value))

============================================================
PATTERN: 'Â/8'
'73Â/8\x80\x93A, BRAJ VIHAR, INDORE, Madhya Pradesh'
'73Â/8\x80\x93A, BRAJ VIHAR, INDORE, मध्य प्रदेश'

============================================================
PATTERN: 'Â\x82¬'
'NERUL AAKASH GANGA CHS, BLOCK #D, FLAT NO. 601, SECTOR 23, PLOT B71, SEAWOOD, NERUL Â\x82¬, NAVI MUMBAI, Maharashtra'

In [ ]:
def repair_mojibake(text):
    if pd.isna(text):
        return text

    text = str(text)

    replacements = {
        "Â\x80\x93": "–",
        "Â\x80\x99": "’",
        "Â\x80\x98": "‘",
        "Â\x80\x90": "‐"
    }

    for bad, good in replacements.items():
        text = text.replace(bad, good)

    return text

In [ ]:
test_addresses = train_source2["business_address"].head(100000)

repaired_test = test_addresses.apply(repair_mojibake)

changed = (
    test_addresses.notna() &
    repaired_test.notna() &
    (test_addresses != repaired_test)
).sum()

print("Changed addresses:", changed)

Changed addresses: 22

In [ ]:
comparison = pd.DataFrame({
    "original": test_addresses,
    "repaired": repaired_test
})

comparison = comparison[
    comparison["original"].notna() &
    (comparison["original"] != comparison["repaired"])
]

print(comparison.head(20).to_string(index=False))

                                                                                                                        original                                                                                                                       repaired
                                                                A/195., PEOPLEÂS CO-OPERATIVE COLONY, KANKARBAGH, PATNA, Bihar                                                                 A/195., PEOPLE’S CO-OPERATIVE COLONY, KANKARBAGH, PATNA, Bihar
                                                  CSN 326/A, B-1 ÂO4 TAKSHSHILA, NEW SHAHUPURI, KARVEER, KOLHAPUR, Maharashtra                                                   CSN 326/A, B-1 –O4 TAKSHSHILA, NEW SHAHUPURI, KARVEER, KOLHAPUR, Maharashtra
                                       NO 041 C/O YAWAR MAZHAR, MOHALLA Â DHARAMPUR NEW COLONY, WARD NO. 03, SAMASTIPUR, Bihar                                        NO 041 C/O YAWAR MAZHAR, MOHALLA – DHARAMPUR NEW COLONY, WARD NO. 03, SAMASTIPUR, Bihar
B-1, BLDG NOÂ1, WING-A, NEW INDIA CHAMBERS, VLG MULGAON, MIDC ROAD, BHD ONIDA HOUSE, AND, HERI EAST, MUMBAI, NULL, Maharashtra B-1, BLDG NO–1, WING-A, NEW INDIA CHAMBERS, VLG MULGAON, MIDC ROAD, BHD ONIDA HOUSE, AND, HERI EAST, MUMBAI, NULL, Maharashtra
          Tamil Nadu, MODULE NO.1205, 12TH FLOOR, TICEL BIOPARK LIMITED PHASE ÂII, NO.5, CSIR CAMPUS ROAD, TAR, AMANI, CHENNAI           Tamil Nadu, MODULE NO.1205, 12TH FLOOR, TICEL BIOPARK LIMITED PHASE –II, NO.5, CSIR CAMPUS ROAD, TAR, AMANI, CHENNAI
                                MAFATLAL CENTRE, 11TH FLOOR, NARIMAN POINT, MUMBAI Â 400 021, MUMBAI CITY, MUMBAI, Maharashtra                                 MAFATLAL CENTRE, 11TH FLOOR, NARIMAN POINT, MUMBAI – 400 021, MUMBAI CITY, MUMBAI, Maharashtra
                                                                          OFFICE NO.D Â 414, NAVI MUMBAI, KARANJA, Maharashtra                                                                           OFFICE NO.D – 414, NAVI MUMBAI, KARANJA, Maharashtra
                  Gujarat, #56 C/O MARUTI TRADERS, GIDC 2, PLOT NO 60, ARAMBHDA VILL Â ARAMBHADA, TAL Â OKHAMANDAL, ARAMBHDA                     Gujarat, #56 C/O MARUTI TRADERS, GIDC 2, PLOT NO 60, ARAMBHDA VILL – ARAMBHADA, TAL – OKHAMANDAL, ARAMBHDA
         H.NO. 7-121-31, R R VENKATAPURAM, SAI NAGAR LAYOUT GOPALAPATNAM, LAND MARK Â LG POLYMERS, VISAKHAPATNAM, ఆంధ్రప్రదేశ్          H.NO. 7-121-31, R R VENKATAPURAM, SAI NAGAR LAYOUT GOPALAPATNAM, LAND MARK – LG POLYMERS, VISAKHAPATNAM, ఆంధ్రప్రదేశ్
                                FLAT NO. Â 307, MARVEL HOMES, B.R.T.S MAIN ROAD OPP. KRISHNA PETROL PUMP, PUNA, SURAT, Gujarat                                 FLAT NO. – 307, MARVEL HOMES, B.R.T.S MAIN ROAD OPP. KRISHNA PETROL PUMP, PUNA, SURAT, Gujarat
    NO. 27/29, CHIKKAKAMMANA HALLI, NEAR ST FRANCIS XAVIERÂS CHURCH, BANNERGHATTA ROAD, GOTT, IGERE POST, BANGALORE, Karnataka     NO. 27/29, CHIKKAKAMMANA HALLI, NEAR ST FRANCIS XAVIER’S CHURCH, BANNERGHATTA ROAD, GOTT, IGERE POST, BANGALORE, Karnataka
                                 FLAT NO. Â 304, MARVEL HOMES, B.R.T.S MAIN ROAD OPP. KRISHNA PETROL PUMP, PUNA, SURAT, ગુજરાત                                  FLAT NO. – 304, MARVEL HOMES, B.R.T.S MAIN ROAD OPP. KRISHNA PETROL PUMP, PUNA, SURAT, ગુજરાત
                                 Telangana, NO. 6-3-1090/B/4, ÂTHE GRANDÂ, 3RD FLOOR, RAJ BHAVAN ROAD, SOMAJIGUDA, HYDERABAD                                    Telangana, NO. 6-3-1090/B/4, ‘THE GRAND’, 3RD FLOOR, RAJ BHAVAN ROAD, SOMAJIGUDA, HYDERABAD
                                           NO. 91 UNIT NO. 518, 5TH FLOOR DLF TOWER ÂB, JASOLA DISTRICT CENTRE, JASOLA, दिल्ली                                            NO. 91 UNIT NO. 518, 5TH FLOOR DLF TOWER –B, JASOLA DISTRICT CENTRE, JASOLA, दिल्ली
                                                  CSN 326/A, B-1 ÂO4 TAKSHSHILA, NEW SHAHUPURI, KARVEER, KOLHAPUR, Maharashtra                                                   CSN 326/A, B-1 –O4 TAKSHSHILA, NEW SHAHUPURI, KARVEER, KOLHAPUR, Maharashtra
                                                                         LV TNWER SA Â 94, D.D. PURAM, BAREILLY, Uttar Pradesh                                                                          LV TNWER SA – 94, D.D. PURAM, BAREILLY, Uttar Pradesh
                                                                                           ZOAHÂS CRESCENT, HYDERABAD, తెలంగాణ                                                                                            ZOAH’S CRESCENT, HYDERABAD, తెలంగాణ
                          Delhi, UNIT NO.30, FLOOR 3, WORLDMARK Â 3, ASSET Â 7, AEROCITY, N.H Â 8, NEW DELHI, , NEW DELHI                               Delhi, UNIT NO.30, FLOOR 3, WORLDMARK – 3, ASSET – 7, AEROCITY, N.H – 8, NEW DELHI, , NEW DELHI
                 912, CTS NO 628, 629, 630, 631, 632, 633 WINGÂG LINK ROAD ANDHERI WEST VILLAGE OS, HIWARA, MUMBAI, महाराष्ट्र                  912, CTS NO 628, 629, 630, 631, 632, 633 WING’G LINK ROAD ANDHERI WEST VILLAGE OS, HIWARA, MUMBAI, महाराष्ट्र
                                                                                                   C Â ##52, JAIPUR, Rajasthan                                                                                                    C – ##52, JAIPUR, Rajasthan

In [ ]:
# Repair encoding corruption
train_source2["business_name_clean"] = (
    train_source2["business_name"].apply(repair_mojibake)
)

train_source2["business_address_clean"] = (
    train_source2["business_address"].apply(repair_mojibake)
)

print("Mojibake repair completed.")

Mojibake repair completed.

In [ ]:
def clean_control_chars(text):
    if pd.isna(text):
        return text

    text = str(text)

    # Replace control characters with a space
    text = re.sub(r"[\x00-\x1F\x7F]", " ", text)

    # Remove repeated whitespace
    text = re.sub(r"\s+", " ", text)

    return text.strip()

In [ ]:
train_source2["business_name_clean"] = (
    train_source2["business_name_clean"].apply(clean_control_chars)
)

train_source2["business_address_clean"] = (
    train_source2["business_address_clean"].apply(clean_control_chars)
)

In [ ]:
def has_control_char(text):
    if pd.isna(text):
        return False

    return bool(re.search(r"[\x00-\x1F\x7F]", str(text)))


name_controls = train_source2["business_name_clean"].apply(has_control_char).sum()
address_controls = train_source2["business_address_clean"].apply(has_control_char).sum()

print("Control characters in names:", name_controls)
print("Control characters in addresses:", address_controls)

Control characters in names: 0
Control characters in addresses: 0

In [ ]:
import unicodedata
import re

def normalize_unicode_text(text):
    if pd.isna(text):
        return text

    text = str(text).lower()

    # Normalize Unicode representation
    text = unicodedata.normalize("NFKC", text)

    # Replace punctuation/symbols with spaces,
    # while preserving letters and numbers from all languages
    result = []

    for char in text:
        category = unicodedata.category(char)

        if category[0] in ("L", "N"):
            # Letter or number
            result.append(char)
        else:
            # Punctuation, symbols, marks, etc.
            result.append(" ")

    text = "".join(result)

    # Remove extra whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [ ]:
train_source2["business_name_normalized"] = (
    train_source2["business_name_clean"]
    .apply(normalize_unicode_text)
)

train_source2["business_address_normalized"] = (
    train_source2["business_address_clean"]
    .apply(normalize_unicode_text)
)

In [ ]:
print(
    train_source2[
        [
            "business_name",
            "business_name_clean",
            "business_name_normalized",
            "business_address",
            "business_address_clean",
            "business_address_normalized"
        ]
    ].head(20).to_string(index=False)
)

                                                           business_name                                                      business_name_clean                                               business_name_normalized                                                                                          business_address                                                                                    business_address_clean                                                                     business_address_normalized
                                         राम मार्केटिंग प्राइवेट लिमिटेड                                          राम मार्केटिंग प्राइवेट लिमिटेड                                         र म म र क ट ग प र इव ट ल म ट ड                                                              KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi                                                              KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi                                                         kh no 570 13 new delhi west delhi delhi
                                            -- Holloway Peak Inc Seafood                                             -- Holloway Peak Inc Seafood                                              holloway peak inc seafood                                                                                 105 ELM ST, MORGANTON, NC                                                                                 105 ELM ST, MORGANTON, NC                                                                         105 elm st morganton nc
                                                आदित्य प्रॉपर्टीज एलएलपी                                                 आदित्य प्रॉपर्टीज एलएलपी                                                आद त य प र पर ट ज एलएलप                                                          G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh                                                          G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh                                                   g 3 571 gulmohar colony bhopal madhya pradesh
                                                              Summit Inc                                                               Summit Inc                                                             summit inc                                                                     GREENSBORO, NC, 19 1/2 STARDUST TRAIL                                                                     GREENSBORO, NC, 19 1/2 STARDUST TRAIL                                                             greensboro nc 19 1 2 stardust trail
                                            Delta Tetlecommunication Inc                                             Delta Tetlecommunication Inc                                           delta tetlecommunication inc                                                                           914 PIERPONT AVE, CLEVELAND, OH                                                                           914 PIERPONT AVE, CLEVELAND, OH                                                                   914 pierpont ave cleveland oh
                                                          Lee and Lawson                                                           Lee and Lawson                                                         lee and lawson                                                                   1702 Pine Avenue, CITY OF MENOMONIE, WI                                                                   1702 Pine Avenue, CITY OF MENOMONIE, WI                                                           1702 pine avenue city of menomonie wi
SHIVSHAKTI VIDYALAYA VIDYALAYA OVERSEAS CORPORATION | www.shivshakti.com SHIVSHAKTI VIDYALAYA VIDYALAYA OVERSEAS CORPORATION | www.shivshakti.com shivshakti vidyalaya vidyalaya overseas corporation www shivshakti com                                                                H.NO 204 C ROAD HOSHIARPUR, PUNJAB, Punjab                                                                H.NO 204 C ROAD HOSHIARPUR, PUNJAB, Punjab                                                        h no 204 c road hoshiarpur punjab punjab
                                              Shree Infracon Private Ltd                                               Shree Infracon Private Ltd                                             shree infracon private ltd                                63/2275/7, ALHIND TOWER, FIRST FLOOR, JAFFERKHAN COLONY, KOZHIKODE, Kerala                                63/2275/7, ALHIND TOWER, FIRST FLOOR, JAFFERKHAN COLONY, KOZHIKODE, Kerala                           63 2275 7 alhind tower first floor jafferkhan colony kozhikode kerala
                                            Chavira Platinum Chimera LLC                                             Chavira Platinum Chimera LLC                                           chavira platinum chimera llc                                                                        282 SAXONY DRIVE, FTT MITCHELL, KY                                                                        282 SAXONY DRIVE, FTT MITCHELL, KY                                                                282 saxony drive ftt mitchell ky
                                FOUNDATION EXCEL AGENCY PRIVATE  LIMITED                                  FOUNDATION EXCEL AGENCY PRIVATE LIMITED                                foundation excel agency private limited                                                  HN 753 E-1, BHARAT NAGAR, 104/1/1 ERANDWANE, Maharashtra                                                  HN 753 E-1, BHARAT NAGAR, 104/1/1 ERANDWANE, Maharashtra                                           hn 753 e 1 bharat nagar 104 1 1 erandwane maharashtra
                                                        heassociates.com                                                         heassociates.com                                                       heassociates com                                                                          599 PEASE HILL ROAD, HORICON, NY                                                                          599 PEASE HILL ROAD, HORICON, NY                                                                  599 pease hill road horicon ny
                                        सन कंस्ट्रक्शंस प्राइवेट लिमिटेड                                         सन कंस्ट्रक्शंस प्राइवेट लिमिटेड                                       सन क स ट रक श स प र इव ट ल म ट ड 43 SUKH SAMRUDDHI, Maharashtra, PUNE REGION, PUNE, BUNGALOW NO. 5, S. NO. 5, VIDISHA SOCIETY, KARVE NAGAR 43 SUKH SAMRUDDHI, Maharashtra, PUNE REGION, PUNE, BUNGALOW NO. 5, S. NO. 5, VIDISHA SOCIETY, KARVE NAGAR 43 sukh samruddhi maharashtra pune region pune bungalow no 5 s no 5 vidisha society karve nagar
                              Global Developers Medicals Private Limited                               Global Developers Medicals Private Limited                             global developers medicals private limited             H.NO 008 GOVIND BUILDING OPP.HOTEL VRINDHAVAN AARAY ROAD GOREGAON (EAST), MUMBAI, Maharashtra             H.NO 008 GOVIND BUILDING OPP.HOTEL VRINDHAVAN AARAY ROAD GOREGAON (EAST), MUMBAI, Maharashtra       h no 008 govind building opp hotel vrindhavan aaray road goregaon east mumbai maharashtra
                                            ASSET BUILDING COALITION LLC                                             ASSET BUILDING COALITION LLC                                           asset building coalition llc                                                                        8219 17RD STREET, LAKE STEVENS, WA                                                                        8219 17RD STREET, LAKE STEVENS, WA                                                                8219 17rd street lake stevens wa
                                       Olszewski Holding Company LLC LLC                                        Olszewski Holding Company LLC LLC                                      olszewski holding company llc llc                                                                         218 SHOAL CREEK, WILLIAMSBURG, VA                                                                         218 SHOAL CREEK, WILLIAMSBURG, VA                                                                 218 shoal creek williamsburg va
                                                        CANDY'S-SERVICES                                                         CANDY'S-SERVICES                                                       candy s services                                                                       313 FOXBOROUGH DRIVE, BRUNSWICK, OH                                                                       313 FOXBOROUGH DRIVE, BRUNSWICK, OH                                                               313 foxborough drive brunswick oh
                                                 रियल मॉडर्न फूड लिमिटेड                                                  रियल मॉडर्न फूड लिमिटेड                                                र यल म डर न फ ड ल म ट ड                               SHP NO. G-4, PLOT NO. 19, SECTOR 42, NERUL, THANE, NAVI MUMBAI, Maharashtra                               SHP NO. G-4, PLOT NO. 19, SECTOR 42, NERUL, THANE, NAVI MUMBAI, Maharashtra                             shp no g 4 plot no 19 sector 42 nerul thane navi mumbai maharashtra
                                            Crestline Crestline Clean LP                                             Crestline Crestline Clean LP                                           crestline crestline clean lp                                                                              HIGHWAY 49, ASHLAND CITY, TN                                                                              HIGHWAY 49, ASHLAND CITY, TN                                                                      highway 49 ashland city tn
                                                                    Nion                                                                     Nion                                                                   nion                                                                     7100 BRIGHAM ROAD, HENRICO COUNTY, VA                                                                     7100 BRIGHAM ROAD, HENRICO COUNTY, VA                                                             7100 brigham road henrico county va
                                            Keystone Odyssey Odyssey LLC                                             Keystone Odyssey Odyssey LLC                                           keystone odyssey odyssey llc                                                                     1418 MEADOWBROOK DR, JOHNSON CITY, TN                                                                     1418 MEADOWBROOK DR, JOHNSON CITY, TN                                                             1418 meadowbrook dr johnson city tn

In [ ]:
def normalize_unicode_text(text):
    if pd.isna(text):
        return text

    text = str(text).lower()

    # Normalize Unicode representation
    text = unicodedata.normalize("NFKC", text)

    result = []

    for char in text:
        category = unicodedata.category(char)

        # Keep letters, numbers and combining marks
        if category[0] in ("L", "N", "M"):
            result.append(char)
        else:
            # Replace punctuation/symbols with space
            result.append(" ")

    text = "".join(result)

    # Remove repeated whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [ ]:
train_source2["business_name_normalized"] = (
    train_source2["business_name_clean"]
    .apply(normalize_unicode_text)
)

train_source2["business_address_normalized"] = (
    train_source2["business_address_clean"]
    .apply(normalize_unicode_text)
)

In [ ]:
print(
    train_source2[
        ["business_name", "business_name_normalized"]
    ].head(20).to_string(index=False)
)

                                                           business_name                                               business_name_normalized
                                         राम मार्केटिंग प्राइवेट लिमिटेड                                        राम मार्केटिंग प्राइवेट लिमिटेड
                                            -- Holloway Peak Inc Seafood                                              holloway peak inc seafood
                                                आदित्य प्रॉपर्टीज एलएलपी                                               आदित्य प्रॉपर्टीज एलएलपी
                                                              Summit Inc                                                             summit inc
                                            Delta Tetlecommunication Inc                                           delta tetlecommunication inc
                                                          Lee and Lawson                                                         lee and lawson
SHIVSHAKTI VIDYALAYA VIDYALAYA OVERSEAS CORPORATION | www.shivshakti.com shivshakti vidyalaya vidyalaya overseas corporation www shivshakti com
                                              Shree Infracon Private Ltd                                             shree infracon private ltd
                                            Chavira Platinum Chimera LLC                                           chavira platinum chimera llc
                                FOUNDATION EXCEL AGENCY PRIVATE  LIMITED                                foundation excel agency private limited
                                                        heassociates.com                                                       heassociates com
                                        सन कंस्ट्रक्शंस प्राइवेट लिमिटेड                                       सन कंस्ट्रक्शंस प्राइवेट लिमिटेड
                              Global Developers Medicals Private Limited                             global developers medicals private limited
                                            ASSET BUILDING COALITION LLC                                           asset building coalition llc
                                       Olszewski Holding Company LLC LLC                                      olszewski holding company llc llc
                                                        CANDY'S-SERVICES                                                       candy s services
                                                 रियल मॉडर्न फूड लिमिटेड                                                रियल मॉडर्न फूड लिमिटेड
                                            Crestline Crestline Clean LP                                           crestline crestline clean lp
                                                                    Nion                                                                   nion
                                            Keystone Odyssey Odyssey LLC                                           keystone odyssey odyssey llc

In [ ]:
print("Missing normalized names:",
      train_source2["business_name_normalized"].isna().sum())

print("Missing normalized addresses:",
      train_source2["business_address_normalized"].isna().sum())

print("Empty normalized names:",
      (train_source2["business_name_normalized"].fillna("") == "").sum())

print("Empty normalized addresses:",
      (train_source2["business_address_normalized"].fillna("") == "").sum())

Missing normalized names: 2
Missing normalized addresses: 168967
Empty normalized names: 2
Empty normalized addresses: 168967

In [ ]:
print(
    train_source2[
        train_source2["business_name"].fillna("").str.contains(
            r"[\u0900-\u097F]", regex=True
        )
    ][
        ["business_name", "business_name_normalized"]
    ].head(10).to_string(index=False)
)

                        business_name              business_name_normalized
      राम मार्केटिंग प्राइवेट लिमिटेड       राम मार्केटिंग प्राइवेट लिमिटेड
             आदित्य प्रॉपर्टीज एलएलपी              आदित्य प्रॉपर्टीज एलएलपी
     सन कंस्ट्रक्शंस प्राइवेट लिमिटेड      सन कंस्ट्रक्शंस प्राइवेट लिमिटेड
              रियल मॉडर्न फूड लिमिटेड               रियल मॉडर्न फूड लिमिटेड
अल्फा अल टेक्नोलॉजीज प्राइवेट लिमिटेड अल्फा अल टेक्नोलॉजीज प्राइवेट लिमिटेड
        ग्लोबल इन्वेस्टमेंट प्रा. लि.           ग्लोबल इन्वेस्टमेंट प्रा लि
          फर्स्ट फूड प्राइवेट लिमिटेड           फर्स्ट फूड प्राइवेट लिमिटेड
                 होटल वेंचर्स लिमिटेड                  होटल वेंचर्स लिमिटेड
         जैन वेंचर्स प्राइवेट लिमिटेड          जैन वेंचर्स प्राइवेट लिमिटेड
    लक्ष्मी डेवलपर्स प्राइवेट लिमिटेड     लक्ष्मी डेवलपर्स प्राइवेट लिमिटेड

In [ ]:
print("Missing normalized names:",
      train_source2["business_name_normalized"].isna().sum())

print("Missing normalized addresses:",
      train_source2["business_address_normalized"].isna().sum())

print("Empty normalized names:",
      (train_source2["business_name_normalized"].fillna("") == "").sum())

print("Empty normalized addresses:",
      (train_source2["business_address_normalized"].fillna("") == "").sum())

Missing normalized names: 2
Missing normalized addresses: 168967
Empty normalized names: 2
Empty normalized addresses: 168967

In [ ]:
train_source3 = pd.read_csv(
    base_path + "/train/train_source3.tsv",
    sep="\t"
)

print("Shape:", train_source3.shape)
print("Columns:", train_source3.columns.tolist())

print("\nFirst 5 rows:")
print(train_source3.head().to_string(index=False))

Shape: (5285603, 4)
Columns: ['entity_id', 'business_name', 'business_address', 'country']

First 5 rows:
   entity_id                               business_name                                                                            business_address country
S3-202863386                          wilfordhancock.com                                                                 Mack Rd, Haltom City, Texas      US
S3-859268022 International South Consultants Private Ltd                                                                                         NaN   India
 S3-22467283                 LLC Moncada Léarning Center                                                             5780 Fawn Ct, Fort Worth, Texas      US
S3-671162755                              Moyna's Coffee                                                1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio      US
S3-960981775                Pvt. EFS Print Ventures Ltd. Door No 183, 41St Cross, 22Nd Main 9Th Block Jayanagar, Bengaluru Urban, Bangalore, ಕರ್ನಾಟಕ   India

In [ ]:
print("Missing values:")
print(train_source3.isnull().sum())

Missing values:
entity_id                0
business_name           13
business_address    175916
country                  0
dtype: int64

In [ ]:
print("Duplicate entity_id:", train_source3["entity_id"].duplicated().sum())

print("Duplicate complete rows:", train_source3.duplicated().sum())

print("Duplicate business names:", train_source3["business_name"].duplicated().sum())

print("Duplicate business addresses:", train_source3["business_address"].duplicated().sum())

Duplicate entity_id: 0
Duplicate complete rows: 0
Duplicate business names: 633994
Duplicate business addresses: 652838

In [ ]:
print("Unique countries:")
print(train_source3["country"].unique())

print("\nNumber of unique countries:")
print(train_source3["country"].nunique())

print("\nCountry counts:")
print(train_source3["country"].value_counts())

Unique countries:
['US' 'India']

Number of unique countries:
2

Country counts:
country
US       3170056
India    2115547
Name: count, dtype: int64

In [ ]:
def has_whitespace_issue(text):
    if pd.isna(text):
        return False

    text = str(text)

    if text != text.strip():
        return True

    if re.search(r"\s{2,}", text):
        return True

    return False


name_whitespace = train_source3["business_name"].apply(has_whitespace_issue).sum()
address_whitespace = train_source3["business_address"].apply(has_whitespace_issue).sum()

print("Business names with whitespace issues:", name_whitespace)
print("Business addresses with whitespace issues:", address_whitespace)

Business names with whitespace issues: 575616
Business addresses with whitespace issues: 4874

In [ ]:
def has_control_char(text):
    if pd.isna(text):
        return False

    return bool(re.search(r"[\x00-\x1F\x7F]", str(text)))


name_control = train_source3["business_name"].apply(has_control_char).sum()
address_control = train_source3["business_address"].apply(has_control_char).sum()

print("Business names with control chars:", name_control)
print("Business addresses with control chars:", address_control)

Business names with control chars: 1
Business addresses with control chars: 125

In [ ]:
from collections import Counter

name_controls = Counter()
address_controls = Counter()

for text in train_source3["business_name"].dropna():
    for char in str(text):
        if re.match(r"[\x00-\x1F\x7F]", char):
            name_controls[repr(char)] += 1

for text in train_source3["business_address"].dropna():
    for char in str(text):
        if re.match(r"[\x00-\x1F\x7F]", char):
            address_controls[repr(char)] += 1

print("Control characters in business names:")
print(name_controls)

print("\nControl characters in business addresses:")
print(address_controls)

Control characters in business names:
Counter({"'\\x1a'": 1})

Control characters in business addresses:
Counter({"'\\x1a'": 156, "'\\x7f'": 1})

In [ ]:
def has_non_ascii(text):
    if pd.isna(text):
        return False

    return any(ord(char) > 127 for char in str(text))


name_non_ascii = train_source3["business_name"].apply(has_non_ascii).sum()
address_non_ascii = train_source3["business_address"].apply(has_non_ascii).sum()

print("Business names with non-ASCII characters:", name_non_ascii)
print("Business addresses with non-ASCII characters:", address_non_ascii)

print("\nPercentages:")
print("Names:", round(name_non_ascii / len(train_source3) * 100, 2), "%")
print("Addresses:", round(address_non_ascii / len(train_source3) * 100, 2), "%")

Business names with non-ASCII characters: 606737
Business addresses with non-ASCII characters: 476588

Percentages:
Names: 11.48 %
Addresses: 9.02 %

In [ ]:
suspicious_patterns = [
    "â",
    "Â",
    "ï¿",
    "â",
    "Â"
]

for pattern in suspicious_patterns:
    name_count = train_source3["business_name"].fillna("").str.contains(
        pattern, regex=False
    ).sum()

    address_count = train_source3["business_address"].fillna("").str.contains(
        pattern, regex=False
    ).sum()

    print(f"Pattern {repr(pattern)}:")
    print("  Business names :", name_count)
    print("  Addresses      :", address_count)

Pattern 'â\x80':
  Business names : 0
  Addresses      : 253
Pattern 'Â\x80':
  Business names : 0
  Addresses      : 785
Pattern 'ï¿':
  Business names : 0
  Addresses      : 15
Pattern 'â':
  Business names : 0
  Addresses      : 255
Pattern 'Â':
  Business names : 0
  Addresses      : 785

In [ ]:
patterns = ["â", "Â", "ï¿"]

for pattern in patterns:
    print(f"\n--- Examples containing {repr(pattern)} ---")

    examples = train_source3[
        train_source3["business_address"]
        .fillna("")
        .str.contains(pattern, regex=False)
    ]["business_address"].head(10)

    for value in examples:
        print(repr(value))

--- Examples containing 'â\x80' ---
'Fourth Floor No.2651, 2 Nd Cross, 15 Th Main, Â\x80\x99eâ\x80\x99 Block, Sahakar Nagar, Bangalore, KA'
'House No. G-183, Ground Floor, Blockâ\x80\x93a, Metro Vihar Phase Â\x80\x93 1, Village & Post Office Holambi, Kalan, North West Delhi, North Delhi, DL'
'Cts No14985, Plot No. 140A Iiâ\x80\x99nd Floor, Sindhi Colony, Jalna Road, Aurangabad, महाराष्ट्र'
'Cts 628 A/5 J.m Road, Bhosale Shinde Arcade, Sâ\x80\x99nagar, Pune, MH'
'201, First Floor, Chanduâ\x80\x99s Central Survey No. 243/9A, Madhurawada Village, Visakhapatnam, Vishakhapatnam, ఆంధ్రప్రదేశ్'
'201, First Floor, Chanduâ\x80\x99s Central Survey No. 243/9A, Madhurawada Village, Visakhapatnam, Vishakhapatnam, AP'
'No 092 Above Bank Of India, Near Queen Mary Girlâ\x80\x99s School B.k. Kaul Nagar, Ram Nagar, Pushkar Road, Ajmer, RJ'
'Pune, Â\x80\x98parth Unnatiâ\x80\x99 Flat No. 204, MH, Pune, Sr. No. 133;134/1 Plot No. 1, Sairang Society'
'H-2344, Yashwant N. Court Rdtq. Paithan Dist Aâ\x80\x99bad Paithan, Aurangabad, MH'
'Â\x80\x98oâ\x80\x99 B3/410, Ahmedabad, GJ'

--- Examples containing 'Â\x80' ---
'Plot 416 Shop Â\x80\x93 484, Mumbai, Mumbai City, MH'
'Vayu Â\x80\x93 616, Sy.no 79, Ele Room Â\x80\x93 I, Near Hitech City, Madhapur, Hyderabad, Rangareddy, TG'
'Hn 301 A Â\x80\x93 204, Thaltej, <NULL>, GJ'
'Fourth Floor No.2651, 2 Nd Cross, 15 Th Main, Â\x80\x99eâ\x80\x99 Block, Sahakar Nagar, Bangalore, KA'
'House No. G-183, Ground Floor, Blockâ\x80\x93a, Metro Vihar Phase Â\x80\x93 1, Village & Post Office Holambi, Kalan, North West Delhi, North Delhi, DL'
'Swiss County, Flat No. Â\x80\x93 601, S. No. - 37, G-1, Near Pcmc School, Thergaon, Pune, Maharashtra'
'Property No. Â\x80\x93 B 4-8 A, Old No. Â\x80\x93 B -35 S/f Kh No. Â\x80\x93 829, Chhattarpur Extn., South Delhi, Delhi, DL'
'Mumbai Suburban, Malad West, Mumbai, Shop No 201 Bldg Â\x80\x93b Interface Heights Link Road, Mumbai City, MH'
'A Â\x80\x93 1, Seva Co Op Housing Society Ltd., New Link Road, Near Oshiwara, Jogeshwar, I (West), Mumbai, Mumbai City, MH'
'#81 Mafatlal Centre, 11Th Floor, Nariman Point, Mumbai Â\x80\x93 400 021, Mumbai City, Mumbai, MH'

--- Examples containing 'ï¿' ---
'H-450 Fourth Floor, Flat No 402 Hï¿½block, New Delhi, South Delhi, DL'
'M 2083 19Th Flor, Avenue Gc 11 Gaur City Greaterï¿½noida, Gautam Buddha Nagar, उत्तर प्रदेश'
'4/189 Bhatwaliya Nathï¿½nag, New Delhi, South West Delhi, DL'
'South West Delhi, Westendï¿½margï¿½laneï¿½2, Saidulajab, दिल्ली, New Delhi, Property No 55. Third Floor'
'603-I Wing Ph 2 Bhoomi, Acres Waghbillï¿½gb Road, Thane, MH'
'Bangalore North, Bangalore, Karnataka, Flat No 14284, Prestige Lakesideï¿½Habitat'
'8/6 Chhoti Gwal Tloi, Indore Poleï¿½noï¿½ims/17/6, Indore, MP'
'Lucknow, Coronation Anand Tower, UP, Lucknow, First Floor 116-117, Vibhuti Khand, Gomtinagar, Lucknow, Oppï¿½sushmaï¿½hospital'
'242, Bangalore North, Bangalore, Binnamangala, 2Nd Fl, 13Th Cross Road, 2Ndï¿½ .St, KA'
'Property No 62 Third Floor, Westendï¿½margï¿½laneï¿½2, Saidulajab, New Delhi, South West Delhi, DL'

In [ ]:
repair_patterns = {
    "Â\\x80\\x93": "–",
    "Â\\x80\\x99": "’",
    "Â\\x80\\x98": "‘",
    "Â\\x80\\x90": "‐",
    "â\\x80\\x93": "–",
    "â\\x80\\x99": "’",
    "â\\x80\\x98": "‘",
    "â\\x80\\x90": "‐"
}

for bad, good in repair_patterns.items():
    count_name = train_source3["business_name"].fillna("").str.count(bad).sum()
    count_address = train_source3["business_address"].fillna("").str.count(bad).sum()

    print(
        repr(bad),
        "→", repr(good),
        "| Names:", int(count_name),
        "| Addresses:", int(count_address)
    )

'Â\\x80\\x93' → '–' | Names: 0 | Addresses: 786
'Â\\x80\\x99' → '’' | Names: 0 | Addresses: 8
'Â\\x80\\x98' → '‘' | Names: 0 | Addresses: 87
'Â\\x80\\x90' → '‐' | Names: 0 | Addresses: 2
'â\\x80\\x93' → '–' | Names: 0 | Addresses: 55
'â\\x80\\x99' → '’' | Names: 0 | Addresses: 194
'â\\x80\\x98' → '‘' | Names: 0 | Addresses: 2
'â\\x80\\x90' → '‐' | Names: 0 | Addresses: 20

In [ ]:
def repair_mojibake(text):
    if pd.isna(text):
        return text

    text = str(text)

    replacements = {
        "Â\x80\x93": "–",
        "Â\x80\x99": "’",
        "Â\x80\x98": "‘",
        "Â\x80\x90": "‐",

        "â\x80\x93": "–",
        "â\x80\x99": "’",
        "â\x80\x98": "‘",
        "â\x80\x90": "‐"
    }

    for bad, good in replacements.items():
        text = text.replace(bad, good)

    return text

In [ ]:
test_rows = train_source3[
    train_source3["business_address"]
    .fillna("")
    .str.contains("Â\x80|â\x80", regex=True)
].head(10)

for value in test_rows["business_address"]:
    print("BEFORE :", repr(value))
    print("AFTER  :", repr(repair_mojibake(value)))
    print()

BEFORE : 'Plot 416 Shop Â\x80\x93 484, Mumbai, Mumbai City, MH'
AFTER  : 'Plot 416 Shop – 484, Mumbai, Mumbai City, MH'

BEFORE : 'Vayu Â\x80\x93 616, Sy.no 79, Ele Room Â\x80\x93 I, Near Hitech City, Madhapur, Hyderabad, Rangareddy, TG'
AFTER  : 'Vayu – 616, Sy.no 79, Ele Room – I, Near Hitech City, Madhapur, Hyderabad, Rangareddy, TG'

BEFORE : 'Hn 301 A Â\x80\x93 204, Thaltej, <NULL>, GJ'
AFTER  : 'Hn 301 A – 204, Thaltej, <NULL>, GJ'

BEFORE : 'Fourth Floor No.2651, 2 Nd Cross, 15 Th Main, Â\x80\x99eâ\x80\x99 Block, Sahakar Nagar, Bangalore, KA'
AFTER  : 'Fourth Floor No.2651, 2 Nd Cross, 15 Th Main, ’e’ Block, Sahakar Nagar, Bangalore, KA'

BEFORE : 'House No. G-183, Ground Floor, Blockâ\x80\x93a, Metro Vihar Phase Â\x80\x93 1, Village & Post Office Holambi, Kalan, North West Delhi, North Delhi, DL'
AFTER  : 'House No. G-183, Ground Floor, Block–a, Metro Vihar Phase – 1, Village & Post Office Holambi, Kalan, North West Delhi, North Delhi, DL'

BEFORE : 'Cts No14985, Plot No. 140A Iiâ\x80\x99nd Floor, Sindhi Colony, Jalna Road, Aurangabad, महाराष्ट्र'
AFTER  : 'Cts No14985, Plot No. 140A Ii’nd Floor, Sindhi Colony, Jalna Road, Aurangabad, महाराष्ट्र'

BEFORE : 'Swiss County, Flat No. Â\x80\x93 601, S. No. - 37, G-1, Near Pcmc School, Thergaon, Pune, Maharashtra'
AFTER  : 'Swiss County, Flat No. – 601, S. No. - 37, G-1, Near Pcmc School, Thergaon, Pune, Maharashtra'

BEFORE : 'Cts 628 A/5 J.m Road, Bhosale Shinde Arcade, Sâ\x80\x99nagar, Pune, MH'
AFTER  : 'Cts 628 A/5 J.m Road, Bhosale Shinde Arcade, S’nagar, Pune, MH'

BEFORE : 'Property No. Â\x80\x93 B 4-8 A, Old No. Â\x80\x93 B -35 S/f Kh No. Â\x80\x93 829, Chhattarpur Extn., South Delhi, Delhi, DL'
AFTER  : 'Property No. – B 4-8 A, Old No. – B -35 S/f Kh No. – 829, Chhattarpur Extn., South Delhi, Delhi, DL'

BEFORE : 'Mumbai Suburban, Malad West, Mumbai, Shop No 201 Bldg Â\x80\x93b Interface Heights Link Road, Mumbai City, MH'
AFTER  : 'Mumbai Suburban, Malad West, Mumbai, Shop No 201 Bldg –b Interface Heights Link Road, Mumbai City, MH'

In [ ]:
train_source3["business_name_clean"] = (
    train_source3["business_name"].apply(repair_mojibake)
)

train_source3["business_address_clean"] = (
    train_source3["business_address"].apply(repair_mojibake)
)

In [ ]:
name_changed = (
    train_source3["business_name"].fillna("").astype(str)
    != train_source3["business_name_clean"].fillna("").astype(str)
).sum()

address_changed = (
    train_source3["business_address"].fillna("").astype(str)
    != train_source3["business_address_clean"].fillna("").astype(str)
).sum()

print("Business names changed:", name_changed)
print("Business addresses changed:", address_changed)

Business names changed: 0
Business addresses changed: 949

In [ ]:
def clean_control_chars(text):
    if pd.isna(text):
        return text

    text = str(text)

    # Replace ASCII control characters with a space
    text = re.sub(r"[\x00-\x1F\x7F]", " ", text)

    # Normalize repeated whitespace
    text = re.sub(r"\s+", " ", text)

    return text.strip()

In [ ]:
name_control_after = train_source3["business_name_clean"].apply(
    has_control_char
).sum()

address_control_after = train_source3["business_address_clean"].apply(
    has_control_char
).sum()

print("Control chars in cleaned names:", name_control_after)
print("Control chars in cleaned addresses:", address_control_after)

Control chars in cleaned names: 0
Control chars in cleaned addresses: 0

In [ ]:
import unicodedata
import re

def normalize_unicode_text(text):
    if pd.isna(text):
        return text

    text = str(text).lower()

    # Normalize Unicode representation
    text = unicodedata.normalize("NFKC", text)

    result = []

    for char in text:
        category = unicodedata.category(char)

        # Keep letters, numbers and combining marks
        if category[0] in ("L", "N", "M"):
            result.append(char)
        else:
            # Replace punctuation/symbols with space
            result.append(" ")

    text = "".join(result)

    # Remove repeated whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [ ]:
train_source3["business_name_normalized"] = (
    train_source3["business_name_clean"]
    .apply(normalize_unicode_text)
)

train_source3["business_address_normalized"] = (
    train_source3["business_address_clean"]
    .apply(normalize_unicode_text)
)

In [ ]:
print(
    train_source3[
        train_source3["business_name"].notna()
    ][
        ["business_name", "business_name_normalized"]
    ].head(10).to_string(index=False)
)

                              business_name                    business_name_normalized
                         wilfordhancock.com                          wilfordhancock com
International South Consultants Private Ltd international south consultants private ltd
                LLC Moncada Léarning Center                 llc moncada léarning center
                             Moyna's Coffee                              moyna s coffee
               Pvt. EFS Print Ventures Ltd.                  pvt efs print ventures ltd
             LLC Hernandez Colonial Redwood              llc hernandez colonial redwood
              Classic Equity Partners Group               classic equity partners group
             Ectolumdrex dba X+ Madison Inc               ectolumdrex dba x madison inc
                    Animal Hanisch Hospirlg                     animal hanisch hospirlg
                              Gomez Optimal                               gomez optimal

In [ ]:
print(
    train_source3[
        train_source3["business_name"]
        .fillna("")
        .str.contains(r"[\u0900-\u0D7F]", regex=True)
    ][
        ["business_name", "business_name_normalized"]
    ].head(10).to_string(index=False)
)

                                  business_name                        business_name_normalized
            அரிஹந்த் Foundation Private Limited             அரிஹந்த் foundation private limited
           സിൽവർ കൺസൾട്ടൻസി പ്രൈവറ്റ് ലിമിറ്റഡ്            സിൽവർ കൺസൾട്ടൻസി പ്രൈവറ്റ് ലിമിറ്റഡ്
                               ब्लू टेक्नोलॉजीज                                ब्लू टेक्नोलॉजीज
                     గుజరాత్ Logistics లిమిటెడ్                      గుజరాత్ logistics లిమిటెడ్
                  सनराइज फूड्स प्राइवेट लिमिटेड                   सनराइज फूड्स प्राइवेट लिमिटेड
           बेस्ट माँ इंटरनेशनल प्राइवेट लिमिटेड            बेस्ट माँ इंटरनेशनल प्राइवेट लिमिटेड
             ग्रेट एक्सपोर्ट्स प्राइवेट लिमिटेड              ग्रेट एक्सपोर्ट्स प्राइवेट लिमिटेड
               આલ્ફા ફાઉન્ડેશન પ્રાઇવેટ લિમિટેડ                આલ્ફા ફાઉન્ડેશન પ્રાઇવેટ લિમિટેડ
        ಬ್ಲ್ಯಾಕ್ ಇಂಜಿನಿಯರಿಂಗ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್         ಬ್ಲ್ಯಾಕ್ ಇಂಜಿನಿಯರಿಂಗ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್
കൃഷ്ണ ഇന്റർനാഷണൽ ഹാർഡ്‌വെയർ പ്രൈവറ്റ് ലിമിറ്റഡ് കൃഷ്ണ ഇന്റർനാഷണൽ ഹാർഡ് വെയർ പ്രൈവറ്റ് ലിമിറ്റഡ്

In [ ]:
print("Missing normalized names:",
      train_source3["business_name_normalized"].isna().sum())

print("Missing normalized addresses:",
      train_source3["business_address_normalized"].isna().sum())

print("Empty normalized names:",
      (train_source3["business_name_normalized"].fillna("").str.strip() == "").sum())

print("Empty normalized addresses:",
      (train_source3["business_address_normalized"].fillna("").str.strip() == "").sum())

Missing normalized names: 13
Missing normalized addresses: 175916
Empty normalized names: 13
Empty normalized addresses: 175916

In [ ]:
test_source1 = pd.read_csv(
    base_path + "/test/test_source1.tsv",
    sep="\t"
)

print("Shape:", test_source1.shape)
print("Columns:", test_source1.columns.tolist())

print("\nFirst 5 rows:")
print(test_source1.head().to_string(index=False))

Shape: (1732544, 4)
Columns: ['entity_id', 'business_name', 'business_address', 'country']

First 5 rows:
   entity_id        business_name                                                            business_address country
S1-714132312      Zephay Labs Inc                                                 2621 Cotten Road, Tyler, TX      US
S1-106407869 Vision Partners Corp                                      IA, Iowa City, 1064 Newton Rd, Unit 11      US
S1-156285671        << Team Ecole 175 Boulevard du Président Franklin Roosevelt, Bordeaux, Nouvelle-Aquitaine  France
S1-689823050  Red Perfect Trading           Mirzapur, Ews 12, Uttar Pradesh, Mirzapursadar, Awas Vikas Colony   India
S1-921369899        ZNB Club SARL               Nouvelle-Aquitaine, La Teste-de-Buch, 5 bis Rue Pierre Dignac  France

In [ ]:
print("Missing values:")
print(test_source1.isnull().sum())

print("\nMissing percentage:")
print((test_source1.isnull().mean() * 100).round(2))

Missing values:
entity_id           0
business_name       0
business_address    0
country             0
dtype: int64

Missing percentage:
entity_id           0.0
business_name       0.0
business_address    0.0
country             0.0
dtype: float64

In [ ]:
print("Duplicate entity_id:",
      test_source1["entity_id"].duplicated().sum())

print("Duplicate complete rows:",
      test_source1.duplicated().sum())

print("Duplicate business names:",
      test_source1["business_name"].duplicated().sum())

print("Duplicate business addresses:",
      test_source1["business_address"].duplicated().sum())

Duplicate entity_id: 0
Duplicate complete rows: 0
Duplicate business names: 493677
Duplicate business addresses: 55061

In [ ]:
print("Unique countries:")
print(test_source1["country"].unique())

print("\nNumber of unique countries:")
print(test_source1["country"].nunique())

print("\nCountry counts:")
print(test_source1["country"].value_counts())

Unique countries:
['US' 'France' 'India']

Number of unique countries:
3

Country counts:
country
India     809986
US        663106
France    259452
Name: count, dtype: int64

In [ ]:
import re

def has_whitespace_issue(text):
    text = str(text)

    if text != text.strip():
        return True

    if re.search(r"\s{2,}", text):
        return True

    return False

print("Business names with whitespace issues:",
      test_source1["business_name"].apply(has_whitespace_issue).sum())

print("Business addresses with whitespace issues:",
      test_source1["business_address"].apply(has_whitespace_issue).sum())

Business names with whitespace issues: 0
Business addresses with whitespace issues: 753

In [ ]:
import re

def has_control_char(text):
    return bool(re.search(r"[\x00-\x1F\x7F]", str(text)))

print("Business names with control characters:",
      test_source1["business_name"].apply(has_control_char).sum())

print("Business addresses with control characters:",
      test_source1["business_address"].apply(has_control_char).sum())

Business names with control characters: 0
Business addresses with control characters: 72

In [ ]:
def has_non_ascii(text):
    return any(ord(char) > 127 for char in str(text))

print("Business names with non-ASCII characters:",
      test_source1["business_name"].apply(has_non_ascii).sum())

print("Business addresses with non-ASCII characters:",
      test_source1["business_address"].apply(has_non_ascii).sum())

Business names with non-ASCII characters: 40789
Business addresses with non-ASCII characters: 73800

In [ ]:
suspicious_patterns = ["â", "Â", "ï¿", "â", "Â"]

for pattern in suspicious_patterns:
    name_count = test_source1["business_name"].fillna("").str.contains(
        pattern, regex=False
    ).sum()

    address_count = test_source1["business_address"].fillna("").str.contains(
        pattern, regex=False
    ).sum()

    print(
        f"Pattern {repr(pattern)} -> "
        f"names: {name_count}, addresses: {address_count}"
    )

Pattern 'â\x80' -> names: 0, addresses: 105
Pattern 'Â\x80' -> names: 0, addresses: 399
Pattern 'ï¿' -> names: 0, addresses: 5
Pattern 'â' -> names: 9, addresses: 1025
Pattern 'Â' -> names: 0, addresses: 400

In [ ]:
patterns = ["â", "Â", "ï¿", "â", "Â"]

for pattern in patterns:
    print("\n" + "=" * 80)
    print("PATTERN:", repr(pattern))
    print("=" * 80)

    mask_name = test_source1["business_name"].fillna("").str.contains(
        pattern, regex=False
    )

    mask_address = test_source1["business_address"].fillna("").str.contains(
        pattern, regex=False
    )

    print("\nBusiness names:")
    print(test_source1.loc[mask_name, "business_name"].head(10).to_string(index=False))

    print("\nBusiness addresses:")
    print(test_source1.loc[mask_address, "business_address"].head(10).to_string(index=False))

================================================================================
PATTERN: 'â\x80'
================================================================================

Business names:
Series([], )

Business addresses:
#302 ChallaâS Janakiram Residency, 1-65/14/6/...
Shop-F22, Xth Central Mall, Mahavir Nagar, Sect...
West Delhi, Delhi, Hâ140 First Floor Karampur...
Hyderabad, Telangana, 5Th Floor, M. No. 8-2-682...
D1-D4, D9, D10, D18, D19, M CubeâVapi Premier...
Second Floor, Plot No.6, ÂFâ Block, TvdâS...
Second Floor, Plot No.6, ÂFâ Block, TvdâS...
TalâSangamner Ghulewadi, Dist A Nagar, Ghulew...
20-A, 260-261 Paiki, Ishwar (Bapunagar) Ownerâ...
Second Floor, Plot No.6, ÂFâ Block, TvdâS...

================================================================================
PATTERN: 'Â\x80'
================================================================================

Business names:
Series([], )

Business addresses:
B Â 59, Midc, Ph 1, Dombivali, Thane, Maharas...
Gn-26, Sector Â V, Salt Lake., Kolkata, Parga...
Anmol Apartment Flat No. 301, Jalaram Â 1, Un...
Infinity It Lagoon, 9Th Floor, 904A, Plot E2-2/...
Unit No. 1C, 2Nd Floor Carnival Inforpark Phase...
New T-96, Gali No. Â 6, Ground Floor, Uttam N...
 Kh No Â 104 Mauja Chalesar, Agra, Uttar Pradesh
Mumbai, Plot -207, Embassy Centre, Jamnalal Baj...
Shop No.Â35 B Sanman Society, Surat, Ff No- 1...
New Delhi, Shop Â 105, West Delhi, Capital To...

================================================================================
PATTERN: 'ï¿'
================================================================================

Business names:
Series([], )

Business addresses:
Rajasthan, Jaipur, Yojna Shwroop Vihar, Gram To...
Dvg Smarakaï¿½Bhavana, Ghokale Institute Of Pub...
Unit No. 7C, Telangana, 7Th Floor, Myscapeï¿½We...
F/113 J M Nagar, Anand Nagar Pï¿½Dï¿½Rd, Kalyan...
Mumbai, Flat #7, Mumbai, Madhuban, 641, P.D Hin...

================================================================================
PATTERN: 'â'
================================================================================

Business names:
Anglais Château Tech EURL
          TBP Théâtre SAS
  Château Culturelle SARL
        Voie Bâtiment SAS
        Saad Bâtiment SAS
            Lycée Château
             Tae Bâtiment
          Ets Château SAS
 Age (France) Théâtre SAS

Business addresses:
53 Route du Château de Beauregard, Saint-Nazair...
     28 Rue du Château, Tourcoing, Hauts-de-France
    Nouvelle-Aquitaine, Bordeaux, 4 Rue du Château
4 Rue du Château d'Eau, Nouvelle-Aquitaine, Pessac
#302 ChallaâS Janakiram Residency, 1-65/14/6/...
39 Rue du Commandant Gâté, Saint-Nazaire, Pays ...
Mérignac, 38 Rue Château Thierry, Nouvelle-Aqui...
Shop-F22, Xth Central Mall, Mahavir Nagar, Sect...
2 Rue Château Jouguet, Bordeaux, Nouvelle-Aquit...
Saint-Nazaire, 122 Rue du Commandant Gâté, Pays...

================================================================================
PATTERN: 'Â'
================================================================================

Business names:
Series([], )

Business addresses:
B Â 59, Midc, Ph 1, Dombivali, Thane, Maharas...
Gn-26, Sector Â V, Salt Lake., Kolkata, Parga...
Anmol Apartment Flat No. 301, Jalaram Â 1, Un...
Infinity It Lagoon, 9Th Floor, 904A, Plot E2-2/...
Unit No. 1C, 2Nd Floor Carnival Inforpark Phase...
New T-96, Gali No. Â 6, Ground Floor, Uttam N...
 Kh No Â 104 Mauja Chalesar, Agra, Uttar Pradesh
Mumbai, Plot -207, Embassy Centre, Jamnalal Baj...
Shop No.Â35 B Sanman Society, Surat, Ff No- 1...
New Delhi, Shop Â 105, West Delhi, Capital To...

In [ ]:
repair_patterns = {
    "Â\x80\x93": "–",
    "Â\x80\x99": "’",
    "Â\x80\x98": "‘",
    "Â\x80\x90": "‐",

    "â\x80\x93": "–",
    "â\x80\x99": "’",
    "â\x80\x98": "‘",
    "â\x80\x90": "‐"
}

In [ ]:
for bad, good in repair_patterns.items():
    count_name = test_source1["business_name"].fillna("").str.count(bad).sum()
    count_address = test_source1["business_address"].fillna("").str.count(bad).sum()

    print(
        repr(bad),
        "->", repr(good),
        "| names:", int(count_name),
        "| addresses:", int(count_address)
    )

'Â\x80\x93' -> '–' | names: 0 | addresses: 389
'Â\x80\x99' -> '’' | names: 0 | addresses: 2
'Â\x80\x98' -> '‘' | names: 0 | addresses: 44
'Â\x80\x90' -> '‐' | names: 0 | addresses: 2
'â\x80\x93' -> '–' | names: 0 | addresses: 20
'â\x80\x99' -> '’' | names: 0 | addresses: 93
'â\x80\x98' -> '‘' | names: 0 | addresses: 0
'â\x80\x90' -> '‐' | names: 0 | addresses: 2

In [ ]:
def repair_mojibake(text):
    if pd.isna(text):
        return text

    text = str(text)

    replacements = {
        "Â\x80\x93": "–",
        "Â\x80\x99": "’",
        "Â\x80\x98": "‘",
        "Â\x80\x90": "‐",

        "â\x80\x93": "–",
        "â\x80\x99": "’",
        "â\x80\x98": "‘",
        "â\x80\x90": "‐"
    }

    for bad, good in replacements.items():
        text = text.replace(bad, good)

    return text

In [ ]:
test_source1["business_name_clean"] = (
    test_source1["business_name"].apply(repair_mojibake)
)

test_source1["business_address_clean"] = (
    test_source1["business_address"].apply(repair_mojibake)
)

In [ ]:
name_changed = (
    test_source1["business_name"] != test_source1["business_name_clean"]
).sum()

address_changed = (
    test_source1["business_address"] != test_source1["business_address_clean"]
).sum()

print("Business names changed:", name_changed)
print("Business addresses changed:", address_changed)

Business names changed: 0
Business addresses changed: 455

In [ ]:
def clean_control_chars(text):
    if pd.isna(text):
        return text

    text = str(text)
    text = re.sub(r"[\x00-\x1F\x7F]", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

In [ ]:
test_source1["business_name_clean"] = (
    test_source1["business_name_clean"].apply(clean_control_chars)
)

test_source1["business_address_clean"] = (
    test_source1["business_address_clean"].apply(clean_control_chars)
)

In [ ]:
print("Control characters after cleaning:")

print(
    "Business names:",
    test_source1["business_name_clean"].apply(has_control_char).sum()
)

print(
    "Business addresses:",
    test_source1["business_address_clean"].apply(has_control_char).sum()
)

print("\nWhitespace issues after cleaning:")

print(
    "Business names:",
    test_source1["business_name_clean"].apply(has_whitespace_issue).sum()
)

print(
    "Business addresses:",
    test_source1["business_address_clean"].apply(has_whitespace_issue).sum()
)

Control characters after cleaning:
Business names: 0
Business addresses: 0

Whitespace issues after cleaning:
Business names: 0
Business addresses: 0

In [ ]:
import unicodedata
import re

def normalize_unicode_text(text):
    if pd.isna(text):
        return text

    text = str(text).lower()
    text = unicodedata.normalize("NFKC", text)

    result = []

    for char in text:
        category = unicodedata.category(char)

        if category[0] in ("L", "N", "M"):
            result.append(char)
        else:
            result.append(" ")

    text = "".join(result)
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [ ]:
test_source1["business_name_normalized"] = (
    test_source1["business_name_clean"].apply(normalize_unicode_text)
)

test_source1["business_address_normalized"] = (
    test_source1["business_address_clean"].apply(normalize_unicode_text)
)

In [ ]:
print(
    test_source1[
        [
            "business_name",
            "business_name_normalized",
            "business_address",
            "business_address_normalized"
        ]
    ].head(10).to_string(index=False)
)

           business_name business_name_normalized                                                                                                                    business_address                                                                                               business_address_normalized
         Zephay Labs Inc          zephay labs inc                                                                                                         2621 Cotten Road, Tyler, TX                                                                                                 2621 cotten road tyler tx
    Vision Partners Corp     vision partners corp                                                                                              IA, Iowa City, 1064 Newton Rd, Unit 11                                                                                       ia iowa city 1064 newton rd unit 11
           << Team Ecole               team ecole                                                         175 Boulevard du Président Franklin Roosevelt, Bordeaux, Nouvelle-Aquitaine                                                 175 boulevard du président franklin roosevelt bordeaux nouvelle aquitaine
     Red Perfect Trading      red perfect trading                                                                   Mirzapur, Ews 12, Uttar Pradesh, Mirzapursadar, Awas Vikas Colony                                                             mirzapur ews 12 uttar pradesh mirzapursadar awas vikas colony
           ZNB Club SARL            znb club sarl                                                                       Nouvelle-Aquitaine, La Teste-de-Buch, 5 bis Rue Pierre Dignac                                                               nouvelle aquitaine la teste de buch 5 bis rue pierre dignac
       Nandlal Kisan LLP        nandlal kisan llp                                                                       D-61 Ifs Apartmentmayur Vihar I, New Delhi, East Delhi, Delhi                                                                d 61 ifs apartmentmayur vihar i new delhi east delhi delhi
            Cure Seafood             cure seafood                                                                                                    1325 Brooklyn Walk, Issaquah, WA                                                                                            1325 brooklyn walk issaquah wa
Om Constructions Pvt Ltd om constructions pvt ltd                                                                        Karauli, Rajasthan, Karauli, Pani Ki Tanki Ke Pas Choubepada                                                                 karauli rajasthan karauli pani ki tanki ke pas choubepada
           Roongta Sangh            roongta sangh Bhubaneswar, Sub Plot No.-L6/29, Mahodadhi Bhawan (Next To Iter College) Panchasakha Nagar, Dumuduma, Khordha, Plot No.-780, Orissa bhubaneswar sub plot no l6 29 mahodadhi bhawan next to iter college panchasakha nagar dumuduma khordha plot no 780 orissa
     Thermal & Fils SASU        thermal fils sasu                                                                                       20 Rue Parmentier, Dunkerque, Hauts-de-France                                                                               20 rue parmentier dunkerque hauts de france

In [ ]:
print("Missing normalized values:")
print(
    test_source1[
        ["business_name_normalized", "business_address_normalized"]
    ].isnull().sum()
)

print("\nEmpty normalized values:")

print(
    "Business names:",
    (test_source1["business_name_normalized"].fillna("").str.strip() == "").sum()
)

print(
    "Business addresses:",
    (test_source1["business_address_normalized"].fillna("").str.strip() == "").sum()
)

Missing normalized values:
business_name_normalized       0
business_address_normalized    0
dtype: int64

Empty normalized values:
Business names: 0
Business addresses: 0

In [ ]:
test_source2 = pd.read_csv(
    base_path + "/test/test_source2.tsv",
    sep="\t"
)

print("Shape:", test_source2.shape)
print("\nColumns:")
print(test_source2.columns.tolist())

print("\nFirst 5 rows:")
print(test_source2.head())

Shape: (4887273, 4)

Columns:
['entity_id', 'business_name', 'business_address', 'country']

First 5 rows:
      entity_id             business_name  \
0  S2-192345572           Brahma Infosoft
1  S2-566025912  Marina Ecole France Sarl
2  S2-158121477          SCI Ptit Àmicale
3   S2-89663826               Apex Summit
4  S2-884102769              Fresh Truist

                                    business_address country
0  COIMATORE COLONY, HUNSUR TQMYSORE DIST., Karna...   India
1            63 R. DE DIEPPE, LILLE, Hauts-de-France  France
2                    18 RUE JEN ZAY, Dunkerque, Nord  France
3                   67 KENTUCKY ST, SALYERSVILLE, KY      US
4               8264 FILLY COURT, ROANOKE COUNTY, VA      US

In [ ]:
print("Missing values:")
print(test_source2.isnull().sum())

print("\nMissing percentage:")
print((test_source2.isnull().mean() * 100).round(2))

Missing values:
entity_id                0
business_name           46
business_address    129408
country                  0
dtype: int64

Missing percentage:
entity_id           0.00
business_name       0.00
business_address    2.65
country             0.00
dtype: float64

In [ ]:
print("Duplicate entity_id:",
      test_source2["entity_id"].duplicated().sum())

print("Duplicate complete rows:",
      test_source2.duplicated().sum())

print("Duplicate business names:",
      test_source2["business_name"].duplicated().sum())

print("Duplicate business addresses:",
      test_source2["business_address"].duplicated().sum())

Duplicate entity_id: 0
Duplicate complete rows: 0
Duplicate business names: 576232
Duplicate business addresses: 662489

In [ ]:
print("Unique countries:")
print(test_source2["country"].unique())

print("\nNumber of unique countries:")
print(test_source2["country"].nunique())

print("\nCountry counts:")
print(test_source2["country"].value_counts())

Unique countries:
['India' 'France' 'US']

Number of unique countries:
3

Country counts:
country
India     2312565
US        1871330
France     703378
Name: count, dtype: int64

In [ ]:
print("Business names with whitespace issues:",
      test_source2["business_name"].apply(has_whitespace_issue).sum())

print("Business addresses with whitespace issues:",
      test_source2["business_address"].apply(has_whitespace_issue).sum())

Business names with whitespace issues: 500237
Business addresses with whitespace issues: 82739

In [ ]:
print("Business names with control characters:",
      test_source2["business_name"].apply(has_control_char).sum())

print("Business addresses with control characters:",
      test_source2["business_address"].apply(has_control_char).sum())

Business names with control characters: 0
Business addresses with control characters: 183

In [ ]:
print("Business names with non-ASCII characters:",
      test_source2["business_name"].apply(
          lambda x: bool(re.search(r"[^\x00-\x7F]", str(x)))
      ).sum())

print("Business addresses with non-ASCII characters:",
      test_source2["business_address"].apply(
          lambda x: bool(re.search(r"[^\x00-\x7F]", str(x)))
      ).sum())

Business names with non-ASCII characters: 928158
Business addresses with non-ASCII characters: 720665

In [ ]:
patterns = {
    "â": r"â",
    "Â": r"Â",
    "ï¿": r"ï¿",
    "â": r"â",
    "Â": r"Â"
}

for name, pattern in patterns.items():
    name_count = test_source2["business_name"].astype(str).str.contains(
        pattern, regex=False
    ).sum()

    address_count = test_source2["business_address"].astype(str).str.contains(
        pattern, regex=False
    ).sum()

    print(f"{name}: names = {name_count}, addresses = {address_count}")

NameError: name 'test_source2' is not defined

In [ ]:
import pandas as pd
import re

base_path = "/content/drive/MyDrive/Business_model_amazon/extracted_data/student_resource/dataset"

test_source2 = pd.read_csv(
    base_path + "/test/test_source2.tsv",
    sep="\t"
)

print(test_source2.shape)

(4887273, 4)

In [ ]:
patterns = {
    "â": r"â",
    "Â": r"Â",
    "ï¿": r"ï¿",
    "â": r"â",
    "Â": r"Â"
}

for name, pattern in patterns.items():
    name_count = test_source2["business_name"].astype(str).str.contains(
        pattern, regex=False
    ).sum()

    address_count = test_source2["business_address"].astype(str).str.contains(
        pattern, regex=False
    ).sum()

    print(f"{name}: names = {name_count}, addresses = {address_count}")

â: names = 0, addresses = 0
Â: names = 0, addresses = 1185
ï¿: names = 0, addresses = 0
â: names = 4293, addresses = 0
Â: names = 1235, addresses = 2812

In [ ]:
print("=== Â in addresses ===")
print(
    test_source2.loc[
        test_source2["business_address"].astype(str).str.contains("Â", regex=False),
        "business_address"
    ].head(10).to_string(index=False)
)

print("\n=== â in business names ===")
print(
    test_source2.loc[
        test_source2["business_name"].astype(str).str.contains("â", regex=False),
        "business_name"
    ].head(10).to_string(index=False)
)

print("\n=== Â in business names ===")
print(
    test_source2.loc[
        test_source2["business_name"].astype(str).str.contains("Â", regex=False),
        "business_name"
    ].head(10).to_string(index=False)
)

print("\n=== Â in addresses ===")
print(
    test_source2.loc[
        test_source2["business_address"].astype(str).str.contains("Â", regex=False),
        "business_address"
    ].head(10).to_string(index=False)
)

=== Â in addresses ===
NEAR JAGAT DARSHAN SOCIETY, KADI KALOL ROAD, VI...
C-#45, KAILASH APPARTMENTS, LALA LAJPAT RAI MAR...
243, SECOND FLOOR, BLOCK Â EF, JOYOS HUB TOWN...
C/0095-99, SECOND FLOOR, LAJPAT NAGAR Â II, N...
PLOT NO. C 36 Â 42, FOCAL POINT, MANDI GOBIND...
C/O ATUL MITTAL, 1001, NDM Â 1, NETAJI SUBHAS...
B. NO. X Â A-60 G10, GREEN GARDEN ROAD POICHI...
BAGAMANE HERMITAGE, NO.22/12, 3RD FLOOR DÂSOU...
HN #377 PRISM MALL, SY. NO. 4/P, 5/P, 6/1/E KON...
Tamil Nadu, CHENNAI, H.NO 49 SECOND FLOOR, PLOT...

=== â in business names ===
                 Clinique Sâinte
          Barth Theatre (Frânce)
             Amicale de lâ Notre
        Libi Service (Frânce) EI
          Union Sâint Mediateurs
Soutien Groupement (Frânce) EURL
     Durable Jules Phârmacie SAS
              de Association Fâs
      La Baule-Escoublac Pârents
        Eleves (France) Bâr SARL

=== Â in business names ===
ÉTABLISSEMENTS TÂURIN INTERNATIONAL SARL
                      LV PÂTRIMOINE SARL
                   SALINS PÂTRIMOINE SAS
                         LYCÉE DU BÂRRIO
                     EUROPEEN SÂNTE SARL
            AMATEURS (FRÂNCE) GROUPE SAS
                    ASSOCIATION DU SÂLON
              ISLAMIQUE MUSIQUE (FRÂNCE)
  DINFORMATION DÂSTRONOMIE CULTUREL EURL
                SARL DEMPLOYEURS PÂRENTS

=== Â in addresses ===
47 RUE CHÂTEAU JOUGUET, BORDEAUX, Nouvelle-Aqui...
NEAR JAGAT DARSHAN SOCIETY, KADI KALOL ROAD, VI...
3 IMP. DES PÂQUERETTES, LA BAULE-ESCOUBLAC, Loi...
C-#45, KAILASH APPARTMENTS, LALA LAJPAT RAI MAR...
                     6 PBACE DU THÉÂTRE, TOURCOING
243, SECOND FLOOR, BLOCK Â EF, JOYOS HUB TOWN...
C/0095-99, SECOND FLOOR, LAJPAT NAGAR Â II, N...
PLOT NO. C 36 Â 42, FOCAL POINT, MANDI GOBIND...
C/O ATUL MITTAL, 1001, NDM Â 1, NETAJI SUBHAS...
6 RUE DU CHÂTEAU DE L'ERAUIÈRE, NANTES, Pays de...

In [ ]:
repair_patterns = {
    "Â\x80\x93": "–",
    "Â\x80\x99": "’",
    "Â\x80\x98": "‘",
    "Â\x80\x90": "‐"
}

In [ ]:
for bad, good in repair_patterns.items():
    name_count = test_source2["business_name"].astype(str).str.count(bad).sum()
    address_count = test_source2["business_address"].astype(str).str.count(bad).sum()

    print(
        f"{repr(bad)} -> {repr(good)}: "
        f"names = {name_count}, addresses = {address_count}"
    )

'Â\x80\x93' -> '–': names = 0, addresses = 1065
'Â\x80\x99' -> '’': names = 0, addresses = 222
'Â\x80\x98' -> '‘': names = 0, addresses = 108
'Â\x80\x90' -> '‐': names = 0, addresses = 9

In [ ]:
def repair_mojibake(text):
    if pd.isna(text):
        return text

    text = str(text)

    replacements = {
        "Â\x80\x93": "–",
        "Â\x80\x99": "’",
        "Â\x80\x98": "‘",
        "Â\x80\x90": "‐"
    }

    for bad, good in replacements.items():
        text = text.replace(bad, good)

    return text


test_source2["business_name_clean"] = (
    test_source2["business_name"]
    .apply(repair_mojibake)
)

test_source2["business_address_clean"] = (
    test_source2["business_address"]
    .apply(repair_mojibake)
)

print("Business names changed:",
      (test_source2["business_name"] != test_source2["business_name_clean"]).sum())

print("Business addresses changed:",
      (test_source2["business_address"] != test_source2["business_address_clean"]).sum())

Business names changed: 46
Business addresses changed: 130586

In [ ]:
test_source2["business_name_clean"] = (
    test_source2["business_name_clean"]
    .apply(clean_control_chars)
)

test_source2["business_address_clean"] = (
    test_source2["business_address_clean"]
    .apply(clean_control_chars)
)

print("Control characters after cleaning:")
print(
    "Names:",
    test_source2["business_name_clean"]
    .apply(has_control_char)
    .sum()
)

print(
    "Addresses:",
    test_source2["business_address_clean"]
    .apply(has_control_char)
    .sum()
)

print("\nWhitespace issues after cleaning:")
print(
    "Names:",
    test_source2["business_name_clean"]
    .apply(has_whitespace_issue)
    .sum()
)

print(
    "Addresses:",
    test_source2["business_address_clean"]
    .apply(has_whitespace_issue)
    .sum()
)

NameError: name 'clean_control_chars' is not defined

In [ ]:
import re

def clean_control_chars(text):
    if pd.isna(text):
        return text

    text = str(text)

    # Remove hidden control characters
    text = re.sub(r"[\x00-\x1F\x7F]", " ", text)

    # Replace multiple spaces with a single space
    text = re.sub(r"\s+", " ", text)

    return text.strip()

In [ ]:
test_source2["business_name_clean"] = (
    test_source2["business_name_clean"]
    .apply(clean_control_chars)
)

test_source2["business_address_clean"] = (
    test_source2["business_address_clean"]
    .apply(clean_control_chars)
)

print("Control characters after cleaning:")
print(
    "Names:",
    test_source2["business_name_clean"]
    .apply(has_control_char)
    .sum()
)

print(
    "Addresses:",
    test_source2["business_address_clean"]
    .apply(has_control_char)
    .sum()
)

print("\nWhitespace issues after cleaning:")
print(
    "Names:",
    test_source2["business_name_clean"]
    .apply(has_whitespace_issue)
    .sum()
)

print(
    "Addresses:",
    test_source2["business_address_clean"]
    .apply(has_whitespace_issue)
    .sum()
)

Control characters after cleaning:

NameError: name 'has_control_char' is not defined

In [ ]:
import re

def has_control_char(text):
    if pd.isna(text):
        return False
    return bool(re.search(r"[\x00-\x1F\x7F]", str(text)))


def has_whitespace_issue(text):
    if pd.isna(text):
        return False

    text = str(text)

    if text != text.strip():
        return True

    if re.search(r"\s{2,}", text):
        return True

    return False

In [ ]:
print("Control characters after cleaning:")

print(
    "Names:",
    test_source2["business_name_clean"]
    .apply(has_control_char)
    .sum()
)

print(
    "Addresses:",
    test_source2["business_address_clean"]
    .apply(has_control_char)
    .sum()
)

print("\nWhitespace issues after cleaning:")

print(
    "Names:",
    test_source2["business_name_clean"]
    .apply(has_whitespace_issue)
    .sum()
)

print(
    "Addresses:",
    test_source2["business_address_clean"]
    .apply(has_whitespace_issue)
    .sum()
)

Control characters after cleaning:
Names: 0
Addresses: 0

Whitespace issues after cleaning:
Names: 0
Addresses: 0

In [ ]:
import unicodedata
import re

def normalize_unicode_text(text):
    if pd.isna(text):
        return text

    text = str(text).lower()

    # Standardize Unicode representation
    text = unicodedata.normalize("NFKC", text)

    result = []

    for char in text:
        category = unicodedata.category(char)

        # Keep letters, numbers and combining marks
        if category[0] in ("L", "N", "M"):
            result.append(char)
        else:
            result.append(" ")

    text = "".join(result)

    # Standardize whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [ ]:
test_source2["business_name_normalized"] = (
    test_source2["business_name_clean"]
    .apply(normalize_unicode_text)
)

test_source2["business_address_normalized"] = (
    test_source2["business_address_clean"]
    .apply(normalize_unicode_text)
)

print(test_source2[
    [
        "business_name",
        "business_name_clean",
        "business_name_normalized",
        "business_address",
        "business_address_clean",
        "business_address_normalized"
    ]
].head(10).to_string(index=False))

                      business_name                 business_name_clean           business_name_normalized                                                                          business_address                                                                    business_address_clean                                                        business_address_normalized
                    Brahma Infosoft                     Brahma Infosoft                    brahma infosoft                                        COIMATORE COLONY, HUNSUR TQMYSORE DIST., Karnataka                                        COIMATORE COLONY, HUNSUR TQMYSORE DIST., Karnataka                                    coimatore colony hunsur tqmysore dist karnataka
           Marina Ecole France Sarl            Marina Ecole France Sarl           marina ecole france sarl                                                   63 R. DE DIEPPE, LILLE, Hauts-de-France                                                   63 R. DE DIEPPE, LILLE, Hauts-de-France                                               63 r de dieppe lille hauts de france
                   SCI Ptit Àmicale                    SCI Ptit Àmicale                   sci ptit àmicale                                                           18 RUE JEN ZAY, Dunkerque, Nord                                                           18 RUE JEN ZAY, Dunkerque, Nord                                                      18 rue jen zay dunkerque nord
                        Apex Summit                         Apex Summit                        apex summit                                                          67 KENTUCKY ST, SALYERSVILLE, KY                                                          67 KENTUCKY ST, SALYERSVILLE, KY                                                     67 kentucky st salyersville ky
                       Fresh Truist                        Fresh Truist                       fresh truist                                                      8264 FILLY COURT, ROANOKE COUNTY, VA                                                      8264 FILLY COURT, ROANOKE COUNTY, VA                                                 8264 filly court roanoke county va
PVT. INDUSTRIES PMB LEASING LIMITED PVT. INDUSTRIES PMB LEASING LIMITED pvt industries pmb leasing limited SURAT, OFFICE NO. 03038, TRADE HOUSE, NEAR RUSHABH PETROL PUMP, RING ROAD, Gujarat, SURAT SURAT, OFFICE NO. 03038, TRADE HOUSE, NEAR RUSHABH PETROL PUMP, RING ROAD, Gujarat, SURAT surat office no 03038 trade house near rushabh petrol pump ring road gujarat surat
                 Clm Agro [Limited]                  Clm Agro [Limited]                   clm agro limited                   G-B3/5, T V INDUSTRIAL ESTATE 248/A, S K AHIRE MARG, WORLI, Maharashtra                   G-B3/5, T V INDUSTRIAL ESTATE 248/A, S K AHIRE MARG, WORLI, Maharashtra                g b3 5 t v industrial estate 248 a s k ahire marg worli maharashtra
              sci ligue ici parents               sci ligue ici parents              sci ligue ici parents                                          NO. 5 ALLÉE DES HÊTRES, Pornic, Loire-Atlantique                                          NO. 5 ALLÉE DES HÊTRES, Pornic, Loire-Atlantique                                      no 5 allée des hêtres pornic loire atlantique
               A DIAMOND  SHORT LLC                 A DIAMOND SHORT LLC                a diamond short llc                                                       126-B New Line Road, MORRISTOWN, TN                                                       126-B New Line Road, MORRISTOWN, TN                                                  126 b new line road morristown tn
              Fanni's Dmaigesostcis               Fanni's Dmaigesostcis              fanni s dmaigesostcis                                                                1200 HWY 1187, CROWLEY, TX                                                                1200 HWY 1187, CROWLEY, TX                                                           1200 hwy 1187 crowley tx

In [ ]:
print("Missing normalized business names:",
      test_source2["business_name_normalized"].isna().sum())

print("Missing normalized business addresses:",
      test_source2["business_address_normalized"].isna().sum())

print("\nEmpty normalized business names:",
      (test_source2["business_name_normalized"].fillna("").str.strip() == "").sum())

print("Empty normalized business addresses:",
      (test_source2["business_address_normalized"].fillna("").str.strip() == "").sum())

Missing normalized business names: 46
Missing normalized business addresses: 129408

Empty normalized business names: 46
Empty normalized business addresses: 129408

In [ ]:
test_source3 = pd.read_csv(
    base_path + "/test/test_source3.tsv",
    sep="\t"
)

print(test_source3.shape)
print(test_source3.columns.tolist())

(5082316, 4)
['entity_id', 'business_name', 'business_address', 'country']

In [ ]:
print("Missing values:")
print(test_source3.isnull().sum())

print("\nMissing percentage:")
print(
    (test_source3.isnull().sum() / len(test_source3) * 100).round(2)
)

Missing values:
entity_id                0
business_name           59
business_address    136098
country                  0
dtype: int64

Missing percentage:
entity_id           0.00
business_name       0.00
business_address    2.68
country             0.00
dtype: float64

In [ ]:
print("Duplicate entity_id:",
      test_source3["entity_id"].duplicated().sum())

print("Duplicate complete rows:",
      test_source3.duplicated().sum())

print("Duplicate business names:",
      test_source3["business_name"].duplicated().sum())

print("Duplicate business addresses:",
      test_source3["business_address"].duplicated().sum())

Duplicate entity_id: 0
Duplicate complete rows: 0
Duplicate business names: 560387
Duplicate business addresses: 625880

In [ ]:
print("Unique countries:")
print(test_source3["country"].unique())

print("\nNumber of unique countries:")
print(test_source3["country"].nunique())

print("\nCountry counts:")
print(test_source3["country"].value_counts())

Unique countries:
['India' 'France' 'US']

Number of unique countries:
3

Country counts:
country
India     2405000
US        1945701
France     731615
Name: count, dtype: int64

In [ ]:
print("Business names with whitespace issues:",
      test_source3["business_name"].apply(has_whitespace_issue).sum())

print("Business addresses with whitespace issues:",
      test_source3["business_address"].apply(has_whitespace_issue).sum())

Business names with whitespace issues: 519596
Business addresses with whitespace issues: 3126

In [ ]:
print("Business names with control characters:",
      test_source3["business_name"].apply(has_control_char).sum())

print("Business addresses with control characters:",
      test_source3["business_address"].apply(has_control_char).sum())

Business names with control characters: 0
Business addresses with control characters: 162

In [ ]:
def has_non_ascii(text):
    if pd.isna(text):
        return False
    return any(ord(char) > 127 for char in str(text))


print("Business names with non-ASCII characters:",
      test_source3["business_name"].apply(has_non_ascii).sum())

print("Business addresses with non-ASCII characters:",
      test_source3["business_address"].apply(has_non_ascii).sum())

Business names with non-ASCII characters: 737515
Business addresses with non-ASCII characters: 729222

In [ ]:
patterns = ["â", "Â", "ï¿", "â", "Â"]

for pattern in patterns:
    name_count = test_source3["business_name"].fillna("").str.contains(
        pattern, regex=False
    ).sum()

    address_count = test_source3["business_address"].fillna("").str.contains(
        pattern, regex=False
    ).sum()

    print(f"Pattern '{pattern}':")
    print("  Business names   :", name_count)
    print("  Business addresses:", address_count)
    print()

Pattern 'â':
  Business names   : 0
  Business addresses: 259

Pattern 'Â':
  Business names   : 0
  Business addresses: 856

Pattern 'ï¿':
  Business names   : 0
  Business addresses: 14

Pattern 'â':
  Business names   : 5415
  Business addresses: 2037

Pattern 'Â':
  Business names   : 1
  Business addresses: 856

In [ ]:
patterns_to_check = ["â", "Â", "ï¿", "â", "Â"]

for pattern in patterns_to_check:
    print("\n" + "=" * 60)
    print("PATTERN:", repr(pattern))
    print("=" * 60)

    print("\nBusiness names:")
    names = test_source3.loc[
        test_source3["business_name"].fillna("").str.contains(pattern, regex=False),
        "business_name"
    ].head(10)

    for x in names:
        print(x)

    print("\nBusiness addresses:")
    addresses = test_source3.loc[
        test_source3["business_address"].fillna("").str.contains(pattern, regex=False),
        "business_address"
    ].head(10)

    for x in addresses:
        print(x)

============================================================
PATTERN: 'â\x80'
============================================================

Business names:

Business addresses:
Plot No.-14, (ÂGokulâ Bungalow) Girija Housing Soc, Old Mit College Road, Kothrud, Pune, MH
G-5, Bldg Noâ1, Wing-a New India Chambers, Vlg, Mulgaon, Midc Road, Bhd Onida House, And, Heri East, Mumbai (SUBURBAN), MH
Topsia Road(south) Kolkata, Kolkata, WB, Puspanjali Chambersâ Apartment No. 004B 9/11A, Kolkata Region, Howrah
Sa-6/2âd-15, Pahariya, Varanasi, Lohta, उत्तर प्रदेश
Indospace Industrial Park Oragadam, Unit A Building No Bâ400, Panrutti Village, Sri, Perumbudur, Kancheepuram, TN
Ukmâs Aurum, Jaipur, RJ
Plot No.-14, (ÂGokulâ Bungalow) Girija Housing Soc, Old Mit College Road, Kothrud, Pune, MH
No 1399/1615 Balia P.s.â Sahadevkhunta, Balasore, Banaparia, OD
Hdâ43, Bangalore, Bengaluru, KA
Plot 316 Hâ140 First Floor Karampura, West Delhi, New Delhi, दिल्ली

============================================================
PATTERN: 'Â\x80'
============================================================

Business names:

Business addresses:
14/28, Sector Â 14 Indira Nagar, Uko, Lucknow, UP
H.no 0083 Jamdheeh Pandey Post Â Labnapar, Basti, UP
Lane No. 1, At Âshriwardha Tal Shriwardhan Dist Ârai Sriwardhan, Raigad, Raigarh, महाराष्ट्र
Plot No.-14, (ÂGokulâ Bungalow) Girija Housing Soc, Old Mit College Road, Kothrud, Pune, MH
M-126, Floor Â Mezzfl, 15A/15B, Supariwala Estate Tata Road No. 2, Roxy Cinema Opera House, Girgaon, Girgaon, MH
Hn 727 B Â 1005, Mumbai, Mumbai City, MH
G-31/833, No:iii/223 Pr Â 11(1), 4Th Floor, Door No: D1 V Square It Hub, Pulikillam West Road, C, Hembumukku, Ernakulam, Keralam
No. Hig Â 1017, 5Th Street, Mogappair Eri Scheme, Chennai, தமிழ்நாடு
Shop Â 105, Capital Tower, Inder Enclave Paschim Vihar, New Delhi, West Delhi, DL
Bihar, Patna, Post - Digha P.S Â Danapur, District - Patna, Patna, Nasriganj

============================================================
PATTERN: 'ï¿'
============================================================

Business names:

Business addresses:
Dvg Smarakaï¿½bhavana, Ghokale Institute Of Public Affairs, No. 2/86/1 A, 5Th Main, Bull Temple Road, N. R. Colony, Bangalore South, Bangalore, KA
Dn. 820 A Block, 2Nd Cro, Anandaï¿½nagara, Mysore, ಕರ್ನಾಟಕ
Plot No 38A, Yojna Shwroop Vihar, Gram Todiramjanipura, Jagatupura, Ï¿½jaipurï¿½-ï¿½, Jaipur, RJ
Unit No. 7C, 7Th Floor, Myscapeï¿½weave In Survey No. 322(P), Municipal No. Mc/mnk/tp/34/2019-2020, Puppalaguda, Gandipet, Hyderabad, TG
Unot No. 9C/4, 7Th Floor, Myscapeï¿½weave In Survey No. 322(P), Municipal No. Mc/mnk/tp/34/2019-2020, Puppalaguda, Gandipet, Seri Lingampally, Hyderabad, Andhra Pradesh
Flat #7, Madhuban, 641, P.d Hinduja Marg Kharï¿½(w), Mumbai, महाराष्ट्र
Dvg Smarakaï¿½bhavana, Bangalore South, KA, Ghokale Institute Of Public Affairs, No. 2/86/1 A, 5Th Main, Bull Temple Road, N. R. Colony, Bangalore
##75 Dvg Smarakaï¿½bhavana, Bangalore South, Bangalore, KA
No ##75 Dvg Smarakaï¿½bhavana, Ghokale Institute Of Public Affairs, No. 2/86/1 A, 5Th Main, Bull Temple Road, N. R. Colony, Bangalore South, Bangalore, KA
C-217/a3ï¿½kaikattipudur, Avanashi, Coimbatore, தமிழ்நாடு

============================================================
PATTERN: 'â'
============================================================

Business names:
EURL Corpo Pârents Holding
Mons Club (Frânce) SAS
Mâm de Clinique
SARL Danses (Frânce) Foyer
École mâternelle Paintball
Team Sânte International
Solidarite Phârmacie
Calais Phârmacie SAS
Ets Stâges SA
Pharmacie Sâinte Cameleon

Business addresses:
30 Rue De Châteaudun, Lille
14 Rue De Châteaulin, Nantes, Loire-Atlantique
N°50 R. Du Châtau, Tourcoing, Nord
65 - Rue Des Gâts, Pornic
6 Bis Chemin De La Butte Du Château, St-nazaire
No. 9 R Du Pâtisseau, Pornic, Pays de la Loire
25 Rue Du Château D'isenghien, Lille, Hauts-de-France
28 Blvd Bâtonnier Cholet, Nantes
40 Rue Des Gâts, Pornic
36 R. De Mâcon, Tourcoing, Nord

============================================================
PATTERN: 'Â'
============================================================

Business names:
SAAD BÂTIMENT DISTRIBUTION SAS

Business addresses:
14/28, Sector Â 14 Indira Nagar, Uko, Lucknow, UP
H.no 0083 Jamdheeh Pandey Post Â Labnapar, Basti, UP
Lane No. 1, At Âshriwardha Tal Shriwardhan Dist Ârai Sriwardhan, Raigad, Raigarh, महाराष्ट्र
Plot No.-14, (ÂGokulâ Bungalow) Girija Housing Soc, Old Mit College Road, Kothrud, Pune, MH
M-126, Floor Â Mezzfl, 15A/15B, Supariwala Estate Tata Road No. 2, Roxy Cinema Opera House, Girgaon, Girgaon, MH
Hn 727 B Â 1005, Mumbai, Mumbai City, MH
G-31/833, No:iii/223 Pr Â 11(1), 4Th Floor, Door No: D1 V Square It Hub, Pulikillam West Road, C, Hembumukku, Ernakulam, Keralam
No. Hig Â 1017, 5Th Street, Mogappair Eri Scheme, Chennai, தமிழ்நாடு
Shop Â 105, Capital Tower, Inder Enclave Paschim Vihar, New Delhi, West Delhi, DL
Bihar, Patna, Post - Digha P.S Â Danapur, District - Patna, Patna, Nasriganj

In [ ]:
patterns_to_check = ["ï¿", "â", "Â"]

for pattern in patterns_to_check:
    print("\n" + "=" * 60)
    print("PATTERN:", repr(pattern))
    print("=" * 60)

    print("\nBusiness names:")
    names = test_source3.loc[
        test_source3["business_name"].fillna("").str.contains(pattern, regex=False),
        "business_name"
    ].head(10)

    for x in names:
        print(x)

    print("\nBusiness addresses:")
    addresses = test_source3.loc[
        test_source3["business_address"].fillna("").str.contains(pattern, regex=False),
        "business_address"
    ].head(10)

    for x in addresses:
        print(x)

============================================================
PATTERN: 'ï¿'
============================================================

Business names:

Business addresses:
Dvg Smarakaï¿½bhavana, Ghokale Institute Of Public Affairs, No. 2/86/1 A, 5Th Main, Bull Temple Road, N. R. Colony, Bangalore South, Bangalore, KA
Dn. 820 A Block, 2Nd Cro, Anandaï¿½nagara, Mysore, ಕರ್ನಾಟಕ
Plot No 38A, Yojna Shwroop Vihar, Gram Todiramjanipura, Jagatupura, Ï¿½jaipurï¿½-ï¿½, Jaipur, RJ
Unit No. 7C, 7Th Floor, Myscapeï¿½weave In Survey No. 322(P), Municipal No. Mc/mnk/tp/34/2019-2020, Puppalaguda, Gandipet, Hyderabad, TG
Unot No. 9C/4, 7Th Floor, Myscapeï¿½weave In Survey No. 322(P), Municipal No. Mc/mnk/tp/34/2019-2020, Puppalaguda, Gandipet, Seri Lingampally, Hyderabad, Andhra Pradesh
Flat #7, Madhuban, 641, P.d Hinduja Marg Kharï¿½(w), Mumbai, महाराष्ट्र
Dvg Smarakaï¿½bhavana, Bangalore South, KA, Ghokale Institute Of Public Affairs, No. 2/86/1 A, 5Th Main, Bull Temple Road, N. R. Colony, Bangalore
##75 Dvg Smarakaï¿½bhavana, Bangalore South, Bangalore, KA
No ##75 Dvg Smarakaï¿½bhavana, Ghokale Institute Of Public Affairs, No. 2/86/1 A, 5Th Main, Bull Temple Road, N. R. Colony, Bangalore South, Bangalore, KA
C-217/a3ï¿½kaikattipudur, Avanashi, Coimbatore, தமிழ்நாடு

============================================================
PATTERN: 'â'
============================================================

Business names:
EURL Corpo Pârents Holding
Mons Club (Frânce) SAS
Mâm de Clinique
SARL Danses (Frânce) Foyer
École mâternelle Paintball
Team Sânte International
Solidarite Phârmacie
Calais Phârmacie SAS
Ets Stâges SA
Pharmacie Sâinte Cameleon

Business addresses:
30 Rue De Châteaudun, Lille
14 Rue De Châteaulin, Nantes, Loire-Atlantique
N°50 R. Du Châtau, Tourcoing, Nord
65 - Rue Des Gâts, Pornic
6 Bis Chemin De La Butte Du Château, St-nazaire
No. 9 R Du Pâtisseau, Pornic, Pays de la Loire
25 Rue Du Château D'isenghien, Lille, Hauts-de-France
28 Blvd Bâtonnier Cholet, Nantes
40 Rue Des Gâts, Pornic
36 R. De Mâcon, Tourcoing, Nord

============================================================
PATTERN: 'Â'
============================================================

Business names:
SAAD BÂTIMENT DISTRIBUTION SAS

Business addresses:
14/28, Sector Â 14 Indira Nagar, Uko, Lucknow, UP
H.no 0083 Jamdheeh Pandey Post Â Labnapar, Basti, UP
Lane No. 1, At Âshriwardha Tal Shriwardhan Dist Ârai Sriwardhan, Raigad, Raigarh, महाराष्ट्र
Plot No.-14, (ÂGokulâ Bungalow) Girija Housing Soc, Old Mit College Road, Kothrud, Pune, MH
M-126, Floor Â Mezzfl, 15A/15B, Supariwala Estate Tata Road No. 2, Roxy Cinema Opera House, Girgaon, Girgaon, MH
Hn 727 B Â 1005, Mumbai, Mumbai City, MH
G-31/833, No:iii/223 Pr Â 11(1), 4Th Floor, Door No: D1 V Square It Hub, Pulikillam West Road, C, Hembumukku, Ernakulam, Keralam
No. Hig Â 1017, 5Th Street, Mogappair Eri Scheme, Chennai, தமிழ்நாடு
Shop Â 105, Capital Tower, Inder Enclave Paschim Vihar, New Delhi, West Delhi, DL
Bihar, Patna, Post - Digha P.S Â Danapur, District - Patna, Patna, Nasriganj

In [ ]:
repair_patterns = {
    "Â\x80\x93": "–",
    "Â\x80\x99": "’",
    "Â\x80\x98": "‘",
    "Â\x80\x90": "‐",
    "â\x80\x93": "–",
    "â\x80\x99": "’",
    "â\x80\x98": "‘",
    "â\x80\x90": "‐"
}

for bad, good in repair_patterns.items():

    name_count = test_source3["business_name"].fillna("").str.count(bad).sum()
    address_count = test_source3["business_address"].fillna("").str.count(bad).sum()

    print(repr(bad), "->", repr(good))
    print("  Business names   :", int(name_count))
    print("  Business addresses:", int(address_count))

'Â\x80\x93' -> '–'
  Business names   : 0
  Business addresses: 822
'Â\x80\x99' -> '’'
  Business names   : 0
  Business addresses: 3
'Â\x80\x98' -> '‘'
  Business names   : 0
  Business addresses: 93
'Â\x80\x90' -> '‐'
  Business names   : 0
  Business addresses: 6
'â\x80\x93' -> '–'
  Business names   : 0
  Business addresses: 66
'â\x80\x99' -> '’'
  Business names   : 0
  Business addresses: 207
'â\x80\x98' -> '‘'
  Business names   : 0
  Business addresses: 0
'â\x80\x90' -> '‐'
  Business names   : 0
  Business addresses: 6

In [ ]:
def repair_mojibake(text):
    if pd.isna(text):
        return text

    text = str(text)

    replacements = {
        "Â\x80\x93": "–",
        "Â\x80\x99": "’",
        "Â\x80\x98": "‘",
        "Â\x80\x90": "‐",
        "â\x80\x93": "–",
        "â\x80\x99": "’",
        "â\x80\x98": "‘",
        "â\x80\x90": "‐"
    }

    for bad, good in replacements.items():
        text = text.replace(bad, good)

    return text


test_source3["business_name_clean"] = (
    test_source3["business_name"].apply(repair_mojibake)
)

test_source3["business_address_clean"] = (
    test_source3["business_address"].apply(repair_mojibake)
)

In [ ]:
name_changed = (
    test_source3["business_name"].notna() &
    (test_source3["business_name"] != test_source3["business_name_clean"])
).sum()

address_changed = (
    test_source3["business_address"].notna() &
    (test_source3["business_address"] != test_source3["business_address_clean"])
).sum()

print("Business names actually changed:", name_changed)
print("Business addresses actually changed:", address_changed)

Business names actually changed: 0
Business addresses actually changed: 1007

In [ ]:
test_source3["business_name_clean"] = (
    test_source3["business_name_clean"]
    .apply(clean_control_chars)
)

test_source3["business_address_clean"] = (
    test_source3["business_address_clean"]
    .apply(clean_control_chars)
)

In [ ]:
print("Control characters after cleaning:")
print(
    "Business names   :",
    test_source3["business_name_clean"].apply(has_control_char).sum()
)
print(
    "Business addresses:",
    test_source3["business_address_clean"].apply(has_control_char).sum()
)

print("\nWhitespace issues after cleaning:")
print(
    "Business names   :",
    test_source3["business_name_clean"].apply(has_whitespace_issue).sum()
)
print(
    "Business addresses:",
    test_source3["business_address_clean"].apply(has_whitespace_issue).sum()
)

Control characters after cleaning:
Business names   : 0
Business addresses: 0

Whitespace issues after cleaning:
Business names   : 0
Business addresses: 0

In [ ]:
test_source3["business_name_normalized"] = (
    test_source3["business_name_clean"]
    .apply(normalize_unicode_text)
)

test_source3["business_address_normalized"] = (
    test_source3["business_address_clean"]
    .apply(normalize_unicode_text)
)

In [ ]:
print(
    test_source3[
        [
            "business_name",
            "business_name_clean",
            "business_name_normalized",
            "business_address",
            "business_address_clean",
            "business_address_normalized"
        ]
    ].head(10).to_string(index=False)
)

                             business_name                       business_name_clean                business_name_normalized                                                              business_address                                                        business_address_clean                                                business_address_normalized
                            मॉडर्न फाइनेंस                            मॉडर्न फाइनेंस                          मॉडर्न फाइनेंस          No 10 Enkay Square, 448A, Udyog Vihar Phase V, Gurugram, Gurgaon, HR          No 10 Enkay Square, 448A, Udyog Vihar Phase V, Gurugram, Gurgaon, HR            no 10 enkay square 448a udyog vihar phase v gurugram gurgaon hr
                     Shri Sai Infratech Co                     Shri Sai Infratech Co                   shri sai infratech co                                                         3/115, East Delhi, DL                                                         3/115, East Delhi, DL                                                        3 115 east delhi dl
               Fractales Amis Groupe S.A.S               Fractales Amis Groupe S.A.S             fractales amis groupe s a s                                       23 Rue Icmre, La Teste-de-buch, Gironde                                       23 Rue Icmre, La Teste-de-buch, Gironde                                      23 rue icmre la teste de buch gironde
Shri Supreme Consulting Private  (Limited) Shri Supreme Consulting Private (Limited) shri supreme consulting private limited                                           H.no 910 A 3503, Mumbai, महाराष्ट्र                                           H.no 910 A 3503, Mumbai, महाराष्ट्र                                          h no 910 a 3503 mumbai महाराष्ट्र
      Prime Realty Ventures Public Limited      Prime Realty Ventures Public Limited    prime realty ventures public limited              G.t. Karnal Road, Industrial Area, New Delhi, null, A-68, दिल्ली              G.t. Karnal Road, Industrial Area, New Delhi, null, A-68, दिल्ली                 g t karnal road industrial area new delhi null a 68 दिल्ली
               Perfect Investments Private               Perfect Investments Private             perfect investments private  Plot No.99, Flat No.201, Sri Dhama Apts., Road No.4, Shaikpet, Hyderabad, TG  Plot No.99, Flat No.201, Sri Dhama Apts., Road No.4, Shaikpet, Hyderabad, TG      plot no 99 flat no 201 sri dhama apts road no 4 shaikpet hyderabad tg
                               Pace Mfa PC                               Pace Mfa PC                             pace mfa pc                                       2132 Thomas Run Road, Bel Air, Maryland                                       2132 Thomas Run Road, Bel Air, Maryland                                      2132 thomas run road bel air maryland
    ஈஸ்டர்ன் கன்சல்டன்சி பிரைவேட் லிமிடெட்    ஈஸ்டர்ன் கன்சல்டன்சி பிரைவேட் லிமிடெட்  ஈஸ்டர்ன் கன்சல்டன்சி பிரைவேட் லிமிடெட் 1410 Sri Mahalakshmi Mandiar 59, Justice Rathinavel Pandian Road, Chennai, TN 1410 Sri Mahalakshmi Mandiar 59, Justice Rathinavel Pandian Road, Chennai, TN 1410 sri mahalakshmi mandiar 59 justice rathinavel pandian road chennai tn
                     PU Pvt. Ltd. Services                     PU Pvt. Ltd. Services                     pu pvt ltd services     TG, Plot No-25, Hyderabad, Qutubullapur, 26, 27, Mayuri Nagar, Bachupally     TG, Plot No-25, Hyderabad, Qutubullapur, 26, 27, Mayuri Nagar, Bachupally         tg plot no 25 hyderabad qutubullapur 26 27 mayuri nagar bachupally
                        Sun पावर Provision                        Sun पावर Provision                      sun पावर provision                      143-Alig Flats Rajouri Garden, New Delhi, West Delhi, DL                      143-Alig Flats Rajouri Garden, New Delhi, West Delhi, DL                      143 alig flats rajouri garden new delhi west delhi dl

In [ ]:
print("Missing normalized business names:",
      test_source3["business_name_normalized"].isna().sum())

print("Missing normalized business addresses:",
      test_source3["business_address_normalized"].isna().sum())

print("Empty normalized business names:",
      (test_source3["business_name_normalized"].fillna("") == "").sum())

print("Empty normalized business addresses:",
      (test_source3["business_address_normalized"].fillna("") == "").sum())

Missing normalized business names: 59
Missing normalized business addresses: 136098
Empty normalized business names: 59
Empty normalized business addresses: 136098

In [ ]:
print("===== FINAL VALIDATION: TEST SOURCE 3 =====")

print("\nShape:")
print(test_source3.shape)

print("\nMissing values:")
print(test_source3[
    ["entity_id", "business_name", "business_address", "country"]
].isna().sum())

print("\nDuplicate entity IDs:")
print(test_source3["entity_id"].duplicated().sum())

print("\nControl characters after cleaning:")
print(
    "Business names   :",
    test_source3["business_name_clean"].apply(has_control_char).sum()
)
print(
    "Business addresses:",
    test_source3["business_address_clean"].apply(has_control_char).sum()
)

print("\nWhitespace issues after cleaning:")
print(
    "Business names   :",
    test_source3["business_name_clean"].apply(has_whitespace_issue).sum()
)
print(
    "Business addresses:",
    test_source3["business_address_clean"].apply(has_whitespace_issue).sum()
)

print("\nNormalized empty values:")
print(
    "Business names   :",
    (test_source3["business_name_normalized"].fillna("") == "").sum()
)
print(
    "Business addresses:",
    (test_source3["business_address_normalized"].fillna("") == "").sum()
)

print("\nCountries:")
print(test_source3["country"].value_counts())

===== FINAL VALIDATION: TEST SOURCE 3 =====

Shape:
(5082316, 8)

Missing values:
entity_id                0
business_name           59
business_address    136098
country                  0
dtype: int64

Duplicate entity IDs:
0

Control characters after cleaning:
Business names   : 0
Business addresses: 0

Whitespace issues after cleaning:
Business names   : 0
Business addresses: 0

Normalized empty values:
Business names   : 59
Business addresses: 136098

Countries:
country
India     2405000
US        1945701
France     731615
Name: count, dtype: int64

In [ ]:
output_path = "/content/drive/MyDrive/Business_model_amazon/cleaned_data"

import os
os.makedirs(output_path, exist_ok=True)

In [ ]:
train_source1.to_csv(
    output_path + "/train_source1_cleaned.tsv",
    sep="\t",
    index=False
)

train_source2.to_csv(
    output_path + "/train_source2_cleaned.tsv",
    sep="\t",
    index=False
)

train_source3.to_csv(
    output_path + "/train_source3_cleaned.tsv",
    sep="\t",
    index=False
)

test_source1.to_csv(
    output_path + "/test_source1_cleaned.tsv",
    sep="\t",
    index=False
)

test_source2.to_csv(
    output_path + "/test_source2_cleaned.tsv",
    sep="\t",
    index=False
)

test_source3.to_csv(
    output_path + "/test_source3_cleaned.tsv",
    sep="\t",
    index=False
)

NameError: name 'train_source1' is not defined

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
base_path = "/content/drive/MyDrive/Business_model_amazon/extracted_data/student_resource/dataset"

output_path = "/content/drive/MyDrive/Business_model_amazon/cleaned_data"

import os
os.makedirs(output_path, exist_ok=True)

In [ ]:
import os

print(os.listdir(base_path + "/train"))
print(os.listdir(base_path + "/test"))

['train_ground_truth.tsv', 'train_source2.tsv', 'train_source3.tsv', 'train_source1.tsv']
['test_source2.tsv', 'test_source3.tsv', 'test_source1.tsv']

In [ ]:
import pandas as pd
import re
import unicodedata
import os

def clean_control_chars(text):
    if pd.isna(text):
        return text

    text = str(text)
    text = re.sub(r"[\x00-\x1F\x7F]", " ", text)
    text = re.sub(r"\s+", " ", text)

    return text.strip()


def normalize_unicode_text(text):
    if pd.isna(text):
        return text

    text = str(text).lower()
    text = unicodedata.normalize("NFKC", text)

    result = []

    for char in text:
        category = unicodedata.category(char)

        if category[0] in ("L", "N", "M"):
            result.append(char)
        else:
            result.append(" ")

    text = "".join(result)
    text = re.sub(r"\s+", " ", text).strip()

    return text


def repair_mojibake(text):
    if pd.isna(text):
        return text

    text = str(text)

    replacements = {
        "Â\x80\x93": "–",
        "Â\x80\x99": "’",
        "Â\x80\x98": "‘",
        "Â\x80\x90": "‐",
        "â\x80\x93": "–",
        "â\x80\x99": "’",
        "â\x80\x98": "‘",
        "â\x80\x90": "‐"
    }

    for bad, good in replacements.items():
        text = text.replace(bad, good)

    return text

In [ ]:
def clean_dataset(df):

    # Repair confirmed mojibake
    df["business_name_clean"] = (
        df["business_name"].apply(repair_mojibake)
    )

    df["business_address_clean"] = (
        df["business_address"].apply(repair_mojibake)
    )

    # Remove control characters and normalize whitespace
    df["business_name_clean"] = (
        df["business_name_clean"].apply(clean_control_chars)
    )

    df["business_address_clean"] = (
        df["business_address_clean"].apply(clean_control_chars)
    )

    # Unicode-aware normalization
    df["business_name_normalized"] = (
        df["business_name_clean"].apply(normalize_unicode_text)
    )

    df["business_address_normalized"] = (
        df["business_address_clean"].apply(normalize_unicode_text)
    )

    return df

In [ ]:
train_source1 = pd.read_csv(
    base_path + "/train/train_source1.tsv",
    sep="\t"
)

train_source1 = clean_dataset(train_source1)

train_source1.to_csv(
    output_path + "/train_source1_cleaned.tsv",
    sep="\t",
    index=False
)

print("Training Source 1 saved.")
print(train_source1.shape)

Training Source 1 saved.
(2206821, 8)

In [ ]:
del train_source1

import gc
gc.collect()

print("Training Source 1 removed from RAM.")

Training Source 1 removed from RAM.

In [ ]:
train_source2 = pd.read_csv(
    base_path + "/train/train_source2.tsv",
    sep="\t"
)

print("Loaded:", train_source2.shape)

train_source2 = clean_dataset(train_source2)

train_source2.to_csv(
    output_path + "/train_source2_cleaned.tsv",
    sep="\t",
    index=False
)

print("Training Source 2 saved.")
print(train_source2.shape)

Loaded: (5034616, 4)

KeyboardInterrupt:

In [ ]:
del train_source1

import gc
gc.collect()

print("Memory cleanup completed.")

NameError: name 'train_source1' is not defined

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
base_path = "/content/drive/MyDrive/Business_model_amazon/extracted_data/student_resource/dataset"
output_path = "/content/drive/MyDrive/Business_model_amazon/cleaned_data"

import os
os.makedirs(output_path, exist_ok=True)

print("Drive and paths ready.")

Drive and paths ready.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
base_path = "/content/drive/MyDrive/Business_model_amazon/extracted_data/student_resource/dataset"
output_path = "/content/drive/MyDrive/Business_model_amazon/cleaned_data"

import os
os.makedirs(output_path, exist_ok=True)

print("Paths ready.")

Paths ready.

In [ ]:
import pandas as pd
import re
import unicodedata
import gc

def clean_control_chars(text):
    if pd.isna(text):
        return text

    text = str(text)
    text = re.sub(r"[\x00-\x1F\x7F]", " ", text)
    text = re.sub(r"\s+", " ", text)

    return text.strip()


def repair_mojibake(text):
    if pd.isna(text):
        return text

    text = str(text)

    replacements = {
        "Â\x80\x93": "–",
        "Â\x80\x99": "’",
        "Â\x80\x98": "‘",
        "Â\x80\x90": "‐",
        "â\x80\x93": "–",
        "â\x80\x99": "’",
        "â\x80\x98": "‘",
        "â\x80\x90": "‐"
    }

    for bad, good in replacements.items():
        text = text.replace(bad, good)

    return text


def normalize_unicode_text(text):
    if pd.isna(text):
        return text

    text = str(text).lower()
    text = unicodedata.normalize("NFKC", text)

    result = []

    for char in text:
        category = unicodedata.category(char)

        if category[0] in ("L", "N", "M"):
            result.append(char)
        else:
            result.append(" ")

    text = "".join(result)
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [ ]:
def clean_chunk(df):

    df["business_name_clean"] = (
        df["business_name"]
        .apply(repair_mojibake)
        .apply(clean_control_chars)
    )

    df["business_address_clean"] = (
        df["business_address"]
        .apply(repair_mojibake)
        .apply(clean_control_chars)
    )

    df["business_name_normalized"] = (
        df["business_name_clean"]
        .apply(normalize_unicode_text)
    )

    df["business_address_normalized"] = (
        df["business_address_clean"]
        .apply(normalize_unicode_text)
    )

    return df

In [ ]:
input_file = base_path + "/train/train_source2.tsv"
output_file = output_path + "/train_source2_cleaned.tsv"

chunk_size = 250_000

# Remove old output if it exists
if os.path.exists(output_file):
    os.remove(output_file)

first_chunk = True
total_rows = 0

for chunk in pd.read_csv(
    input_file,
    sep="\t",
    chunksize=chunk_size
):

    # Clean this chunk
    chunk = clean_chunk(chunk)

    # Write to output
    chunk.to_csv(
        output_file,
        sep="\t",
        index=False,
        mode="w" if first_chunk else "a",
        header=first_chunk
    )

    total_rows += len(chunk)

    print(f"Processed: {total_rows:,} rows")

    # Free chunk memory
    del chunk
    gc.collect()

print("\nTraining Source 2 cleaning completed.")
print("Total rows:", total_rows)
print("Saved to:", output_file)

Processed: 250,000 rows
Processed: 500,000 rows
Processed: 750,000 rows
Processed: 1,000,000 rows
Processed: 1,250,000 rows
Processed: 1,500,000 rows
Processed: 1,750,000 rows
Processed: 2,000,000 rows
Processed: 2,250,000 rows
Processed: 2,500,000 rows
Processed: 2,750,000 rows
Processed: 3,000,000 rows
Processed: 3,250,000 rows
Processed: 3,500,000 rows
Processed: 3,750,000 rows
Processed: 4,000,000 rows
Processed: 4,250,000 rows
Processed: 4,500,000 rows
Processed: 4,750,000 rows
Processed: 5,000,000 rows
Processed: 5,034,616 rows

Training Source 2 cleaning completed.
Total rows: 5034616
Saved to: /content/drive/MyDrive/Business_model_amazon/cleaned_data/train_source2_cleaned.tsv

In [ ]:
# Validate cleaned Training Source 2

cleaned_s2 = pd.read_csv(
    output_path + "/train_source2_cleaned.tsv",
    sep="\t"
)

print("Shape:", cleaned_s2.shape)

print("\nColumns:")
print(cleaned_s2.columns.tolist())

print("\nMissing values:")
print(cleaned_s2.isna().sum())

print("\nDuplicate entity IDs:")
print(cleaned_s2["entity_id"].duplicated().sum())

print("\nEmpty normalized business names:")
print(
    cleaned_s2["business_name_normalized"]
    .fillna("")
    .str.strip()
    .eq("")
    .sum()
)

print("\nEmpty normalized business addresses:")
print(
    cleaned_s2["business_address_normalized"]
    .fillna("")
    .str.strip()
    .eq("")
    .sum()
)

del cleaned_s2
gc.collect()

Shape: (34616, 8)

Columns:
['entity_id', 'business_name', 'business_address', 'country', 'business_name_clean', 'business_address_clean', 'business_name_normalized', 'business_address_normalized']

Missing values:
entity_id                         0
business_name                     0
business_address               1193
country                           0
business_name_clean               0
business_address_clean         1193
business_name_normalized          0
business_address_normalized    1193
dtype: int64

Duplicate entity IDs:
0

Empty normalized business names:
0

Empty normalized business addresses:
1193

31

In [ ]:
import os
import pandas as pd
import gc

input_file = base_path + "/train/train_source2.tsv"
output_file = output_path + "/train_source2_cleaned.tsv"

chunk_size = 250_000

# Remove the incomplete output file
if os.path.exists(output_file):
    os.remove(output_file)

first_chunk = True
total_rows = 0

for chunk in pd.read_csv(
    input_file,
    sep="\t",
    chunksize=chunk_size
):

    # Clean this chunk
    chunk = clean_chunk(chunk)

    # Write first chunk with header,
    # append all remaining chunks
    chunk.to_csv(
        output_file,
        sep="\t",
        index=False,
        mode="w" if first_chunk else "a",
        header=first_chunk
    )

    total_rows += len(chunk)

    print(f"Processed: {total_rows:,} rows")

    # IMPORTANT: switch to append mode after first chunk
    first_chunk = False

    del chunk
    gc.collect()

print("\nTraining Source 2 cleaning completed.")
print("Total rows:", total_rows)
print("Saved to:", output_file)

Processed: 250,000 rows
Processed: 500,000 rows
Processed: 750,000 rows
Processed: 1,000,000 rows
Processed: 1,250,000 rows
Processed: 1,500,000 rows
Processed: 1,750,000 rows
Processed: 2,000,000 rows
Processed: 2,250,000 rows
Processed: 2,500,000 rows
Processed: 2,750,000 rows
Processed: 3,000,000 rows
Processed: 3,250,000 rows
Processed: 3,500,000 rows
Processed: 3,750,000 rows
Processed: 4,000,000 rows
Processed: 4,250,000 rows
Processed: 4,500,000 rows
Processed: 4,750,000 rows
Processed: 5,000,000 rows
Processed: 5,034,616 rows

Training Source 2 cleaning completed.
Total rows: 5034616
Saved to: /content/drive/MyDrive/Business_model_amazon/cleaned_data/train_source2_cleaned.tsv

In [ ]:
input_file = base_path + "/train/train_source3.tsv"
output_file = output_path + "/train_source3_cleaned.tsv"

chunk_size = 250_000

if os.path.exists(output_file):
    os.remove(output_file)

first_chunk = True
total_rows = 0

for chunk in pd.read_csv(
    input_file,
    sep="\t",
    chunksize=chunk_size
):
    chunk = clean_chunk(chunk)

    chunk.to_csv(
        output_file,
        sep="\t",
        index=False,
        mode="w" if first_chunk else "a",
        header=first_chunk
    )

    total_rows += len(chunk)
    first_chunk = False

    print(f"Processed: {total_rows:,} rows")

    del chunk
    gc.collect()

print("\nTraining Source 3 cleaning completed.")
print("Total rows:", total_rows)
print("Saved to:", output_file)

Processed: 250,000 rows
Processed: 500,000 rows
Processed: 750,000 rows
Processed: 1,000,000 rows
Processed: 1,250,000 rows
Processed: 1,500,000 rows
Processed: 1,750,000 rows
Processed: 2,000,000 rows
Processed: 2,250,000 rows
Processed: 2,500,000 rows
Processed: 2,750,000 rows
Processed: 3,000,000 rows
Processed: 3,250,000 rows
Processed: 3,500,000 rows
Processed: 3,750,000 rows
Processed: 4,000,000 rows
Processed: 4,250,000 rows
Processed: 4,500,000 rows
Processed: 4,750,000 rows
Processed: 5,000,000 rows
Processed: 5,250,000 rows
Processed: 5,285,603 rows

Training Source 3 cleaning completed.
Total rows: 5285603
Saved to: /content/drive/MyDrive/Business_model_amazon/cleaned_data/train_source3_cleaned.tsv

In [ ]:
input_file = base_path + "/test/test_source1.tsv"
output_file = output_path + "/test_source1_cleaned.tsv"

chunk_size = 250_000

if os.path.exists(output_file):
    os.remove(output_file)

first_chunk = True
total_rows = 0

for chunk in pd.read_csv(
    input_file,
    sep="\t",
    chunksize=chunk_size
):
    chunk = clean_chunk(chunk)

    chunk.to_csv(
        output_file,
        sep="\t",
        index=False,
        mode="w" if first_chunk else "a",
        header=first_chunk
    )

    total_rows += len(chunk)
    first_chunk = False

    print(f"Processed: {total_rows:,} rows")

    del chunk
    gc.collect()

print("\nTest Source 1 cleaning completed.")
print("Total rows:", total_rows)
print("Saved to:", output_file)

Processed: 250,000 rows
Processed: 500,000 rows
Processed: 750,000 rows
Processed: 1,000,000 rows
Processed: 1,250,000 rows
Processed: 1,500,000 rows
Processed: 1,732,544 rows

Test Source 1 cleaning completed.
Total rows: 1732544
Saved to: /content/drive/MyDrive/Business_model_amazon/cleaned_data/test_source1_cleaned.tsv

In [ ]:
input_file = base_path + "/test/test_source2.tsv"
output_file = output_path + "/test_source2_cleaned.tsv"

chunk_size = 250_000

if os.path.exists(output_file):
    os.remove(output_file)

first_chunk = True
total_rows = 0

for chunk in pd.read_csv(
    input_file,
    sep="\t",
    chunksize=chunk_size
):
    chunk = clean_chunk(chunk)

    chunk.to_csv(
        output_file,
        sep="\t",
        index=False,
        mode="w" if first_chunk else "a",
        header=first_chunk
    )

    total_rows += len(chunk)
    first_chunk = False

    print(f"Processed: {total_rows:,} rows")

    del chunk
    gc.collect()

print("\nTest Source 2 cleaning completed.")
print("Total rows:", total_rows)
print("Saved to:", output_file)

Processed: 250,000 rows
Processed: 500,000 rows
Processed: 750,000 rows
Processed: 1,000,000 rows
Processed: 1,250,000 rows
Processed: 1,500,000 rows
Processed: 1,750,000 rows
Processed: 2,000,000 rows
Processed: 2,250,000 rows
Processed: 2,500,000 rows
Processed: 2,750,000 rows
Processed: 3,000,000 rows
Processed: 3,250,000 rows
Processed: 3,500,000 rows
Processed: 3,750,000 rows
Processed: 4,000,000 rows
Processed: 4,250,000 rows
Processed: 4,500,000 rows
Processed: 4,750,000 rows
Processed: 4,887,273 rows

Test Source 2 cleaning completed.
Total rows: 4887273
Saved to: /content/drive/MyDrive/Business_model_amazon/cleaned_data/test_source2_cleaned.tsv

In [ ]:
input_file = base_path + "/test/test_source3.tsv"
output_file = output_path + "/test_source3_cleaned.tsv"

chunk_size = 250_000

if os.path.exists(output_file):
    os.remove(output_file)

first_chunk = True
total_rows = 0

for chunk in pd.read_csv(
    input_file,
    sep="\t",
    chunksize=chunk_size
):
    chunk = clean_chunk(chunk)

    chunk.to_csv(
        output_file,
        sep="\t",
        index=False,
        mode="w" if first_chunk else "a",
        header=first_chunk
    )

    total_rows += len(chunk)
    first_chunk = False

    print(f"Processed: {total_rows:,} rows")

    del chunk
    gc.collect()

print("\nTest Source 3 cleaning completed.")
print("Total rows:", total_rows)
print("Saved to:", output_file)

Processed: 250,000 rows
Processed: 500,000 rows
Processed: 750,000 rows
Processed: 1,000,000 rows
Processed: 1,250,000 rows
Processed: 1,500,000 rows
Processed: 1,750,000 rows
Processed: 2,000,000 rows
Processed: 2,250,000 rows
Processed: 2,500,000 rows
Processed: 2,750,000 rows
Processed: 3,000,000 rows
Processed: 3,250,000 rows
Processed: 3,500,000 rows
Processed: 3,750,000 rows
Processed: 4,000,000 rows
Processed: 4,250,000 rows
Processed: 4,500,000 rows
Processed: 4,750,000 rows
Processed: 5,000,000 rows
Processed: 5,082,316 rows

Test Source 3 cleaning completed.
Total rows: 5082316
Saved to: /content/drive/MyDrive/Business_model_amazon/cleaned_data/test_source3_cleaned.tsv

In [ ]:
import os

for file in sorted(os.listdir(output_path)):
    if file.endswith(".tsv"):
        size_gb = os.path.getsize(output_path + "/" + file) / (1024**3)
        print(f"{file:35} {size_gb:.2f} GB")

test_source1_cleaned.tsv            0.42 GB
test_source3_cleaned.tsv            1.23 GB
train_source1_cleaned.tsv           0.51 GB
train_source2_cleaned.tsv           1.19 GB
train_source3_cleaned.tsv           0.82 GB

In [ ]:
import os

print("Files in cleaned_data:\n")

for f in sorted(os.listdir(output_path)):
    if f.endswith(".tsv"):
        print(f)

Files in cleaned_data:

test_source1_cleaned.tsv
train_source1_cleaned.tsv
train_source2_cleaned.tsv
train_source3_cleaned.tsv

In [ ]:
import os

test_path = base_path + "/test"

for f in ["test_source2.tsv", "test_source3.tsv"]:
    path = test_path + "/" + f
    print(f, "→", os.path.exists(path))

test_source2.tsv → True
test_source3.tsv → True

In [ ]:
import pandas as pd
import gc
import os

for filename in ["test_source2.tsv", "test_source3.tsv"]:

    input_file = base_path + "/test/" + filename
    output_file = output_path + "/" + filename.replace(".tsv", "_cleaned.tsv")

    print("\nProcessing:", filename)

    first_chunk = True
    total_rows = 0

    for chunk in pd.read_csv(
        input_file,
        sep="\t",
        chunksize=250_000,
        keep_default_na=True
    ):
        chunk = clean_chunk(chunk)

        chunk.to_csv(
            output_file,
            sep="\t",
            index=False,
            mode="w" if first_chunk else "a",
            header=first_chunk
        )

        total_rows += len(chunk)
        first_chunk = False

        del chunk
        gc.collect()

        print("Processed:", total_rows)

    print("DONE:", output_file)

Processing: test_source2.tsv
Processed: 250000
Processed: 500000
Processed: 750000
Processed: 1000000
Processed: 1250000
Processed: 1500000
Processed: 1750000
Processed: 2000000
Processed: 2250000
Processed: 2500000
Processed: 2750000
Processed: 3000000
Processed: 3250000
Processed: 3500000
Processed: 3750000
Processed: 4000000
Processed: 4250000
Processed: 4500000
Processed: 4750000
Processed: 4887273
DONE: /content/drive/MyDrive/Business_model_amazon/cleaned_data/test_source2_cleaned.tsv

Processing: test_source3.tsv
Processed: 250000
Processed: 500000
Processed: 750000
Processed: 1000000
Processed: 1250000
Processed: 1500000
Processed: 1750000
Processed: 2000000
Processed: 2250000
Processed: 2500000
Processed: 2750000
Processed: 3000000
Processed: 3250000
Processed: 3500000
Processed: 3750000
Processed: 4000000
Processed: 4250000
Processed: 4500000
Processed: 4750000
Processed: 5000000
Processed: 5082316
DONE: /content/drive/MyDrive/Business_model_amazon/cleaned_data/test_source3_cleaned.tsv

In [ ]:
import os

print("Files in cleaned_data:\n")

for f in sorted(os.listdir(output_path)):
    if f.endswith(".tsv"):
        print(f)

Files in cleaned_data:

test_source1_cleaned.tsv
test_source2_cleaned.tsv
train_source1_cleaned.tsv
train_source2_cleaned.tsv
train_source3_cleaned.tsv

In [ ]:
import os

target = "test_source3_cleaned.tsv"

matches = []

for root, dirs, files in os.walk(
    "/content/drive/MyDrive/Business_model_amazon"
):
    if target in files:
        matches.append(os.path.join(root, target))

print("Matches found:")
for path in matches:
    print(path)

Matches found:

In [ ]:
import pandas as pd
import gc
import os

input_file = base_path + "/test/test_source3.tsv"
output_file = output_path + "/test_source3_cleaned.tsv"

print("Processing:", input_file)

first_chunk = True
total_rows = 0

for chunk in pd.read_csv(
    input_file,
    sep="\t",
    chunksize=250_000,
    keep_default_na=True
):
    chunk = clean_chunk(chunk)

    chunk.to_csv(
        output_file,
        sep="\t",
        index=False,
        mode="w" if first_chunk else "a",
        header=first_chunk
    )

    total_rows += len(chunk)
    first_chunk = False

    del chunk
    gc.collect()

    print("Processed:", total_rows)

print("\nDONE:", output_file)
print("Expected rows:", 5_082_316)
print("Actual rows:", total_rows)

Processing: /content/drive/MyDrive/Business_model_amazon/extracted_data/student_resource/dataset/test/test_source3.tsv
Processed: 250000
Processed: 500000
Processed: 750000
Processed: 1000000
Processed: 1250000
Processed: 1500000
Processed: 1750000
Processed: 2000000
Processed: 2250000
Processed: 2500000
Processed: 2750000
Processed: 3000000
Processed: 3250000
Processed: 3500000
Processed: 3750000
Processed: 4000000
Processed: 4250000
Processed: 4500000
Processed: 4750000
Processed: 5000000
Processed: 5082316

DONE: /content/drive/MyDrive/Business_model_amazon/cleaned_data/test_source3_cleaned.tsv
Expected rows: 5082316
Actual rows: 5082316

In [ ]:
import os

print("Files in cleaned_data:\n")

for f in sorted(os.listdir(output_path)):
    if f.endswith(".tsv"):
        print(f)

Files in cleaned_data:

test_source1_cleaned.tsv
test_source2_cleaned.tsv
train_source1_cleaned.tsv
train_source2_cleaned.tsv
train_source3_cleaned.tsv

In [ ]:
import os

output_path = "/content/drive/MyDrive/Business_model_amazon/cleaned_data"

# Check whether the file exists somewhere under Business_model_amazon
for root, dirs, files in os.walk("/content/drive/MyDrive/Business_model_amazon"):
    if "test_source3_cleaned.tsv" in files:
        print("FOUND:")
        print(os.path.join(root, "test_source3_cleaned.tsv"))

In [ ]:
import pandas as pd
import os
import gc

# ============================================================
# PATHS
# ============================================================

input_file = "/content/drive/MyDrive/Business_model_amazon/extracted_data/student_resource/dataset/test/test_source3.tsv"

output_dir = "/content/drive/MyDrive/Business_model_amazon/cleaned_data"

temp_file = os.path.join(
    output_dir,
    "test_source3_cleaned_TEMP.tsv"
)

output_file = os.path.join(
    output_dir,
    "test_source3_cleaned.tsv"
)

EXPECTED_ROWS = 5_082_316
CHUNK_SIZE = 250_000

os.makedirs(output_dir, exist_ok=True)

# Remove old temporary file if it exists
if os.path.exists(temp_file):
    os.remove(temp_file)

print("Input file:")
print(input_file)

print("\nOutput file:")
print(output_file)

print("\nStarting cleaning...\n")

# ============================================================
# CHUNK-BY-CHUNK CLEANING
# ============================================================

first_chunk = True
total_rows = 0

for chunk_no, chunk in enumerate(
    pd.read_csv(
        input_file,
        sep="\t",
        chunksize=CHUNK_SIZE
    ),
    start=1
):

    # Apply the SAME cleaning function used previously
    chunk = clean_chunk(chunk)

    # Write chunk
    chunk.to_csv(
        temp_file,
        sep="\t",
        index=False,
        mode="w" if first_chunk else "a",
        header=first_chunk
    )

    total_rows += len(chunk)

    print(
        f"Chunk {chunk_no}: "
        f"{len(chunk):,} rows | "
        f"Total: {total_rows:,}"
    )

    first_chunk = False

    del chunk
    gc.collect()

# ============================================================
# VERIFY ROW COUNT
# ============================================================

print("\n----------------------------------------")
print("Cleaning finished.")
print("----------------------------------------")

print(f"Rows processed : {total_rows:,}")
print(f"Expected rows  : {EXPECTED_ROWS:,}")

if total_rows != EXPECTED_ROWS:
    raise ValueError(
        f"ROW COUNT ERROR! "
        f"Expected {EXPECTED_ROWS:,}, "
        f"but processed {total_rows:,}."
    )

print("\nRow count verification: PASSED")

# ============================================================
# VERIFY TEMP FILE
# ============================================================

if not os.path.exists(temp_file):
    raise FileNotFoundError(
        "Temporary cleaned file was not created."
    )

temp_size = os.path.getsize(temp_file)

print(f"Temporary file size: {temp_size / (1024**3):.2f} GB")

if temp_size == 0:
    raise ValueError("Temporary file is empty.")

# ============================================================
# MOVE TEMP FILE TO FINAL FILE
# ============================================================

if os.path.exists(output_file):
    os.remove(output_file)

os.rename(temp_file, output_file)

print("\nFinal file created successfully.")

# ============================================================
# FINAL VERIFICATION
# ============================================================

if not os.path.exists(output_file):
    raise FileNotFoundError(
        "Final test_source3_cleaned.tsv was not found."
    )

final_size = os.path.getsize(output_file)

print(f"Final file size: {final_size / (1024**3):.2f} GB")

# Verify the file can actually be opened
header = pd.read_csv(
    output_file,
    sep="\t",
    nrows=2
)

print("\nFinal file verification: PASSED")

print("\nColumns:")
print(list(header.columns))

print("\n========================================")
print("SUCCESS")
print("========================================")
print("test_source3_cleaned.tsv is ready.")
print(f"Rows: {total_rows:,}")
print(f"Path: {output_file}")

Input file:
/content/drive/MyDrive/Business_model_amazon/extracted_data/student_resource/dataset/test/test_source3.tsv

Output file:
/content/drive/MyDrive/Business_model_amazon/cleaned_data/test_source3_cleaned.tsv

Starting cleaning...

Chunk 1: 250,000 rows | Total: 250,000
Chunk 2: 250,000 rows | Total: 500,000
Chunk 3: 250,000 rows | Total: 750,000
Chunk 4: 250,000 rows | Total: 1,000,000
Chunk 5: 250,000 rows | Total: 1,250,000
Chunk 6: 250,000 rows | Total: 1,500,000
Chunk 7: 250,000 rows | Total: 1,750,000
Chunk 8: 250,000 rows | Total: 2,000,000
Chunk 9: 250,000 rows | Total: 2,250,000
Chunk 10: 250,000 rows | Total: 2,500,000
Chunk 11: 250,000 rows | Total: 2,750,000
Chunk 12: 250,000 rows | Total: 3,000,000
Chunk 13: 250,000 rows | Total: 3,250,000
Chunk 14: 250,000 rows | Total: 3,500,000
Chunk 15: 250,000 rows | Total: 3,750,000
Chunk 16: 250,000 rows | Total: 4,000,000
Chunk 17: 250,000 rows | Total: 4,250,000
Chunk 18: 250,000 rows | Total: 4,500,000
Chunk 19: 250,000 rows | Total: 4,750,000
Chunk 20: 250,000 rows | Total: 5,000,000
Chunk 21: 82,316 rows | Total: 5,082,316

----------------------------------------
Cleaning finished.
----------------------------------------
Rows processed : 5,082,316
Expected rows  : 5,082,316

Row count verification: PASSED
Temporary file size: 1.17 GB

Final file created successfully.
Final file size: 1.17 GB

Final file verification: PASSED

Columns:
['entity_id', 'business_name', 'business_address', 'country', 'business_name_clean', 'business_address_clean', 'business_name_normalized', 'business_address_normalized']

========================================
SUCCESS
========================================
test_source3_cleaned.tsv is ready.
Rows: 5,082,316
Path: /content/drive/MyDrive/Business_model_amazon/cleaned_data/test_source3_cleaned.tsv

In [ ]:
import os

print("Files in cleaned_data:\n")

for f in sorted(os.listdir(output_dir)):
    if f.endswith(".tsv"):
        print(f)

Files in cleaned_data:

test_source1_cleaned.tsv
test_source2_cleaned.tsv
test_source3_cleaned.tsv
train_source1_cleaned.tsv
train_source2_cleaned.tsv
train_source3_cleaned.tsv

In [ ]:
import pandas as pd
import os
import gc

# ============================================================
# PATHS
# ============================================================

input_file = "/content/drive/MyDrive/Business_model_amazon/extracted_data/student_resource/dataset/train/train_source2.tsv"

output_dir = "/content/drive/MyDrive/Business_model_amazon/cleaned_data"

output_file = os.path.join(
    output_dir,
    "train_source2_cleaned.tsv"
)

temp_file = os.path.join(
    output_dir,
    "train_source2_cleaned_TEMP.tsv"
)

EXPECTED_ROWS = 5_034_616
CHUNK_SIZE = 250_000

os.makedirs(output_dir, exist_ok=True)

# Remove old temporary file
if os.path.exists(temp_file):
    os.remove(temp_file)

print("Input:")
print(input_file)

print("\nOutput:")
print(output_file)

print("\nStarting Train Source 2 cleaning...\n")

# ============================================================
# PROCESS ALL CHUNKS
# ============================================================

first_chunk = True
total_rows = 0

for chunk_no, chunk in enumerate(
    pd.read_csv(
        input_file,
        sep="\t",
        chunksize=CHUNK_SIZE
    ),
    start=1
):

    # Apply the same cleaning function
    chunk = clean_chunk(chunk)

    # First chunk creates the file.
    # All later chunks APPEND to it.
    if first_chunk:
        mode = "w"
        header = True
    else:
        mode = "a"
        header = False

    chunk.to_csv(
        temp_file,
        sep="\t",
        index=False,
        mode=mode,
        header=header
    )

    total_rows += len(chunk)

    print(
        f"Chunk {chunk_no}: "
        f"{len(chunk):,} rows | "
        f"Total: {total_rows:,}"
    )

    # VERY IMPORTANT
    first_chunk = False

    del chunk
    gc.collect()

# ============================================================
# ROW COUNT CHECK
# ============================================================

print("\n----------------------------------------")
print("Processing finished")
print("----------------------------------------")

print(f"Rows processed : {total_rows:,}")
print(f"Expected rows  : {EXPECTED_ROWS:,}")

if total_rows != EXPECTED_ROWS:
    raise ValueError(
        f"ERROR: Expected {EXPECTED_ROWS:,} rows "
        f"but processed {total_rows:,} rows."
    )

print("\nRow count check: PASSED")

# ============================================================
# CHECK TEMP FILE
# ============================================================

if not os.path.exists(temp_file):
    raise FileNotFoundError("Temporary file was not created.")

temp_size = os.path.getsize(temp_file)

print(
    f"Temporary file size: "
    f"{temp_size / (1024**3):.2f} GB"
)

# ============================================================
# REPLACE OLD BAD FILE
# ============================================================

if os.path.exists(output_file):
    os.remove(output_file)

os.rename(temp_file, output_file)

print("\nOld incorrect file replaced.")

# ============================================================
# FINAL VERIFICATION
# ============================================================

if not os.path.exists(output_file):
    raise FileNotFoundError(
        "Final cleaned file was not created."
    )

final_size = os.path.getsize(output_file)

print(
    f"Final file size: "
    f"{final_size / (1024**3):.2f} GB"
)

# Check that the file can actually be opened
check = pd.read_csv(
    output_file,
    sep="\t",
    nrows=2
)

print("\nColumns:")
print(list(check.columns))

print("\n========================================")
print("SUCCESS")
print("========================================")
print("train_source2_cleaned.tsv regenerated.")
print(f"Rows: {total_rows:,}")

Input:
/content/drive/MyDrive/Business_model_amazon/extracted_data/student_resource/dataset/train/train_source2.tsv

Output:
/content/drive/MyDrive/Business_model_amazon/cleaned_data/train_source2_cleaned.tsv

Starting Train Source 2 cleaning...

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Business_model_amazon/extracted_data/student_resource/dataset/train/train_source2.tsv'

In [ ]:
import os

search_root = "/content/drive/MyDrive/Business_model_amazon"

print("Searching for train_source2.tsv...\n")

found = []

for root, dirs, files in os.walk(search_root):
    if "train_source2.tsv" in files:
        path = os.path.join(root, "train_source2.tsv")
        found.append(path)

if found:
    print("FOUND:")
    for path in found:
        print(path)
else:
    print("NOT FOUND anywhere under:")
    print(search_root)

Searching for train_source2.tsv...

NOT FOUND anywhere under:
/content/drive/MyDrive/Business_model_amazon

In [ ]:
import os

zip_file = "/content/drive/MyDrive/Business_model_amazon/6ab10eb3b23ba_student_resource.zip"

if os.path.exists(zip_file):
    size_gb = os.path.getsize(zip_file) / (1024**3)
    print("ZIP FOUND ✅")
    print(f"Size: {size_gb:.2f} GB")
else:
    print("ZIP NOT FOUND ❌")

ZIP NOT FOUND ❌

In [ ]:
import os

search_root = "/content/drive/MyDrive"

targets = {
    "train_source2.tsv",
    "6ab10eb3b23ba_student_resource.zip"
}

found = []

print("Searching entire My Drive...\n")

for root, dirs, files in os.walk(search_root):
    for file in files:
        if file in targets:
            path = os.path.join(root, file)
            found.append(path)
            print("FOUND:", path)

print("\n--------------------------------")

if not found:
    print("Neither file was found anywhere in My Drive.")
else:
    print(f"Found {len(found)} matching file(s).")

Searching entire My Drive...


--------------------------------
Neither file was found anywhere in My Drive.

In [ ]:
import pandas as pd
import os
import gc

# ============================================================
# PATHS
# ============================================================

input_file = "/content/drive/MyDrive/Business_model_amazon/extracted_data/student_resource/dataset/train/train_source2.tsv"

output_dir = "/content/drive/MyDrive/Business_model_amazon/cleaned_data"

temp_file = os.path.join(
    output_dir,
    "train_source2_cleaned_TEMP.tsv"
)

output_file = os.path.join(
    output_dir,
    "train_source2_cleaned.tsv"
)

EXPECTED_ROWS = 5_034_616
CHUNK_SIZE = 250_000

os.makedirs(output_dir, exist_ok=True)

# Remove old temporary file
if os.path.exists(temp_file):
    os.remove(temp_file)

print("Starting Train Source 2 cleaning...")
print("Expected rows:", f"{EXPECTED_ROWS:,}")
print()

# ============================================================
# PROCESS ALL CHUNKS
# ============================================================

first_chunk = True
total_rows = 0

for chunk_no, chunk in enumerate(
    pd.read_csv(
        input_file,
        sep="\t",
        chunksize=CHUNK_SIZE
    ),
    start=1
):

    chunk = clean_chunk(chunk)

    chunk.to_csv(
        temp_file,
        sep="\t",
        index=False,
        mode="w" if first_chunk else "a",
        header=first_chunk
    )

    total_rows += len(chunk)

    print(
        f"Chunk {chunk_no}: "
        f"{len(chunk):,} rows | "
        f"Total: {total_rows:,}"
    )

    # ⭐ VERY IMPORTANT
    first_chunk = False

    del chunk
    gc.collect()

# ============================================================
# VERIFY ROW COUNT
# ============================================================

print("\n----------------------------------------")
print("PROCESSING COMPLETE")
print("----------------------------------------")

print(f"Rows processed : {total_rows:,}")
print(f"Expected rows  : {EXPECTED_ROWS:,}")

if total_rows != EXPECTED_ROWS:
    raise ValueError(
        f"ERROR: Expected {EXPECTED_ROWS:,} rows "
        f"but got {total_rows:,}"
    )

print("Row count verification: PASSED")

# ============================================================
# VERIFY TEMP FILE
# ============================================================

if not os.path.exists(temp_file):
    raise FileNotFoundError("Temporary file was not created.")

temp_size = os.path.getsize(temp_file)

print(f"Temporary file size: {temp_size / (1024**3):.2f} GB")

# ============================================================
# REPLACE OLD INCORRECT FILE
# ============================================================

if os.path.exists(output_file):
    os.remove(output_file)

os.rename(temp_file, output_file)

print("\nFinal cleaned file created.")

# ============================================================
# FINAL VERIFICATION
# ============================================================

if not os.path.exists(output_file):
    raise FileNotFoundError(
        "Final train_source2_cleaned.tsv was not created."
    )

print(f"Final file size: {os.path.getsize(output_file) / (1024**3):.2f} GB")

# Test that the file can be opened
test = pd.read_csv(
    output_file,
    sep="\t",
    nrows=2
)

print("\nColumns:")
print(list(test.columns))

print("\n========================================")
print("SUCCESS")
print("========================================")
print("train_source2_cleaned.tsv is CORRECT")
print(f"Rows: {total_rows:,}")

Starting Train Source 2 cleaning...
Expected rows: 5,034,616

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Business_model_amazon/extracted_data/student_resource/dataset/train/train_source2.tsv'

In [ ]:
import pandas as pd
import os
import gc

# ============================================================
# CORRECT PATHS
# ============================================================

input_file = "/content/drive/MyDrive/Business_model_amazon/extracted_data/student_resource/dataset/train_source2.tsv"

output_dir = "/content/drive/MyDrive/Business_model_amazon/cleaned_data"

temp_file = os.path.join(
    output_dir,
    "train_source2_cleaned_TEMP.tsv"
)

output_file = os.path.join(
    output_dir,
    "train_source2_cleaned.tsv"
)

EXPECTED_ROWS = 5_034_616
CHUNK_SIZE = 250_000

os.makedirs(output_dir, exist_ok=True)

# Check input first
if not os.path.exists(input_file):
    raise FileNotFoundError(
        "Original train_source2.tsv was not found at:\n"
        + input_file
    )

print("Input file FOUND:")
print(input_file)

print("\nStarting Train Source 2 cleaning...")
print(f"Expected rows: {EXPECTED_ROWS:,}\n")

# Remove old temporary file
if os.path.exists(temp_file):
    os.remove(temp_file)

# ============================================================
# PROCESS ALL ROWS
# ============================================================

first_chunk = True
total_rows = 0

for chunk_no, chunk in enumerate(
    pd.read_csv(
        input_file,
        sep="\t",
        chunksize=CHUNK_SIZE
    ),
    start=1
):

    chunk = clean_chunk(chunk)

    chunk.to_csv(
        temp_file,
        sep="\t",
        index=False,
        mode="w" if first_chunk else "a",
        header=first_chunk
    )

    total_rows += len(chunk)

    print(
        f"Chunk {chunk_no}: "
        f"{len(chunk):,} rows | "
        f"Total: {total_rows:,}"
    )

    # IMPORTANT: prevents overwriting previous chunks
    first_chunk = False

    del chunk
    gc.collect()

# ============================================================
# VERIFY
# ============================================================

print("\n----------------------------------------")
print("PROCESSING COMPLETE")
print("----------------------------------------")

print(f"Rows processed : {total_rows:,}")
print(f"Expected rows  : {EXPECTED_ROWS:,}")

if total_rows != EXPECTED_ROWS:
    raise ValueError(
        f"ERROR: Expected {EXPECTED_ROWS:,} rows "
        f"but got {total_rows:,}"
    )

print("✅ Row count verification PASSED")

# ============================================================
# REPLACE OLD WRONG FILE
# ============================================================

if os.path.exists(output_file):
    os.remove(output_file)

os.rename(temp_file, output_file)

# ============================================================
# FINAL CHECK
# ============================================================

if not os.path.exists(output_file):
    raise FileNotFoundError(
        "Final cleaned file was not created."
    )

print("\n========================================")
print("SUCCESS")
print("========================================")
print("File:", output_file)
print(f"Rows: {total_rows:,}")
print(
    f"Size: {os.path.getsize(output_file) / (1024**3):.2f} GB"
)

# Check columns
check = pd.read_csv(
    output_file,
    sep="\t",
    nrows=2
)

print("\nColumns:")
print(list(check.columns))

print("\n✅ train_source2_cleaned.tsv is FIXED.")

FileNotFoundError: Original train_source2.tsv was not found at:
/content/drive/MyDrive/Business_model_amazon/extracted_data/student_resource/dataset/train_source2.tsv

In [ ]:
import os

search_root = "/content/drive/MyDrive/Business_model_amazon"

print("Searching for train_source2.tsv...\n")

found = []

for root, dirs, files in os.walk(search_root):
    if "train_source2.tsv" in files:
        found.append(os.path.join(root, "train_source2.tsv"))

if found:
    print("FOUND:\n")
    for path in found:
        print(path)
else:
    print("❌ train_source2.tsv was NOT found anywhere under:")
    print(search_root)

Searching for train_source2.tsv...

❌ train_source2.tsv was NOT found anywhere under:
/content/drive/MyDrive/Business_model_amazon

In [ ]:
import os

zip_path = "/content/drive/MyDrive/Business_model_amazon/6ab10eb3b23ba_student_resource.zip"

if os.path.exists(zip_path):
    print("✅ ZIP FOUND")
    print("Size:", f"{os.path.getsize(zip_path) / (1024**3):.2f} GB")
    print(zip_path)
else:
    print("❌ ZIP NOT FOUND")
    print(zip_path)

❌ ZIP NOT FOUND
/content/drive/MyDrive/Business_model_amazon/6ab10eb3b23ba_student_resource.zip

In [ ]:
import os

search_root = "/content/drive/MyDrive"

print("Searching entire My Drive...")
print("This may take a little time.\n")

zip_found = []
source_found = []

for root, dirs, files in os.walk(search_root):

    for file in files:

        if file == "6ab10eb3b23ba_student_resource.zip":
            zip_found.append(os.path.join(root, file))

        if file == "train_source2.tsv":
            source_found.append(os.path.join(root, file))


print("========================================")
print("SEARCH RESULTS")
print("========================================")

print("\nZIP FILES:")

if zip_found:
    for path in zip_found:
        print("✅", path)
else:
    print("❌ ZIP not found")


print("\nORIGINAL TRAIN SOURCE 2:")

if source_found:
    for path in source_found:
        print("✅", path)
else:
    print("❌ train_source2.tsv not found")

Searching entire My Drive...
This may take a little time.

========================================
SEARCH RESULTS
========================================

ZIP FILES:
❌ ZIP not found

ORIGINAL TRAIN SOURCE 2:
❌ train_source2.tsv not found

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os

root = "/content/drive/MyDrive/Business_model_amazon"

print("ZIP files found:\n")

for r, d, files in os.walk(root):
    for f in files:
        if f.lower().endswith(".zip"):
            print(os.path.join(r, f))

ZIP files found:

/content/drive/MyDrive/Business_model_amazon/6ab10eb3b23ba_student_resource.zip

In [ ]:
import zipfile
import os

zip_path = "/content/drive/MyDrive/Business_model_amazon/6ab10eb3b23ba_student_resource.zip"

extract_dir = "/content/drive/MyDrive/Business_model_amazon/recovered_train_source2"

os.makedirs(extract_dir, exist_ok=True)

target = "train_source2.tsv"

print("Searching ZIP for:", target)

with zipfile.ZipFile(zip_path, "r") as z:

    matches = [
        name for name in z.namelist()
        if name.endswith("/" + target) or name == target
    ]

    print("\nMatches found:")

    for name in matches:
        print(name)

    if not matches:
        raise FileNotFoundError(
            "train_source2.tsv was not found inside the ZIP."
        )

    source_name = matches[0]

    print("\nExtracting:")
    print(source_name)

    z.extract(source_name, extract_dir)

print("\nExtraction completed.")

# Find the extracted file
for root, dirs, files in os.walk(extract_dir):
    for file in files:
        if file == target:
            recovered_path = os.path.join(root, file)
            print("\n✅ FOUND:")
            print(recovered_path)

Searching ZIP for: train_source2.tsv

Matches found:
student_resource/dataset/train/train_source2.tsv

Extracting:
student_resource/dataset/train/train_source2.tsv

Extraction completed.

✅ FOUND:
/content/drive/MyDrive/Business_model_amazon/recovered_train_source2/student_resource/dataset/train/train_source2.tsv

In [ ]:
import pandas as pd
import os
import gc

# ============================================================
# PATHS
# ============================================================

input_file = "/content/drive/MyDrive/Business_model_amazon/recovered_train_source2/student_resource/dataset/train/train_source2.tsv"

output_dir = "/content/drive/MyDrive/Business_model_amazon/cleaned_data"

temp_file = os.path.join(
    output_dir,
    "train_source2_cleaned_TEMP.tsv"
)

output_file = os.path.join(
    output_dir,
    "train_source2_cleaned.tsv"
)

EXPECTED_ROWS = 5_034_616
CHUNK_SIZE = 250_000

os.makedirs(output_dir, exist_ok=True)

# ============================================================
# CHECK INPUT
# ============================================================

if not os.path.exists(input_file):
    raise FileNotFoundError(
        f"Original file not found:\n{input_file}"
    )

print("✅ Original Train Source 2 found")
print(f"Expected rows: {EXPECTED_ROWS:,}")
print()

# Remove old temporary file if present
if os.path.exists(temp_file):
    os.remove(temp_file)

# ============================================================
# CLEAN ALL CHUNKS
# ============================================================

first_chunk = True
total_rows = 0

for chunk_no, chunk in enumerate(
    pd.read_csv(
        input_file,
        sep="\t",
        chunksize=CHUNK_SIZE
    ),
    start=1
):

    # Apply our existing cleaning function
    chunk = clean_chunk(chunk)

    # First chunk creates file.
    # Every following chunk is APPENDED.
    chunk.to_csv(
        temp_file,
        sep="\t",
        index=False,
        mode="w" if first_chunk else "a",
        header=first_chunk
    )

    total_rows += len(chunk)

    print(
        f"Chunk {chunk_no}: "
        f"{len(chunk):,} rows | "
        f"Total: {total_rows:,}"
    )

    # ⭐ CRITICAL LINE
    first_chunk = False

    del chunk
    gc.collect()

# ============================================================
# VERIFY ROW COUNT
# ============================================================

print("\n========================================")
print("PROCESSING COMPLETE")
print("========================================")

print(f"Rows processed : {total_rows:,}")
print(f"Expected rows  : {EXPECTED_ROWS:,}")

if total_rows != EXPECTED_ROWS:
    raise ValueError(
        f"❌ ROW COUNT ERROR: "
        f"Expected {EXPECTED_ROWS:,}, "
        f"got {total_rows:,}"
    )

print("✅ Row count verification PASSED")

# ============================================================
# VERIFY TEMP FILE
# ============================================================

if not os.path.exists(temp_file):
    raise FileNotFoundError(
        "Temporary cleaned file was not created."
    )

temp_size = os.path.getsize(temp_file)

print(
    f"Temporary file size: "
    f"{temp_size / (1024**3):.2f} GB"
)

if temp_size == 0:
    raise ValueError("Temporary file is empty.")

# ============================================================
# REPLACE OLD INCORRECT FILE
# ============================================================

if os.path.exists(output_file):
    os.remove(output_file)

os.rename(temp_file, output_file)

# ============================================================
# FINAL VERIFICATION
# ============================================================

if not os.path.exists(output_file):
    raise FileNotFoundError(
        "Final cleaned Train Source 2 file was not created."
    )

final_size = os.path.getsize(output_file)

print("\nFinal file created successfully.")
print(
    f"Final file size: "
    f"{final_size / (1024**3):.2f} GB"
)

# Check that the file opens correctly
check = pd.read_csv(
    output_file,
    sep="\t",
    nrows=2
)

print("\nColumns:")
print(list(check.columns))

print("\n========================================")
print("SUCCESS")
print("========================================")
print("train_source2_cleaned.tsv is FIXED")
print(f"Rows: {total_rows:,}")
print("========================================")

✅ Original Train Source 2 found
Expected rows: 5,034,616

NameError: name 'clean_chunk' is not defined

In [ ]:
import pandas as pd
import re
import unicodedata
import os
import gc

# ============================================================
# 1. CLEANING FUNCTIONS
# ============================================================

def clean_control_chars(text):
    if pd.isna(text):
        return text

    text = str(text)

    # Remove ASCII control characters
    text = re.sub(r"[\x00-\x1F\x7F]", " ", text)

    # Normalize repeated spaces
    text = re.sub(r"\s+", " ", text)

    return text.strip()


def repair_mojibake(text):
    if pd.isna(text):
        return text

    text = str(text)

    # ONLY verified corruption patterns
    replacements = {
        "Â\x80\x93": "–",
        "Â\x80\x99": "’",
        "Â\x80\x98": "‘",
        "Â\x80\x90": "‐",
        "â\x80\x93": "–",
        "â\x80\x99": "’",
        "â\x80\x98": "‘",
        "â\x80\x90": "‐"
    }

    for bad, good in replacements.items():
        text = text.replace(bad, good)

    return text


def normalize_unicode_text(text):
    if pd.isna(text):
        return text

    text = str(text).lower()

    # Unicode compatibility normalization
    text = unicodedata.normalize("NFKC", text)

    result = []

    for char in text:

        category = unicodedata.category(char)

        # Keep letters, numbers and combining marks
        if category[0] in ("L", "N", "M"):
            result.append(char)
        else:
            result.append(" ")

    text = "".join(result)

    # Remove repeated spaces
    text = re.sub(r"\s+", " ", text)

    return text.strip()


def clean_chunk(df):

    # --------------------------------------------------------
    # Business name
    # --------------------------------------------------------

    df["business_name_clean"] = (
        df["business_name"]
        .apply(repair_mojibake)
        .apply(clean_control_chars)
    )

    # --------------------------------------------------------
    # Business address
    # --------------------------------------------------------

    df["business_address_clean"] = (
        df["business_address"]
        .apply(repair_mojibake)
        .apply(clean_control_chars)
    )

    # --------------------------------------------------------
    # Normalized business name
    # --------------------------------------------------------

    df["business_name_normalized"] = (
        df["business_name_clean"]
        .apply(normalize_unicode_text)
    )

    # --------------------------------------------------------
    # Normalized business address
    # --------------------------------------------------------

    df["business_address_normalized"] = (
        df["business_address_clean"]
        .apply(normalize_unicode_text)
    )

    return df


# ============================================================
# 2. FILE PATHS
# ============================================================

input_file = (
    "/content/drive/MyDrive/Business_model_amazon/"
    "recovered_train_source2/student_resource/dataset/train/"
    "train_source2.tsv"
)

output_dir = (
    "/content/drive/MyDrive/Business_model_amazon/"
    "cleaned_data"
)

temp_file = os.path.join(
    output_dir,
    "train_source2_cleaned_TEMP.tsv"
)

output_file = os.path.join(
    output_dir,
    "train_source2_cleaned.tsv"
)

EXPECTED_ROWS = 5_034_616
CHUNK_SIZE = 250_000

os.makedirs(output_dir, exist_ok=True)


# ============================================================
# 3. CHECK ORIGINAL FILE
# ============================================================

if not os.path.exists(input_file):
    raise FileNotFoundError(
        f"Original Train Source 2 not found:\n{input_file}"
    )

print("✅ Original Train Source 2 found")
print(f"Expected rows: {EXPECTED_ROWS:,}")
print()


# ============================================================
# 4. REMOVE OLD TEMP FILE
# ============================================================

if os.path.exists(temp_file):
    os.remove(temp_file)


# ============================================================
# 5. PROCESS ALL ROWS
# ============================================================

first_chunk = True
total_rows = 0

for chunk_no, chunk in enumerate(
    pd.read_csv(
        input_file,
        sep="\t",
        chunksize=CHUNK_SIZE
    ),
    start=1
):

    # Clean current chunk
    chunk = clean_chunk(chunk)

    # Write first chunk, append all remaining chunks
    chunk.to_csv(
        temp_file,
        sep="\t",
        index=False,
        mode="w" if first_chunk else "a",
        header=first_chunk
    )

    total_rows += len(chunk)

    print(
        f"Chunk {chunk_no}: "
        f"{len(chunk):,} rows | "
        f"Total: {total_rows:,}"
    )

    # ⭐ VERY IMPORTANT
    first_chunk = False

    del chunk
    gc.collect()


# ============================================================
# 6. VERIFY ROW COUNT
# ============================================================

print("\n========================================")
print("PROCESSING COMPLETE")
print("========================================")

print(f"Rows processed : {total_rows:,}")
print(f"Expected rows  : {EXPECTED_ROWS:,}")

if total_rows != EXPECTED_ROWS:

    raise ValueError(
        f"❌ ROW COUNT ERROR!\n"
        f"Expected: {EXPECTED_ROWS:,}\n"
        f"Got:      {total_rows:,}"
    )

print("✅ Row count verification PASSED")


# ============================================================
# 7. VERIFY TEMP FILE
# ============================================================

if not os.path.exists(temp_file):

    raise FileNotFoundError(
        "Temporary cleaned file was not created."
    )

temp_size = os.path.getsize(temp_file)

print(
    f"Temporary file size: "
    f"{temp_size / (1024**3):.2f} GB"
)


# ============================================================
# 8. REPLACE OLD INCORRECT FILE
# ============================================================

if os.path.exists(output_file):
    os.remove(output_file)

os.rename(
    temp_file,
    output_file
)


# ============================================================
# 9. FINAL VERIFICATION
# ============================================================

if not os.path.exists(output_file):

    raise FileNotFoundError(
        "Final cleaned file was not created."
    )

final_size = os.path.getsize(output_file)

print("\nFinal file created successfully.")

print(
    f"Final file size: "
    f"{final_size / (1024**3):.2f} GB"
)


# ============================================================
# 10. CHECK COLUMNS
# ============================================================

check = pd.read_csv(
    output_file,
    sep="\t",
    nrows=2
)

print("\nColumns:")
print(list(check.columns))


# ============================================================
# 11. SUCCESS
# ============================================================

print("\n========================================")
print("SUCCESS")
print("========================================")
print("train_source2_cleaned.tsv is FIXED")
print(f"Rows: {total_rows:,}")
print("========================================")

✅ Original Train Source 2 found
Expected rows: 5,034,616

Chunk 1: 250,000 rows | Total: 250,000
Chunk 2: 250,000 rows | Total: 500,000
Chunk 3: 250,000 rows | Total: 750,000
Chunk 4: 250,000 rows | Total: 1,000,000
Chunk 5: 250,000 rows | Total: 1,250,000
Chunk 6: 250,000 rows | Total: 1,500,000
Chunk 7: 250,000 rows | Total: 1,750,000
Chunk 8: 250,000 rows | Total: 2,000,000
Chunk 9: 250,000 rows | Total: 2,250,000
Chunk 10: 250,000 rows | Total: 2,500,000
Chunk 11: 250,000 rows | Total: 2,750,000
Chunk 12: 250,000 rows | Total: 3,000,000
Chunk 13: 250,000 rows | Total: 3,250,000
Chunk 14: 250,000 rows | Total: 3,500,000
Chunk 15: 250,000 rows | Total: 3,750,000
Chunk 16: 250,000 rows | Total: 4,000,000
Chunk 17: 250,000 rows | Total: 4,250,000
Chunk 18: 250,000 rows | Total: 4,500,000
Chunk 19: 250,000 rows | Total: 4,750,000
Chunk 20: 250,000 rows | Total: 5,000,000
Chunk 21: 34,616 rows | Total: 5,034,616

========================================
PROCESSING COMPLETE
========================================
Rows processed : 5,034,616
Expected rows  : 5,034,616
✅ Row count verification PASSED
Temporary file size: 1.19 GB

Final file created successfully.
Final file size: 1.19 GB

Columns:
['entity_id', 'business_name', 'business_address', 'country', 'business_name_clean', 'business_address_clean', 'business_name_normalized', 'business_address_normalized']

========================================
SUCCESS
========================================
train_source2_cleaned.tsv is FIXED
Rows: 5,034,616
========================================

In [ ]:
import os

output_dir = "/content/drive/MyDrive/Business_model_amazon/cleaned_data"

expected = {
    "train_source1_cleaned.tsv": 2_206_821,
    "train_source2_cleaned.tsv": 5_034_616,
    "train_source3_cleaned.tsv": 5_285_603,
    "test_source1_cleaned.tsv": 1_732_544,
    "test_source2_cleaned.tsv": 4_887_273,
    "test_source3_cleaned.tsv": 5_082_316
}

print("FINAL DATA CLEANING VERIFICATION\n")

all_passed = True

for filename, expected_rows in expected.items():

    path = os.path.join(output_dir, filename)

    if os.path.exists(path):

        actual_rows = sum(
            1 for _ in open(path, encoding="utf-8")
        ) - 1

        status = "✅ PASS" if actual_rows == expected_rows else "❌ WRONG"

        if actual_rows != expected_rows:
            all_passed = False

        print(
            f"{status} | {filename} | "
            f"{actual_rows:,} / {expected_rows:,}"
        )

    else:
        all_passed = False
        print(f"❌ MISSING | {filename}")

print("\n========================================")

if all_passed:
    print("🎉 ALL 6 FILES VERIFIED SUCCESSFULLY")
    print("✅ DATA CLEANING STAGE COMPLETE")
    print("⛔ STOP HERE — DO NOT START EDA YET")
else:
    print("❌ SOME FILES NEED ATTENTION")

print("========================================")

FINAL DATA CLEANING VERIFICATION

✅ PASS | train_source1_cleaned.tsv | 2,206,821 / 2,206,821
✅ PASS | train_source2_cleaned.tsv | 5,034,616 / 5,034,616
❌ WRONG | train_source3_cleaned.tsv | 3,535,602 / 5,285,603
✅ PASS | test_source1_cleaned.tsv | 1,732,544 / 1,732,544
✅ PASS | test_source2_cleaned.tsv | 4,887,273 / 4,887,273
❌ WRONG | test_source3_cleaned.tsv | 4,832,761 / 5,082,316

========================================
❌ SOME FILES NEED ATTENTION
========================================

In [ ]:
import os

paths = [
    "/content/drive/MyDrive/Business_model_amazon/extracted_data/student_resource/dataset/train/train_source3.tsv",
    "/content/drive/MyDrive/Business_model_amazon/extracted_data/student_resource/dataset/test/test_source3.tsv",
    "/content/drive/MyDrive/Business_model_amazon/recovered_train_source2/student_resource/dataset/train/train_source3.tsv",
    "/content/drive/MyDrive/Business_model_amazon/recovered_train_source2/student_resource/dataset/test/test_source3.tsv"
]

print("SOURCE 3 ORIGINAL FILE CHECK\n")

for path in paths:
    if os.path.exists(path):
        size_gb = os.path.getsize(path) / (1024**3)
        print(f"✅ FOUND | {size_gb:.2f} GB | {path}")
    else:
        print(f"❌ NOT FOUND | {path}")

SOURCE 3 ORIGINAL FILE CHECK

✅ FOUND | 0.47 GB | /content/drive/MyDrive/Business_model_amazon/extracted_data/student_resource/dataset/train/train_source3.tsv
✅ FOUND | 0.47 GB | /content/drive/MyDrive/Business_model_amazon/extracted_data/student_resource/dataset/test/test_source3.tsv
❌ NOT FOUND | /content/drive/MyDrive/Business_model_amazon/recovered_train_source2/student_resource/dataset/train/train_source3.tsv
❌ NOT FOUND | /content/drive/MyDrive/Business_model_amazon/recovered_train_source2/student_resource/dataset/test/test_source3.tsv

In [ ]:
import pandas as pd
import re
import unicodedata
import os
import gc

# ============================================================
# CLEANING FUNCTIONS
# ============================================================

def clean_control_chars(text):
    if pd.isna(text):
        return text

    text = str(text)
    text = re.sub(r"[\x00-\x1F\x7F]", " ", text)
    text = re.sub(r"\s+", " ", text)

    return text.strip()


def repair_mojibake(text):
    if pd.isna(text):
        return text

    text = str(text)

    replacements = {
        "Â\x80\x93": "–",
        "Â\x80\x99": "’",
        "Â\x80\x98": "‘",
        "Â\x80\x90": "‐",
        "â\x80\x93": "–",
        "â\x80\x99": "’",
        "â\x80\x98": "‘",
        "â\x80\x90": "‐"
    }

    for bad, good in replacements.items():
        text = text.replace(bad, good)

    return text


def normalize_unicode_text(text):
    if pd.isna(text):
        return text

    text = str(text).lower()
    text = unicodedata.normalize("NFKC", text)

    result = []

    for char in text:
        category = unicodedata.category(char)

        if category[0] in ("L", "N", "M"):
            result.append(char)
        else:
            result.append(" ")

    text = "".join(result)
    text = re.sub(r"\s+", " ", text)

    return text.strip()


def clean_chunk(df):

    df["business_name_clean"] = (
        df["business_name"]
        .apply(repair_mojibake)
        .apply(clean_control_chars)
    )

    df["business_address_clean"] = (
        df["business_address"]
        .apply(repair_mojibake)
        .apply(clean_control_chars)
    )

    df["business_name_normalized"] = (
        df["business_name_clean"]
        .apply(normalize_unicode_text)
    )

    df["business_address_normalized"] = (
        df["business_address_clean"]
        .apply(normalize_unicode_text)
    )

    return df


# ============================================================
# PATHS
# ============================================================

base_dir = "/content/drive/MyDrive/Business_model_amazon"

output_dir = os.path.join(
    base_dir,
    "cleaned_data"
)

os.makedirs(output_dir, exist_ok=True)


# ============================================================
# FILE INFORMATION
# ============================================================

files = {

    "train_source3": {
        "input": os.path.join(
            base_dir,
            "extracted_data/student_resource/dataset/train/"
            "train_source3.tsv"
        ),
        "output": os.path.join(
            output_dir,
            "train_source3_cleaned.tsv"
        ),
        "expected": 5_285_603
    },

    "test_source3": {
        "input": os.path.join(
            base_dir,
            "extracted_data/student_resource/dataset/test/"
            "test_source3.tsv"
        ),
        "output": os.path.join(
            output_dir,
            "test_source3_cleaned.tsv"
        ),
        "expected": 5_082_316
    }
}


# ============================================================
# PROCESS EACH FILE
# ============================================================

CHUNK_SIZE = 250_000

for name, info in files.items():

    input_file = info["input"]
    output_file = info["output"]
    expected_rows = info["expected"]

    temp_file = output_file.replace(
        ".tsv",
        "_TEMP.tsv"
    )

    print("\n")
    print("=" * 70)
    print(f"PROCESSING: {name}")
    print("=" * 70)

    # Check original file
    if not os.path.exists(input_file):
        raise FileNotFoundError(
            f"Original file not found:\n{input_file}"
        )

    print("✅ Original file found")
    print(f"Expected rows: {expected_rows:,}")

    # Remove old temporary file
    if os.path.exists(temp_file):
        os.remove(temp_file)

    first_chunk = True
    total_rows = 0

    # --------------------------------------------------------
    # READ + CLEAN IN CHUNKS
    # --------------------------------------------------------

    for chunk_no, chunk in enumerate(
        pd.read_csv(
            input_file,
            sep="\t",
            chunksize=CHUNK_SIZE
        ),
        start=1
    ):

        chunk = clean_chunk(chunk)

        chunk.to_csv(
            temp_file,
            sep="\t",
            index=False,
            mode="w" if first_chunk else "a",
            header=first_chunk
        )

        total_rows += len(chunk)

        print(
            f"Chunk {chunk_no}: "
            f"{len(chunk):,} rows | "
            f"Total: {total_rows:,}"
        )

        # IMPORTANT:
        # After first write, all later chunks append
        first_chunk = False

        del chunk
        gc.collect()

    # --------------------------------------------------------
    # VERIFY ROW COUNT
    # --------------------------------------------------------

    print("\n----------------------------------------")
    print("PROCESSING COMPLETE")
    print("----------------------------------------")

    print(f"Rows processed : {total_rows:,}")
    print(f"Expected rows  : {expected_rows:,}")

    if total_rows != expected_rows:

        print(
            "\n❌ ROW COUNT ERROR!"
        )

        print(
            "The existing cleaned file will NOT be replaced."
        )

        if os.path.exists(temp_file):
            os.remove(temp_file)

        raise ValueError(
            f"{name}: Expected {expected_rows:,} rows "
            f"but processed {total_rows:,}."
        )

    print("✅ Row count verification PASSED")

    # --------------------------------------------------------
    # CHECK TEMP FILE
    # --------------------------------------------------------

    if not os.path.exists(temp_file):
        raise FileNotFoundError(
            "Temporary cleaned file was not created."
        )

    temp_size = os.path.getsize(temp_file)

    print(
        f"Temporary file size: "
        f"{temp_size / (1024**3):.2f} GB"
    )

    # --------------------------------------------------------
    # REPLACE OLD FILE ONLY AFTER SUCCESS
    # --------------------------------------------------------

    if os.path.exists(output_file):
        os.remove(output_file)

    os.rename(
        temp_file,
        output_file
    )

    # --------------------------------------------------------
    # FINAL EXISTENCE CHECK
    # --------------------------------------------------------

    if not os.path.exists(output_file):
        raise FileNotFoundError(
            "Final cleaned file was not created."
        )

    final_size = os.path.getsize(output_file)

    print("\n✅ Final file created successfully")

    print(
        f"Final file size: "
        f"{final_size / (1024**3):.2f} GB"
    )

    # --------------------------------------------------------
    # COLUMN CHECK
    # --------------------------------------------------------

    check = pd.read_csv(
        output_file,
        sep="\t",
        nrows=2
    )

    print("\nColumns:")
    print(list(check.columns))

    print("\n✅", name, "REBUILD SUCCESSFUL")


# ============================================================
# FINAL MESSAGE
# ============================================================

print("\n")
print("=" * 70)
print("🎉 BOTH SOURCE 3 FILES REBUILT SUCCESSFULLY")
print("=" * 70)

print("Train Source 3:", 5_285_603)
print("Test Source 3 :", 5_082_316)

print("\n⛔ DO NOT START EDA YET")
print("Next step: verify all 6 cleaned files.")
print("=" * 70)

======================================================================
PROCESSING: train_source3
======================================================================
✅ Original file found
Expected rows: 5,285,603
Chunk 1: 250,000 rows | Total: 250,000
Chunk 2: 250,000 rows | Total: 500,000
Chunk 3: 250,000 rows | Total: 750,000
Chunk 4: 250,000 rows | Total: 1,000,000
Chunk 5: 250,000 rows | Total: 1,250,000
Chunk 6: 250,000 rows | Total: 1,500,000
Chunk 7: 250,000 rows | Total: 1,750,000
Chunk 8: 250,000 rows | Total: 2,000,000
Chunk 9: 250,000 rows | Total: 2,250,000
Chunk 10: 250,000 rows | Total: 2,500,000
Chunk 11: 250,000 rows | Total: 2,750,000
Chunk 12: 250,000 rows | Total: 3,000,000
Chunk 13: 250,000 rows | Total: 3,250,000
Chunk 14: 250,000 rows | Total: 3,500,000
Chunk 15: 250,000 rows | Total: 3,750,000
Chunk 16: 250,000 rows | Total: 4,000,000
Chunk 17: 250,000 rows | Total: 4,250,000
Chunk 18: 250,000 rows | Total: 4,500,000
Chunk 19: 250,000 rows | Total: 4,750,000
Chunk 20: 250,000 rows | Total: 5,000,000
Chunk 21: 250,000 rows | Total: 5,250,000
Chunk 22: 35,603 rows | Total: 5,285,603

----------------------------------------
PROCESSING COMPLETE
----------------------------------------
Rows processed : 5,285,603
Expected rows  : 5,285,603
✅ Row count verification PASSED
Temporary file size: 1.10 GB

✅ Final file created successfully
Final file size: 1.10 GB

Columns:
['entity_id', 'business_name', 'business_address', 'country', 'business_name_clean', 'business_address_clean', 'business_name_normalized', 'business_address_normalized']

✅ train_source3 REBUILD SUCCESSFUL


======================================================================
PROCESSING: test_source3
======================================================================
✅ Original file found
Expected rows: 5,082,316
Chunk 1: 250,000 rows | Total: 250,000
Chunk 2: 250,000 rows | Total: 500,000
Chunk 3: 250,000 rows | Total: 750,000
Chunk 4: 250,000 rows | Total: 1,000,000
Chunk 5: 250,000 rows | Total: 1,250,000
Chunk 6: 250,000 rows | Total: 1,500,000

OSError: [Errno 95] Operation not supported: '/content/drive/MyDrive/Business_model_amazon/cleaned_data/test_source3_cleaned_TEMP.tsv'

In [ ]:
import pandas as pd
import re
import unicodedata
import os
import gc
import shutil

# ============================================================
# CLEANING FUNCTIONS
# ============================================================

def clean_control_chars(text):
    if pd.isna(text):
        return text

    text = str(text)
    text = re.sub(r"[\x00-\x1F\x7F]", " ", text)
    text = re.sub(r"\s+", " ", text)

    return text.strip()


def repair_mojibake(text):
    if pd.isna(text):
        return text

    text = str(text)

    replacements = {
        "Â\x80\x93": "–",
        "Â\x80\x99": "’",
        "Â\x80\x98": "‘",
        "Â\x80\x90": "‐",
        "â\x80\x93": "–",
        "â\x80\x99": "’",
        "â\x80\x98": "‘",
        "â\x80\x90": "‐"
    }

    for bad, good in replacements.items():
        text = text.replace(bad, good)

    return text


def normalize_unicode_text(text):
    if pd.isna(text):
        return text

    text = str(text).lower()
    text = unicodedata.normalize("NFKC", text)

    result = []

    for char in text:
        category = unicodedata.category(char)

        if category[0] in ("L", "N", "M"):
            result.append(char)
        else:
            result.append(" ")

    text = "".join(result)
    text = re.sub(r"\s+", " ", text)

    return text.strip()


def clean_chunk(df):

    df["business_name_clean"] = (
        df["business_name"]
        .apply(repair_mojibake)
        .apply(clean_control_chars)
    )

    df["business_address_clean"] = (
        df["business_address"]
        .apply(repair_mojibake)
        .apply(clean_control_chars)
    )

    df["business_name_normalized"] = (
        df["business_name_clean"]
        .apply(normalize_unicode_text)
    )

    df["business_address_normalized"] = (
        df["business_address_clean"]
        .apply(normalize_unicode_text)
    )

    return df


# ============================================================
# PATHS
# ============================================================

base_dir = "/content/drive/MyDrive/Business_model_amazon"

input_file = (
    base_dir +
    "/extracted_data/student_resource/dataset/test/"
    "test_source3.tsv"
)

drive_output = (
    base_dir +
    "/cleaned_data/test_source3_cleaned.tsv"
)

# IMPORTANT:
# Write temporary file to LOCAL COLAB STORAGE,
# NOT directly to Google Drive.
local_temp = "/content/test_source3_cleaned_TEMP.tsv"

EXPECTED_ROWS = 5_082_316
CHUNK_SIZE = 250_000


# ============================================================
# CHECK ORIGINAL FILE
# ============================================================

if not os.path.exists(input_file):
    raise FileNotFoundError(
        f"Original Test Source 3 not found:\n{input_file}"
    )

print("✅ Original Test Source 3 found")
print(f"Expected rows: {EXPECTED_ROWS:,}")
print()


# ============================================================
# REMOVE OLD LOCAL TEMP FILE
# ============================================================

if os.path.exists(local_temp):
    os.remove(local_temp)

first_chunk = True
total_rows = 0


# ============================================================
# PROCESS IN CHUNKS
# ============================================================

for chunk_no, chunk in enumerate(
    pd.read_csv(
        input_file,
        sep="\t",
        chunksize=CHUNK_SIZE
    ),
    start=1
):

    chunk = clean_chunk(chunk)

    chunk.to_csv(
        local_temp,
        sep="\t",
        index=False,
        mode="w" if first_chunk else "a",
        header=first_chunk
    )

    total_rows += len(chunk)

    print(
        f"Chunk {chunk_no}: "
        f"{len(chunk):,} rows | "
        f"Total: {total_rows:,}"
    )

    first_chunk = False

    del chunk
    gc.collect()


# ============================================================
# VERIFY COMPLETE LOCAL FILE
# ============================================================

print("\n")
print("=" * 70)
print("LOCAL PROCESSING COMPLETE")
print("=" * 70)

print(f"Rows processed : {total_rows:,}")
print(f"Expected rows  : {EXPECTED_ROWS:,}")


if total_rows != EXPECTED_ROWS:

    print("\n❌ ROW COUNT ERROR")
    print("Google Drive file will NOT be replaced.")

    if os.path.exists(local_temp):
        os.remove(local_temp)

    raise ValueError(
        f"Expected {EXPECTED_ROWS:,} rows "
        f"but processed {total_rows:,}"
    )


print("✅ Row count verification PASSED")


# ============================================================
# CHECK LOCAL TEMP FILE
# ============================================================

if not os.path.exists(local_temp):
    raise FileNotFoundError(
        "Local temporary file was not created."
    )

local_size = os.path.getsize(local_temp)

print(
    f"Local temporary file size: "
    f"{local_size / (1024**3):.2f} GB"
)


# ============================================================
# VERIFY LOCAL FILE HEADER
# ============================================================

check = pd.read_csv(
    local_temp,
    sep="\t",
    nrows=2
)

expected_columns = [
    "entity_id",
    "business_name",
    "business_address",
    "country",
    "business_name_clean",
    "business_address_clean",
    "business_name_normalized",
    "business_address_normalized"
]

if list(check.columns) != expected_columns:

    raise ValueError(
        "❌ Column verification failed.\n"
        f"Got: {list(check.columns)}"
    )

print("✅ Column verification PASSED")


# ============================================================
# COPY COMPLETED FILE TO GOOGLE DRIVE
# ============================================================

print("\nCopying completed file to Google Drive...")
print("Please wait...")

# Remove the incomplete Drive file ONLY NOW,
# after local processing has fully passed verification.

if os.path.exists(drive_output):
    os.remove(drive_output)

shutil.copy2(
    local_temp,
    drive_output
)


# ============================================================
# VERIFY DRIVE FILE EXISTS
# ============================================================

if not os.path.exists(drive_output):
    raise FileNotFoundError(
        "❌ Final Drive file was not created."
    )

drive_size = os.path.getsize(drive_output)

print(
    f"Drive file size: "
    f"{drive_size / (1024**3):.2f} GB"
)


# ============================================================
# FINAL DRIVE ROW COUNT
# ============================================================

print("\nVerifying final Drive file row count...")

drive_rows = sum(
    1 for _ in open(
        drive_output,
        encoding="utf-8"
    )
) - 1

print(
    f"Drive rows    : {drive_rows:,}"
)

print(
    f"Expected rows : {EXPECTED_ROWS:,}"
)


if drive_rows != EXPECTED_ROWS:

    raise ValueError(
        f"❌ FINAL DRIVE ROW COUNT ERROR!\n"
        f"Expected: {EXPECTED_ROWS:,}\n"
        f"Got:      {drive_rows:,}"
    )


# ============================================================
# CLEAN UP LOCAL TEMP
# ============================================================

os.remove(local_temp)


# ============================================================
# SUCCESS
# ============================================================

print("\n")
print("=" * 70)
print("🎉 TEST SOURCE 3 REBUILD SUCCESSFUL")
print("=" * 70)

print(
    f"Rows: {drive_rows:,}"
)

print(
    "File: test_source3_cleaned.tsv"
)

print(
    "Location: Google Drive / cleaned_data"
)

print("\n⛔ DO NOT START EDA YET")
print("Next step: final verification of all 6 cleaned files.")
print("=" * 70)

✅ Original Test Source 3 found
Expected rows: 5,082,316

Chunk 1: 250,000 rows | Total: 250,000
Chunk 2: 250,000 rows | Total: 500,000
Chunk 3: 250,000 rows | Total: 750,000
Chunk 4: 250,000 rows | Total: 1,000,000
Chunk 5: 250,000 rows | Total: 1,250,000
Chunk 6: 250,000 rows | Total: 1,500,000
Chunk 7: 250,000 rows | Total: 1,750,000
Chunk 8: 250,000 rows | Total: 2,000,000
Chunk 9: 250,000 rows | Total: 2,250,000
Chunk 10: 250,000 rows | Total: 2,500,000
Chunk 11: 250,000 rows | Total: 2,750,000
Chunk 12: 250,000 rows | Total: 3,000,000
Chunk 13: 250,000 rows | Total: 3,250,000
Chunk 14: 250,000 rows | Total: 3,500,000
Chunk 15: 250,000 rows | Total: 3,750,000
Chunk 16: 250,000 rows | Total: 4,000,000
Chunk 17: 250,000 rows | Total: 4,250,000
Chunk 18: 250,000 rows | Total: 4,500,000
Chunk 19: 250,000 rows | Total: 4,750,000
Chunk 20: 250,000 rows | Total: 5,000,000
Chunk 21: 82,316 rows | Total: 5,082,316


======================================================================
LOCAL PROCESSING COMPLETE
======================================================================
Rows processed : 5,082,316
Expected rows  : 5,082,316
✅ Row count verification PASSED
Local temporary file size: 1.23 GB
✅ Column verification PASSED

Copying completed file to Google Drive...
Please wait...
Drive file size: 1.23 GB

Verifying final Drive file row count...
Drive rows    : 5,082,316
Expected rows : 5,082,316


======================================================================
🎉 TEST SOURCE 3 REBUILD SUCCESSFUL
======================================================================
Rows: 5,082,316
File: test_source3_cleaned.tsv
Location: Google Drive / cleaned_data

⛔ DO NOT START EDA YET
Next step: final verification of all 6 cleaned files.
======================================================================

In [ ]:
import os

output_dir = "/content/drive/MyDrive/Business_model_amazon/cleaned_data"

expected = {
    "train_source1_cleaned.tsv": 2_206_821,
    "train_source2_cleaned.tsv": 5_034_616,
    "train_source3_cleaned.tsv": 5_285_603,
    "test_source1_cleaned.tsv": 1_732_544,
    "test_source2_cleaned.tsv": 4_887_273,
    "test_source3_cleaned.tsv": 5_082_316
}

print("FINAL DATA CLEANING VERIFICATION\n")

all_passed = True

for filename, expected_rows in expected.items():

    path = os.path.join(output_dir, filename)

    if not os.path.exists(path):
        all_passed = False
        print(f"❌ MISSING | {filename}")
        continue

    actual_rows = sum(
        1 for _ in open(path, encoding="utf-8")
    ) - 1

    if actual_rows == expected_rows:
        print(
            f"✅ PASS | {filename} | "
            f"{actual_rows:,} / {expected_rows:,}"
        )
    else:
        all_passed = False
        print(
            f"❌ WRONG | {filename} | "
            f"{actual_rows:,} / {expected_rows:,}"
        )

print("\n" + "=" * 60)

if all_passed:
    print("🎉 ALL 6 FILES VERIFIED SUCCESSFULLY")
    print("✅ DATA CLEANING STAGE COMPLETE")
else:
    print("❌ SOME FILES NEED ATTENTION")

print("=" * 60)

FINAL DATA CLEANING VERIFICATION

✅ PASS | train_source1_cleaned.tsv | 2,206,821 / 2,206,821
✅ PASS | train_source2_cleaned.tsv | 5,034,616 / 5,034,616
❌ WRONG | train_source3_cleaned.tsv | 4,785,626 / 5,285,603
✅ PASS | test_source1_cleaned.tsv | 1,732,544 / 1,732,544
✅ PASS | test_source2_cleaned.tsv | 4,887,273 / 4,887,273
✅ PASS | test_source3_cleaned.tsv | 5,082,316 / 5,082,316

============================================================
❌ SOME FILES NEED ATTENTION
============================================================

In [ ]:
import pandas as pd
import re
import unicodedata
import os
import gc
import shutil

# ============================================================
# CLEANING FUNCTIONS
# ============================================================

def clean_control_chars(text):
    if pd.isna(text):
        return text

    text = str(text)
    text = re.sub(r"[\x00-\x1F\x7F]", " ", text)
    text = re.sub(r"\s+", " ", text)

    return text.strip()


def repair_mojibake(text):
    if pd.isna(text):
        return text

    text = str(text)

    replacements = {
        "Â\x80\x93": "–",
        "Â\x80\x99": "’",
        "Â\x80\x98": "‘",
        "Â\x80\x90": "‐",
        "â\x80\x93": "–",
        "â\x80\x99": "’",
        "â\x80\x98": "‘",
        "â\x80\x90": "‐"
    }

    for bad, good in replacements.items():
        text = text.replace(bad, good)

    return text


def normalize_unicode_text(text):
    if pd.isna(text):
        return text

    text = str(text).lower()
    text = unicodedata.normalize("NFKC", text)

    result = []

    for char in text:
        category = unicodedata.category(char)

        if category[0] in ("L", "N", "M"):
            result.append(char)
        else:
            result.append(" ")

    text = "".join(result)
    text = re.sub(r"\s+", " ", text)

    return text.strip()


def clean_chunk(df):

    df["business_name_clean"] = (
        df["business_name"]
        .apply(repair_mojibake)
        .apply(clean_control_chars)
    )

    df["business_address_clean"] = (
        df["business_address"]
        .apply(repair_mojibake)
        .apply(clean_control_chars)
    )

    df["business_name_normalized"] = (
        df["business_name_clean"]
        .apply(normalize_unicode_text)
    )

    df["business_address_normalized"] = (
        df["business_address_clean"]
        .apply(normalize_unicode_text)
    )

    return df


# ============================================================
# PATHS
# ============================================================

base_dir = "/content/drive/MyDrive/Business_model_amazon"

input_file = (
    base_dir +
    "/extracted_data/student_resource/dataset/train/"
    "train_source3.tsv"
)

drive_output = (
    base_dir +
    "/cleaned_data/train_source3_cleaned.tsv"
)

# Write temporary file locally
local_temp = "/content/train_source3_cleaned_TEMP.tsv"

EXPECTED_ROWS = 5_285_603
CHUNK_SIZE = 250_000


# ============================================================
# CHECK ORIGINAL
# ============================================================

if not os.path.exists(input_file):
    raise FileNotFoundError(
        f"Original Train Source 3 not found:\n{input_file}"
    )

print("✅ Original Train Source 3 found")
print(f"Expected rows: {EXPECTED_ROWS:,}")
print()


# ============================================================
# REMOVE OLD LOCAL TEMP
# ============================================================

if os.path.exists(local_temp):
    os.remove(local_temp)


# ============================================================
# PROCESS
# ============================================================

first_chunk = True
total_rows = 0

for chunk_no, chunk in enumerate(
    pd.read_csv(
        input_file,
        sep="\t",
        chunksize=CHUNK_SIZE
    ),
    start=1
):

    chunk = clean_chunk(chunk)

    chunk.to_csv(
        local_temp,
        sep="\t",
        index=False,
        mode="w" if first_chunk else "a",
        header=first_chunk
    )

    total_rows += len(chunk)

    print(
        f"Chunk {chunk_no}: "
        f"{len(chunk):,} rows | "
        f"Total: {total_rows:,}"
    )

    first_chunk = False

    del chunk
    gc.collect()


# ============================================================
# VERIFY LOCAL FILE
# ============================================================

print("\n")
print("=" * 70)
print("LOCAL PROCESSING COMPLETE")
print("=" * 70)

print(f"Rows processed : {total_rows:,}")
print(f"Expected rows  : {EXPECTED_ROWS:,}")

if total_rows != EXPECTED_ROWS:

    print("\n❌ ROW COUNT ERROR")
    print("Google Drive file will NOT be replaced.")

    if os.path.exists(local_temp):
        os.remove(local_temp)

    raise ValueError(
        f"Expected {EXPECTED_ROWS:,} rows "
        f"but processed {total_rows:,}"
    )

print("✅ Row count verification PASSED")


# ============================================================
# LOCAL FILE CHECK
# ============================================================

if not os.path.exists(local_temp):
    raise FileNotFoundError(
        "Local temporary file was not created."
    )

local_size = os.path.getsize(local_temp)

print(
    f"Local temporary file size: "
    f"{local_size / (1024**3):.2f} GB"
)


# ============================================================
# COLUMN CHECK
# ============================================================

check = pd.read_csv(
    local_temp,
    sep="\t",
    nrows=2
)

expected_columns = [
    "entity_id",
    "business_name",
    "business_address",
    "country",
    "business_name_clean",
    "business_address_clean",
    "business_name_normalized",
    "business_address_normalized"
]

if list(check.columns) != expected_columns:

    raise ValueError(
        "❌ Column verification failed.\n"
        f"Got: {list(check.columns)}"
    )

print("✅ Column verification PASSED")


# ============================================================
# COPY TO DRIVE
# ============================================================

print("\nCopying completed file to Google Drive...")
print("Please wait...")

if os.path.exists(drive_output):
    os.remove(drive_output)

shutil.copy2(
    local_temp,
    drive_output
)

print("✅ Copy completed")


# ============================================================
# VERIFY DRIVE FILE
# ============================================================

if not os.path.exists(drive_output):
    raise FileNotFoundError(
        "❌ Final Drive file was not created."
    )

drive_size = os.path.getsize(drive_output)

print(
    f"Drive file size: "
    f"{drive_size / (1024**3):.2f} GB"
)

print("\nVerifying final Drive row count...")

drive_rows = sum(
    1 for _ in open(
        drive_output,
        encoding="utf-8"
    )
) - 1

print(f"Drive rows    : {drive_rows:,}")
print(f"Expected rows : {EXPECTED_ROWS:,}")


if drive_rows != EXPECTED_ROWS:

    raise ValueError(
        f"❌ FINAL DRIVE ROW COUNT ERROR!\n"
        f"Expected: {EXPECTED_ROWS:,}\n"
        f"Got:      {drive_rows:,}"
    )


# ============================================================
# CLEAN LOCAL TEMP
# ============================================================

os.remove(local_temp)


# ============================================================
# SUCCESS
# ============================================================

print("\n")
print("=" * 70)
print("🎉 TRAIN SOURCE 3 REBUILD SUCCESSFUL")
print("=" * 70)

print(f"Rows: {drive_rows:,}")
print("File: train_source3_cleaned.tsv")
print("Location: Google Drive / cleaned_data")

print("\n⛔ DO NOT START EDA YET")
print("Next step: final verification of all 6 files.")
print("=" * 70)

✅ Original Train Source 3 found
Expected rows: 5,285,603

Chunk 1: 250,000 rows | Total: 250,000
Chunk 2: 250,000 rows | Total: 500,000
Chunk 3: 250,000 rows | Total: 750,000
Chunk 4: 250,000 rows | Total: 1,000,000
Chunk 5: 250,000 rows | Total: 1,250,000
Chunk 6: 250,000 rows | Total: 1,500,000
Chunk 7: 250,000 rows | Total: 1,750,000
Chunk 8: 250,000 rows | Total: 2,000,000
Chunk 9: 250,000 rows | Total: 2,250,000
Chunk 10: 250,000 rows | Total: 2,500,000
Chunk 11: 250,000 rows | Total: 2,750,000
Chunk 12: 250,000 rows | Total: 3,000,000
Chunk 13: 250,000 rows | Total: 3,250,000
Chunk 14: 250,000 rows | Total: 3,500,000
Chunk 15: 250,000 rows | Total: 3,750,000
Chunk 16: 250,000 rows | Total: 4,000,000
Chunk 17: 250,000 rows | Total: 4,250,000
Chunk 18: 250,000 rows | Total: 4,500,000
Chunk 19: 250,000 rows | Total: 4,750,000
Chunk 20: 250,000 rows | Total: 5,000,000
Chunk 21: 250,000 rows | Total: 5,250,000
Chunk 22: 35,603 rows | Total: 5,285,603


======================================================================
LOCAL PROCESSING COMPLETE
======================================================================
Rows processed : 5,285,603
Expected rows  : 5,285,603
✅ Row count verification PASSED
Local temporary file size: 1.22 GB
✅ Column verification PASSED

Copying completed file to Google Drive...
Please wait...
✅ Copy completed
Drive file size: 1.22 GB

Verifying final Drive row count...
Drive rows    : 5,285,603
Expected rows : 5,285,603


======================================================================
🎉 TRAIN SOURCE 3 REBUILD SUCCESSFUL
======================================================================
Rows: 5,285,603
File: train_source3_cleaned.tsv
Location: Google Drive / cleaned_data

⛔ DO NOT START EDA YET
Next step: final verification of all 6 files.
======================================================================

In [ ]:
import os

output_dir = "/content/drive/MyDrive/Business_model_amazon/cleaned_data"

expected = {
    "train_source1_cleaned.tsv": 2_206_821,
    "train_source2_cleaned.tsv": 5_034_616,
    "train_source3_cleaned.tsv": 5_285_603,
    "test_source1_cleaned.tsv": 1_732_544,
    "test_source2_cleaned.tsv": 4_887_273,
    "test_source3_cleaned.tsv": 5_082_316
}

print("FINAL DATA CLEANING VERIFICATION\n")

all_passed = True

for filename, expected_rows in expected.items():

    path = os.path.join(output_dir, filename)

    if not os.path.exists(path):
        all_passed = False
        print(f"❌ MISSING | {filename}")
        continue

    actual_rows = sum(
        1 for _ in open(path, encoding="utf-8")
    ) - 1

    if actual_rows == expected_rows:
        print(
            f"✅ PASS | {filename} | "
            f"{actual_rows:,} / {expected_rows:,}"
        )
    else:
        all_passed = False
        print(
            f"❌ WRONG | {filename} | "
            f"{actual_rows:,} / {expected_rows:,}"
        )

print("\n" + "=" * 65)

if all_passed:
    print("🎉 ALL 6 FILES VERIFIED SUCCESSFULLY")
    print("✅ DATA CLEANING STAGE COMPLETE")
else:
    print("❌ SOME FILES NEED ATTENTION")

print("=" * 65)

FINAL DATA CLEANING VERIFICATION

✅ PASS | train_source1_cleaned.tsv | 2,206,821 / 2,206,821
✅ PASS | train_source2_cleaned.tsv | 5,034,616 / 5,034,616
✅ PASS | train_source3_cleaned.tsv | 5,285,603 / 5,285,603
✅ PASS | test_source1_cleaned.tsv | 1,732,544 / 1,732,544
✅ PASS | test_source2_cleaned.tsv | 4,887,273 / 4,887,273
✅ PASS | test_source3_cleaned.tsv | 5,082,316 / 5,082,316

=================================================================
🎉 ALL 6 FILES VERIFIED SUCCESSFULLY
✅ DATA CLEANING STAGE COMPLETE
=================================================================